Repository OpenCTI-Platform/opencti, pull requests merged in 2023-07, with the labels that each got.

#3302 [frontend/backend] Added Customizable Header/Footer banner and Idle Time Screen Masking then Logout
  opencti-platform/opencti-front/src/private/Index.jsx
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/IdleTimeoutLockscreen.tsx
  opencti-platform/opencti-front/src/private/components/analysis/groupings/GroupingKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analysis/reports/ReportKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/Feedbacks.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservables.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjects.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainersGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileToolbar.jsx
  opencti-platform/opencti-front/src/private/components/common/menus/NavToolbarMenu.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectKnowledgeBar.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationships.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectsRightBar.jsx
  opencti-platform/opencti-front/src/private/components/data/Entities.jsx
  opencti-platform/opencti-front/src/private/components/data/IngestionMenu.jsx
  opencti-platform/opencti-front/src/private/components/data/Relationships.jsx
  opencti-platform/opencti-front/src/private/components/data/SharingMenu.jsx
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/private/components/observations/Indicators.tsx
  opencti-platform/opencti-front/src/private/components/observations/StixCyberObservables.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorsRightBar.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/StixDomainObjectIndicators.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservablesRightBar.jsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/Labels.jsx
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/private/components/settings/Vocabularies.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/ToolBar.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Root.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraphBar.jsx
  opencti-platform/opencti-front/src/public/Root.js
  opencti-platform/opencti-front/src/public/components/Login.tsx
  opencti-platform/opencti-front/src/public/components/SystemBanners.js
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-front/src/utils/SystemBanners.tsx
  opencti-platform/opencti-front/src/utils/Time.js
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/resolvers/settings.js
Labels: community

#3612 [frontend] avoid re-render when click in the settings hidden entity types list (#3611)
  opencti-platform/opencti-front/src/private/components/settings/entity_settings/HiddenInRoles.tsx
  opencti-platform/opencti-front/src/private/components/settings/entity_settings/HiddenInRolesContainer.tsx
  opencti-platform/opencti-front/src/private/components/settings/entity_settings/HiddenTypesList.tsx
Labels: bug, filigran team

#3576 [backend/frontend] add organization management in the Security section (#3520)
  opencti-platform/opencti-front/src/components/FieldOrEmpty.tsx
  opencti-platform/opencti-front/src/private/components/settings/AccessesMenu.tsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/SettingsOrganizations.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganization.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganizationDetails.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganizationLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganizationsLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/MembersList.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/organization.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/organization.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/organization-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixCoreRelationship-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixDomainObject-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/sync-utils.js
  opencti-platform/opencti-graphql/tests/data/DATA-TEST-STIX2_v2.json
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#3615 [frontend] avoid re-render on case template (#3609)
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplateTasks.tsx
Labels: filigran team

#3569 [backend/frontend] Add a broadcast message in administration (#2508)
  opencti-platform/opencti-front/src/__tests__/components/settings/SettingsMessagesBanner.test.tsx
  opencti-platform/opencti-front/src/components/DeleteDialog.tsx
  opencti-platform/opencti-front/src/private/Index.jsx
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileToolbar.jsx
  opencti-platform/opencti-front/src/private/components/common/menus/NavToolbarMenu.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectKnowledgeBar.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectContentFiles.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectsRightBar.jsx
  opencti-platform/opencti-front/src/private/components/data/IngestionMenu.jsx
  opencti-platform/opencti-front/src/private/components/data/SharingMenu.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorsRightBar.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservablesRightBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessageCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessageEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessageForm.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessages.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessagesBanner.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessagesLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessagesLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessagesPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/withHooksSettingsMessagesBannerHeight.js
  opencti-platform/opencti-front/src/private/components/settings/sub_types/entitySetting/EntitySettingAttributeLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-front/src/utils/hooks/useBus.ts
  opencti-platform/opencti-front/src/utils/hooks/useDeletion.ts
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-front/vitest.config.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/manager/activityManager.ts
  opencti-platform/opencti-graphql/src/manager/cacheManager.ts
  opencti-platform/opencti-graphql/src/manager/clusterManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/resolvers/settings.js
  opencti-platform/opencti-graphql/src/types/settings.d.ts
  opencti-platform/opencti-graphql/src/types/store.d.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/settings-test.js
Labels: filigran team

#3577 [frontend/backend] Dashboard persistance and update in server (#issue/3163)
  opencti-platform/opencti-front/src/components/FieldOrEmpty.tsx
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/private/components/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/DashboardSettings.jsx
  opencti-platform/opencti-front/src/private/components/analysis/Reports.tsx
  opencti-platform/opencti-front/src/private/components/common/location/LocationMiniMapTargets.jsx
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
  opencti-platform/opencti-front/src/private/components/profile/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/ListParameters.js
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
Labels: filigran team

#3599 [backend/frontend] Export investigation in JSON as STIX report (#1374)
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-front/src/utils/Time.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-resolver.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
Labels: filigran team

#3618 Fix settings message banner display
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessagesBanner.tsx
Labels: filigran team

#3601 [frontend/backend] Add triggers management in Organizations overview settings screen (#3520)
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/common/Triggers.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganization.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-domain.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-resolver.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-types.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification.graphql
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/organization-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixDomainObject-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/trigger-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#3621 [frontend/backend] Allow color customization for banner messages (#2508)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessageForm.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessages.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessagesBanner.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessagesLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Colors.js
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/types/settings.d.ts
Labels: filigran team

#3602 Make the platform supports opinion custom vocab / scale (#3003)
  opencti-platform/opencti-front/src/private/components/analysis/opinions/StixCoreObjectOpinions.jsx
  opencti-platform/opencti-front/src/private/components/analysis/opinions/StixCoreObjectOpinions.tsx
  opencti-platform/opencti-front/src/private/components/analysis/opinions/StixCoreObjectOpinionsRadar.jsx
  opencti-platform/opencti-front/src/private/components/analysis/opinions/StixCoreObjectOpinionsRadar.tsx
  opencti-platform/opencti-front/src/private/components/common/form/OpenVocabField.tsx
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/Vocabularies.tsx
  opencti-platform/opencti-front/src/private/components/settings/attributes/VocabulariesLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/attributes/VocabularyCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/attributes/VocabularyEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/attributes/VocabularyPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplateTasksLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/entity_settings/HiddenTypesList.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Colors.js
  opencti-platform/opencti-front/src/utils/FormikUtils.ts
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-front/src/utils/hooks/useVocabularyCategory.tsx
  opencti-platform/opencti-front/src/utils/utils.ts
  opencti-platform/opencti-graphql/src/domain/opinion.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/initialization.js
  opencti-platform/opencti-graphql/src/migrations/1688710489709-add_order_to_opinion_ov.js
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary-domain.ts
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary-utils.ts
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary.graphql
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary.ts
Labels: filigran team

#3638 [frontend/backend] Add default dashboards in group and organizations
  opencti-platform/opencti-front/src/private/Index.jsx
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/DashboardSettings.jsx
  opencti-platform/opencti-front/src/private/components/common/form/DashboardField.tsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/private/components/nav/TopMenuDashboard.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganization.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganizationEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessagesBanner.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-front/src/utils/hooks/useBus.ts
  opencti-platform/opencti-front/src/utils/hooks/useFormEditor.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
  opencti-platform/opencti-graphql/src/resolvers/group.js
  opencti-platform/opencti-graphql/src/resolvers/organization.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/group-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
Labels: filigran team

#3636 [backend] Adapt update to use element _index
  opencti-platform/opencti-graphql/src/domain/work.js
  opencti-platform/opencti-graphql/src/manager/connectorManager.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
Labels: filigran team

#3626 Members and triggers in Group/User/Orga overview should be sortable and searchable (#3595)
  opencti-platform/opencti-front/src/components/ColumnsLinesTitles.tsx
  opencti-platform/opencti-front/src/private/components/profile/TriggerLineTitles.tsx
  opencti-platform/opencti-front/src/private/components/profile/Triggers.tsx
  opencti-platform/opencti-front/src/private/components/settings/Users.jsx
  opencti-platform/opencti-front/src/private/components/settings/common/Triggers.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganization.tsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplateLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/GroupUsers.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/GroupUsersLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/MembersList.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/SettingsOrganizationUsers.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/SettingsOrganizationUsersLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserLineTitles.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/group.js
  opencti-platform/opencti-graphql/src/resolvers/organization.js
Labels: filigran team

#3717 [backend] Fix unusable filters
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
Labels: filigran team

#3715 [backend/frontend] Add relations between entities
  opencti-platform/opencti-front/src/utils/Relation.js
  opencti-platform/opencti-graphql/src/database/stix.ts
Labels: filigran team

#3767 [backend] Add global trimming string when preparing data for ingestion (#3022)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/01-unit/database/engine-test.js
Labels: filigran team

#3839 [frontend] Close dialog on create/update opinion
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsRadar.tsx
Labels: filigran team

#3797 [backend/frontend] Be able to add images in overview of some entity types (#issue/2540)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/private/components/common/files/PictureManagementViewer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectBookmark.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualCard.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualDetails.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/utils.ts
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/administrativeArea/administrativeArea.graphql
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rft/case-rft.graphql
  opencti-platform/opencti-graphql/src/modules/case/case.graphql
  opencti-platform/opencti-graphql/src/modules/case/feedback/feedback.graphql
  opencti-platform/opencti-graphql/src/modules/channel/channel.graphql
  opencti-platform/opencti-graphql/src/modules/dataComponent/dataComponent.graphql
  opencti-platform/opencti-graphql/src/modules/dataSource/dataSource.graphql
  opencti-platform/opencti-graphql/src/modules/event/event.graphql
  opencti-platform/opencti-graphql/src/modules/grouping/grouping.graphql
  opencti-platform/opencti-graphql/src/modules/language/language.graphql
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis.graphql
  opencti-platform/opencti-graphql/src/modules/narrative/narrative.graphql
  opencti-platform/opencti-graphql/src/modules/task/task.graphql
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.graphql
  opencti-platform/opencti-graphql/src/resolvers/stixDomainObject.js
  opencti-platform/opencti-graphql/src/types/store.d.ts
Labels: filigran team

#3847 [frontend] fix Malware analyses names in Cases/Analyses "Entities" view
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsMappingLine.jsx
Labels: filigran team
