Repository OpenCTI-Platform/opencti, pull requests merged in 2023-06, with the labels that each got.

#3448 [backend/frontend] Extends mandatory attributes to relationships and sightings (#3210)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationForm.js
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromRelation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreationForm.js
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipOverview.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorAddObservablesLines.jsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/EntitySetting.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/SubTypes.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/ToolBar.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/modules/attributes/stixCoreRelationship-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixSightingRelationship-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-utils.ts
  opencti-platform/opencti-graphql/src/modules/relationsRef/stixRelationship-registrationRef.ts
Labels: filigran team

#3447 [frontend] In create/update a trigger, the filters on multiple lines are not correctly displayed (#3439)
  opencti-platform/opencti-front/src/components/FilterIconButton.tsx
Labels: filigran team

#3449 [frontend] In an Intrusion Set => Knowledge => Malware, keyword is disappearing between Entities / Relations views (#issue/3440)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationships.jsx
Labels: filigran team

#3472 [backend] List of available streams should take care of groups restrictions (#3020)
  opencti-platform/opencti-graphql/src/domain/stream.js
  opencti-platform/opencti-graphql/src/utils/access.ts
Labels: filigran team

#3383 [backend/frontend] Add a new capability to restrict the access to users list (#3151)
  opencti-platform/opencti-front/src/components/list_cards/ListCards.jsx
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
  opencti-platform/opencti-front/src/private/components/common/form/CreatorField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/ObjectAssigneeField.jsx
  opencti-platform/opencti-front/src/private/components/common/identities/IdentitySearch.js
  opencti-platform/opencti-front/src/private/components/common/lists/FilterAutocomplete.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/Filters.jsx
  opencti-platform/opencti-front/src/private/components/common/lists/FiltersElement.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/ListFilters.jsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentsCards.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
  opencti-platform/opencti-graphql/src/initialization.js
  opencti-platform/opencti-graphql/src/migrations/1611671597858-standard_id.js
  opencti-platform/opencti-graphql/src/migrations/1612381566895-clear_indicates_indexation.js
  opencti-platform/opencti-graphql/src/migrations/1612999232704-fix_attack_patterns.js
  opencti-platform/opencti-graphql/src/migrations/1613150325865-clear_aliases.js
  opencti-platform/opencti-graphql/src/migrations/1614942944848-fix_locations_identities.js
  opencti-platform/opencti-graphql/src/migrations/1616890781521-fix_aliases.js
  opencti-platform/opencti-graphql/src/migrations/1619270898754-migrate_incidents.js
  opencti-platform/opencti-graphql/src/migrations/1620980638439-fix_attack_patterns.js
  opencti-platform/opencti-graphql/src/migrations/1630337822820-report_status.js
  opencti-platform/opencti-graphql/src/migrations/1637328713848-system_standard_id.js
  opencti-platform/opencti-graphql/src/migrations/1643894590312-change_resolves-to.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/src/utils/access.ts
Labels: filigran team

#3490 [frontend] Add button for addInContainer in toolbar
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rft/case-rft.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-task/case-task.graphql
  opencti-platform/opencti-graphql/src/modules/case/case.graphql
  opencti-platform/opencti-graphql/src/modules/case/feedback/feedback.graphql
  opencti-platform/opencti-graphql/src/modules/grouping/grouping.graphql
  opencti-platform/opencti-graphql/src/resolvers/container.js
Labels: filigran team

#3497 [backend/frontend] Enforce all creation input to be mandatory to prevent any API mistakes (#3480)
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionMarkings.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionRoles.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionUsers.jsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEditionGroups.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#3274 [backend/frontend] Added support for Consent Message on Login Page
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/public/LoginRoot.tsx
  opencti-platform/opencti-front/src/public/components/Login.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
Labels: community

#3483 [backend] fix dashboard entities list filtered by related entity (#3476)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/schema/stixCoreObject.ts
Labels: filigran team

#3468 [frontend] Add the lasso selection tool in graphs (#3109)
  opencti-platform/opencti-front/src/private/components/analysis/reports/ReportKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/analysis/reports/ReportKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/analysis/reports/ReportKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfi/CaseRfiKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfi/CaseRfiKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfi/CaseRfiKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rft/CaseRftKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rft/CaseRftKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rft/CaseRftKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/incidents/IncidentKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/incidents/IncidentKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/incidents/IncidentKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraphBar.jsx
  opencti-platform/opencti-front/src/utils/Graph.js
  opencti-platform/opencti-front/src/utils/ListParameters.js
  opencti-platform/opencti-front/src/utils/graph/LassoSelection.tsx
Labels: filigran team

#3517 [frontend] Add Note resolution in TimeLine (#3486)
  opencti-platform/opencti-front/src/private/components/analysis/reports/ReportKnowledgeTimeLine.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfi/CaseRfiKnowledgeTimeLine.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rft/CaseRftKnowledgeTimeLine.jsx
  opencti-platform/opencti-front/src/private/components/cases/incidents/IncidentKnowledgeTimeLine.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsTimeline.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationshipsTimeline.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipsTimeline.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectsTimeline.jsx
  opencti-platform/opencti-front/src/utils/graph/LassoSelection.tsx
Labels: filigran team

#3537 [frontend] - NOT FINAL FIX, but prevent crash
  opencti-platform/opencti-front/src/private/components/analysis/groupings/GroupingKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analysis/reports/ReportKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfi/CaseRfiKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rft/CaseRftKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/incidents/IncidentKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraphBar.jsx
Labels: filigran team

#3353 [backend/frontend] Settings overview of user , display the user triggers & digests (#3160)
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/private/components/profile/TriggerLineTitles.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationLine.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerCreation.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerDigestCreation.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerLiveCreation.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerPopover.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggersField.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggersLines.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggersQueries.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/User.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistory.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistoryLine.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Charts.js
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js
  opencti-platform/opencti-graphql/src/manager/activityManager.ts
  opencti-platform/opencti-graphql/src/manager/historyManager.ts
  opencti-platform/opencti-graphql/src/migrations/1686647636564-triggers-add-authorized-members.js
  opencti-platform/opencti-graphql/src/modules/notification/notification-domain.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-resolver.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-types.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification.graphql
  opencti-platform/opencti-graphql/src/modules/notification/notification.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-resolver.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-types.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/src/utils/authorizedMembers.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/group-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/role-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/trigger-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#3535 [backend] Fix entity creation with associated file (#3534)
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/file.js
Labels: filigran team

#3526 [frontend] Hide add in container button for unusable types
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#3523 [frontend/backend] Display related Malware-analyses in Obs overview (#3478)
  opencti-platform/opencti-front/src/private/components/analysis/malware_analyses/MalwareAnalysisDetails.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectNestedEntitiesLines.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableDetails.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableMalwareAnalyses.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableMalwareAnalysesDummyList.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/audit/Audit.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/audit/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/configuration/Configuration.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis.graphql
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis.ts
Labels: filigran team

#3548 [frontend/backend] add associated file to Malware Analysis
  opencti-platform/opencti-front/src/private/components/analysis/malware_analyses/MalwareAnalysisCreation.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis.graphql
Labels: filigran team

#3559 [frontend] display Notes abstract in Reports-->Entities (#3557)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjectLine.jsx
Labels: bug, filigran team

#3558 [frontend] notifications improvement and bug fix (#3555)
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/private/components/profile/Notifications.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationLine.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationsToolBar.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/ToolBar.jsx
  opencti-platform/opencti-front/src/utils/Localization.js
Labels: bug, filigran team

#3579 [backend] Listing with search criteria prevent pagination usage with cursor (#3578)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
Labels: filigran team

#3567 [frontend/backend] Add triggers management in Group overview settings (#3520)
  opencti-platform/opencti-front/src/private/components/profile/TriggerLineTitles.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerLine.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/Triggers.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/User.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/migrations/1687529127415-triggers-remove-unused-field.js
  opencti-platform/opencti-graphql/src/modules/notification/notification-domain.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-resolver.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification.graphql
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/trigger-test.js
Labels: filigran team

#3563 [frontend] Create analyst workbench from an entity (#3188)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileCreator.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileLine.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileViewer.jsx
  opencti-platform/opencti-front/src/private/components/import/ImportContent.jsx
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team
