Repository OpenCTI-Platform/opencti, pull requests merged in 2023-12, with the labels that each got.

#5019 [frontend] improve global search layout (#1483)
  opencti-platform/opencti-front/src/private/components/SearchRoot.tsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/private/components/settings/file_indexing/FileIndexing.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/file-search.js
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/domain/indexedFile.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/schema.js
  opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
  opencti-platform/opencti-graphql/src/resolvers/file.js
  opencti-platform/opencti-graphql/src/resolvers/indexedFile.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/index-file-test.js
Labels: filigran team

#5037 [frontend] Fix search when lasso selection
  opencti-platform/opencti-front/src/utils/graph/LassoSelection.tsx
Labels: filigran team

#5042 [backend] Avoid upserting a filled attribute with something null (#4804)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#5030 [backend] Improve CPU usage of elastic/open.search results parsing (#5029)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#5006 [backend/frontend] Improve auditing to split file read and file download (#5005)
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/listener/UserActionListener.ts
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/resolvers/log.js
Labels: filigran team

#5044 [backend/frontend] Improve id conversion between platforms (#3242)
  opencti-platform/opencti-front/src/components/ExportButtons.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceCreation.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetPopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/widgetExportHandler.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/workspaceExportHandler.ts
  opencti-platform/opencti-front/src/private/components/workspaces/workspaceExportHandler.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-resolver.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/workspace-test.js
  opencti-platform/opencti-graphql/tests/data/20231123_invalid_type_octi_widget_list.json
  opencti-platform/opencti-graphql/tests/data/20231123_invalid_version_octi_widget_list.json
  opencti-platform/opencti-graphql/tests/data/20231123_octi_widget_list.json
Labels: filigran team

#5083 [frontend] Improve file indexing layout (#1483)
  opencti-platform/opencti-front/src/private/components/settings/file_indexing/FileIndexingMonitoring.tsx
Labels: filigran team

#5086 [backend] sanitize dates coming from RSS feed
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/utils/format.js
Labels: filigran team

#5091 Fix case template filter key, taskContains > tasks (#5089)
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplateTasks.tsx
Labels: filigran team

#5101 [backend] Domain Name Observable accepts unicode characters (#5045)
  opencti-platform/opencti-graphql/src/utils/syntax.js
Labels: filigran team

#5108 [backend] source_reliability filter with nil / not_nil operator (#5106)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
Labels: filigran team

#5125 [backend] fix filters in TimeSeries Widgets (#5124)
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
Labels: filigran team

#5128 On-demand deployment of feature branch for early testing
  .github/workflows/test-feature-branch.yml
  opencti-platform/Dockerfile_ga
Labels: filigran team

#5127 [backend] Add tests for observable syntax regex pattern (#5045)
  opencti-platform/opencti-graphql/src/utils/syntax.js
  opencti-platform/opencti-graphql/tests/01-unit/utils/syntax-test.ts
Labels: filigran team

#5109 [frontend/backend] restrict api filter keys to EQ operator and OR local mode (#5103)
  opencti-platform/opencti-front/src/components/FilterIconButton.tsx
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/FilterIconButtonGlobalOperator.tsx
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/components/filters/FilterValues.tsx
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainertKnowledgeTimeLineBar.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainers.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChain.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectThreatKnowledge.tsx
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-front/src/utils/filters/SearchEntitiesUtil.ts
  opencti-platform/opencti-front/src/utils/filters/filtersLocalStorageUtil.ts
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorageModel.ts
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
  opencti-platform/opencti-graphql/src/domain/log.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-resolution.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
Labels: filigran team

#5139 [backend] Fix search in files query (#5129)
  opencti-platform/opencti-graphql/src/database/file-search.js
  opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
Labels: filigran team

#5154 [backend] authorize api filters keys for retention policies checking (#5153)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/domain/retentionRule.js
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
Labels: filigran team

#5132 [backend] Customize time range of relationship de-deduplication (#3387)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#5131 [backend/frontend] Refactor files management to rely on internal engine instead of S3 (#4583)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileCreator.tsx
  opencti-platform/opencti-front/src/private/components/settings/file_indexing/FileIndexingConfiguration.tsx
  opencti-platform/opencti-front/src/private/components/settings/file_indexing/FileIndexingConfigurationAndMonitoring.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
  opencti-platform/opencti-graphql/src/migrations/1701354091174-files-registration.js
  opencti-platform/opencti-graphql/src/migrations/1701354091184-file_mappings.js
  opencti-platform/opencti-graphql/src/modules/index.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-types.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document.ts
  opencti-platform/opencti-graphql/src/modules/managerConfiguration/managerConfiguration-domain.ts
  opencti-platform/opencti-graphql/src/modules/managerConfiguration/managerConfiguration-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/managerConfiguration/managerConfiguration-utils.ts
  opencti-platform/opencti-graphql/src/resolvers/externalReference.js
  opencti-platform/opencti-graphql/src/resolvers/file.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/resolvers/stixDomainObject.js
  opencti-platform/opencti-graphql/src/schema/internalObject.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
Labels: filigran team

#5167 [frontend] The top of the graph view in an entity is broken (#5164)
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainers.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainersGraph.jsx
Labels: filigran team

#5172 [backend] fix file deletion (#5166)
  opencti-platform/opencti-front/src/private/components/observations/artifacts/Root.jsx
  opencti-platform/opencti-graphql/src/database/file-storage.js
Labels: filigran team

#5174 [frontend] fix widgets filters (#5168)
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsList.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsMultiAreaChart.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsMultiHeatMap.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsMultiLineChart.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsMultiVerticalBars.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsNumber.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsMultiHeatMap.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectBookmarksList.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsMultiHorizontalBars.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsTreeMap.jsx
Labels: filigran team, Filters

#5188 [backend/frontend] File indexing fixes and improvements (#5187)
  opencti-platform/opencti-front/src/private/components/SearchRoot.tsx
  opencti-platform/opencti-front/src/private/components/settings/file_indexing/FileIndexingMonitoring.tsx
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-graphql/src/domain/file.js
Labels: filigran team

#5196 [frontend] Fix column headers (#5196)
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
Labels: filigran team

#5194 [frontend] add targets filter in Knowledge entities list of threats (#5193)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectThreatKnowledge.tsx
Labels: filigran team, filters

#5192 [frontend] fix 'based on an observable' filter (#5191)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicators.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/observations/Indicators.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/StixDomainObjectIndicators.tsx
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
Labels: filigran team, filters

#5217 [frontend] fix filters in Knowledge view of an entity (#5216)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsRelationshipsView.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team, filters

#5213 [frontend] Fix error when creating Software from Vulnerability (#5198)
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/AddSoftwares.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorAddObservablesLines.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
Labels: filigran team

#5215 [frontend] fix entity type context in background tasks filters (#5214)
  opencti-platform/opencti-front/src/components/FilterIconButton.tsx
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/TaskFilterValue.tsx
  opencti-platform/opencti-front/src/components/TasksFilterValueContainer.tsx
  opencti-platform/opencti-front/src/components/filters/DisplayFilterGroup.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservables.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectThreatKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/EntityStixSightingRelationships.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team, filters

#5211 [frontend/backend] handle entity_type filter in bookmark widgets (#5182)
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectBookmarksList.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
Labels: filigran team, filters

#5180 [frontend] switch translation key when relationship (#5142)
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationExpandForm.tsx
Labels: filigran team

#5224 [frontend] add the possibility to filter some entities by name (#5223)
  opencti-platform/opencti-front/src/private/components/analyses/Groupings.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Channels.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Malwares.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Tools.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Vulnerabilities.tsx
  opencti-platform/opencti-front/src/private/components/cases/CaseIncidents.tsx
  opencti-platform/opencti-front/src/private/components/cases/CaseRfis.tsx
  opencti-platform/opencti-front/src/private/components/cases/CaseRfts.tsx
  opencti-platform/opencti-front/src/private/components/cases/Feedbacks.tsx
  opencti-platform/opencti-front/src/private/components/entities/Events.tsx
  opencti-platform/opencti-front/src/private/components/entities/Individuals.tsx
  opencti-platform/opencti-front/src/private/components/entities/Organizations.tsx
  opencti-platform/opencti-front/src/private/components/entities/Systems.tsx
  opencti-platform/opencti-front/src/private/components/events/Incidents.tsx
  opencti-platform/opencti-front/src/private/components/locations/AdministrativeAreas.tsx
  opencti-platform/opencti-front/src/private/components/locations/Cities.tsx
  opencti-platform/opencti-front/src/private/components/locations/Countries.tsx
  opencti-platform/opencti-front/src/private/components/locations/Positions.tsx
  opencti-platform/opencti-front/src/private/components/locations/Regions.tsx
  opencti-platform/opencti-front/src/private/components/observations/Indicators.tsx
  opencti-platform/opencti-front/src/private/components/observations/Infrastructures.tsx
  opencti-platform/opencti-front/src/private/components/techniques/AttackPatterns.tsx
  opencti-platform/opencti-front/src/private/components/techniques/CoursesOfAction.tsx
  opencti-platform/opencti-front/src/private/components/techniques/DataComponents.tsx
  opencti-platform/opencti-front/src/private/components/techniques/DataSources.tsx
  opencti-platform/opencti-front/src/private/components/threats/Campaigns.tsx
  opencti-platform/opencti-front/src/private/components/threats/IntrusionSets.tsx
  opencti-platform/opencti-front/src/private/components/threats/ThreatActorsGroup.tsx
  opencti-platform/opencti-front/src/private/components/threats/ThreatActorsIndividual.tsx
Labels: filigran team, filters

#5152 [Frontend/Backend] Quick fixes for existing CSV Mapper (#4932)
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/CsvMapperRepresentationForm.tsx
  opencti-platform/opencti-graphql/src/domain/attribute-utils.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/schema/stixDomainObject.ts
Labels: filigran team

#5233 [frontend] fix display issue on Triggers in user overview (#5232)
  opencti-platform/opencti-front/src/private/components/settings/common/Triggers.tsx
Labels: filigran team

#5185 [frontend] Redirect from user Overview to all entities and relations created by the user (#2563)
  opencti-platform/opencti-front/src/private/components/settings/common/Triggers.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistory.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistory.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistoryLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistoryLines.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistoryLines.tsx
Labels: filigran team

#5236 [frontend] rename observable_value column in Representation (#5225)
  opencti-platform/opencti-front/src/private/components/observations/StixCyberObservables.tsx
  opencti-platform/opencti-front/src/utils/Localization.js
Labels: filigran team, filters

#5235 [frontend] avoid representatives filters queries if no filters (#5234)
  opencti-platform/opencti-front/src/components/FilterIconButton.tsx
Labels: filigran team, filters

#5245 [backend] Too many files in minio can prevent correct migration execution (#5244)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/migrations/1701354091189-files-registration.js
Labels: filigran team

#5248 [backend] Improve observable merging to support multi operations (#5247)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#5144 [frontend] Fix interface bugs on data import page
  opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx
  opencti-platform/opencti-front/src/private/components/import/ImportContent.jsx
Labels: filigran team

#5256 [frontend] Fix broken by filigran logo
  opencti-platform/opencti-front/src/public/components/Login.tsx
Labels: filigran team

#5189 Search all possible values in identity filters (#3585)
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/private/components/settings/VocabularyQuery.js
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
Labels: filigran team, filters

#5253 [frontend] Redirect from user Overview to all entities and relations created by user (#2563)
  opencti-platform/opencti-front/src/utils/Localization.js
Labels: filigran team

#5272 [backend/frontend] Invalidate empty CSV mappers (#4644)
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperForm.tsx
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-utils.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/csv-mapper-utils-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/csv-parser-test.js
  opencti-platform/opencti-graphql/tests/data/csv-mapper-mock-simple-different-entities.ts
Labels: filigran team

#5281 [frontend] Export button remove on Investigation (#5271)
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
Labels: filigran team

#5289 [backend] Prevent inferences modification to be part of history by default (#5288)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/manager/historyManager.ts
Labels: filigran team

#5282 [frontend] fix autocomplete to search containers (#5276)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContainer.jsx
Labels: filigran team

#5291 [backend] configure yarn test:dev to be in watch mode
  opencti-platform/opencti-graphql/package.json
Labels: filigran team

#5312 [frontend/backend] Filter stix domain object on Data & Search UI and check type in tasks (#5308)
  opencti-platform/opencti-front/src/private/components/Search.tsx
  opencti-platform/opencti-front/src/private/components/data/Entities.tsx
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
Labels: filigran team

#5261 [backend/frontend] Move indicator to module (#2859)
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorPopover.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/graphql-codegen.yml
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/database/stix-representative.ts
  opencti-platform/opencti-graphql/src/database/stix.ts
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/schema.js
  opencti-platform/opencti-graphql/src/manager/expiredManager.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/migrations/1612381566895-clear_indicates_indexation.js
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/index.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-converter.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-resolver.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-types.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-utils.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.graphql
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
  opencti-platform/opencti-graphql/src/modules/relationsRef/stixDomainObject-registrationRef.ts
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary-types.ts
  opencti-platform/opencti-graphql/src/rules/indicate-sighted/IndicateSightedDefinition.ts
  opencti-platform/opencti-graphql/src/rules/observed-sighting/ObserveSightingDefinition.ts
  opencti-platform/opencti-graphql/src/rules/observed-sighting/ObserveSightingRule.ts
  opencti-platform/opencti-graphql/src/rules/report-refs-indicator-based-on/ReportRefIndicatorBasedOnDefinition.ts
  opencti-platform/opencti-graphql/src/rules/report-refs-indicator-based-on/ReportRefIndicatorBasedOnRule.ts
  opencti-platform/opencti-graphql/src/rules/report-refs-observable-based-on/ReportRefObservableBasedOnDefinition.ts
  opencti-platform/opencti-graphql/src/rules/report-refs-observable-based-on/ReportRefObservableBasedOnRule.ts
  opencti-platform/opencti-graphql/src/rules/sighting-incident/SightingIncidentDefinition.ts
  opencti-platform/opencti-graphql/src/rules/sighting-incident/SightingIncidentRule.ts
  opencti-platform/opencti-graphql/src/rules/sighting-indicator/SightingIndicatorDefinition.ts
  opencti-platform/opencti-graphql/src/rules/sighting-observable/SightingObservableDefinition.ts
  opencti-platform/opencti-graphql/src/rules/sighting-observable/SightingObservableRule.ts
  opencti-platform/opencti-graphql/src/schema/identifier.js
  opencti-platform/opencti-graphql/src/schema/stixDomainObject.ts
  opencti-platform/opencti-graphql/src/types/stix-sdo.d.ts
  opencti-platform/opencti-graphql/src/types/store.d.ts
  opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js
  opencti-platform/opencti-graphql/tests/01-unit/database/stix-filtering-testers-test.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/indicator-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
  opencti-platform/opencti-graphql/tests/05-rules/observe-sighting-test.js
  opencti-platform/opencti-graphql/tests/05-rules/report-refs-observable-based-on-test.js
  opencti-platform/opencti-graphql/tests/05-rules/sighting-incident-test.js
Labels: filigran team

#5320 [backend] Fix ignoring boolean value when false in csv mapper (#5300)
  opencti-platform/opencti-graphql/src/parser/csv-mapper.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/csv-parser-test.js
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/entities-with-booleans/malwares.csv
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/entities-with-booleans/mapper.ts
Labels: filigran team

#5322 [frontend] Fix url search keyword in top bar input (#5321)
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
Labels: filigran team

#5311 [worker] Improve worker logging related to client python refactor
  opencti-platform/opencti-graphql/src/python/requirements.txt
  opencti-worker/src/requirements.txt
  opencti-worker/src/worker.py
Labels: filigran team
