Repository OpenCTI-Platform/opencti, pull requests merged in 2024-12, with the labels that each got.

#9076 [frontend/backend] Add new markings to max_shareable_markings of groups with auto_new_marking (#7944)
  opencti-platform/opencti-front/src/private/components/common/form/MaxShareableMarkingsSelectField.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionMarkings.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionOverview.tsx
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/domain/markingDefinition.js
  opencti-platform/opencti-graphql/src/resolvers/group.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/marking-definition-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/group-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#9152 [backend] remove HTML parsing in title of RSS items (#9133)
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
Labels: filigran team

#9193 [backend] fix reindex error on deleting old objects (#9173)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
Labels: filigran team

#9088 [backend] optionnal STIX_EXT_OCTI_SCO
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
  opencti-platform/opencti-graphql/src/types/stix-common.d.ts
  opencti-platform/opencti-graphql/src/types/stix-sco.d.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/csv-parser-test.ts
Labels: filigran team

#9196 [frontend] Marking definitions data tables (9049)
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFileExport.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservablesExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/MarkingDefinitions.tsx
  opencti-platform/opencti-front/src/private/components/settings/MarkingDefinitionsQuery.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionMarkings.tsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionPopover.jsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionsLines.jsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
Labels: filigran team

#8930 [frontend] Refacto of data tables dimensions computation (#8808)
  opencti-platform/opencti-front/src/components/Breadcrumbs.tsx
  opencti-platform/opencti-front/src/components/ItemOperations.tsx
  opencti-platform/opencti-front/src/components/dashboard/WidgetContainer.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTablePagination.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableComponent.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeader.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeaders.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsList.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorAddObservables.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorObservablePopover.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorObservables.jsx
  opencti-platform/opencti-front/src/private/components/settings/MarkingDefinitions.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/techniques/AttackPatterns.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceDuplicationDialog.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Workspaces.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/public_dashboards/PublicDashboards.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsList.tsx
  opencti-platform/opencti-front/src/utils/domEvent.ts
  opencti-platform/opencti-front/src/utils/resizeObservers.ts
  opencti-platform/opencti-front/tests_e2e/model/MalwareAnalyses.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/navigation/navigation.spec.ts
Labels: filigran team

#9197 [frontend] Exclusion List frontend Create - Delete (#8941)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/private/components/settings/CustomizationMenu.tsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListValidator.ts
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListsLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListsLines.tsx
Labels: filigran team

#9188 [frontend] Display the available connectors if the ‘select all’ option is activated (#9126)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#6622 [graphql] Replace redlock@5.0.0-beta.2 w/ @sesamecare-oss/redlock@1.2.1
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/yarn.lock
Labels: technical improvement, community

#9255 [frontend] Fix 'Knowledge from container view' if no containers (#9247)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsContextualView.tsx
Labels: filigran team

#9212 [frontend] List of opinions have UI issues (#9186)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/opinions/OpinionPopover.tsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinions.tsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsList.tsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsRadar.tsx
Labels: filigran team

#9238 [frontend] Exclusion list page with datatable (#8941)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListsLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListsLines.tsx
Labels: filigran team

#9261 [backend] fix playbook attributPathMapping for SCOs (#9226)
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team

#9253 [backend] improve exclusion cache handling (binary search version) (#8941)
  opencti-platform/opencti-graphql/src/database/exclusionListCache.ts
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/utils/exclusionLists.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/exclusionLists-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/exclusionListCacheBuildManager-test.ts
Labels: filigran team

#9275 [frontend] Add a confirmation popup before deleting any files (#9225)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/DeleteDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
Labels: filigran team

#9132 [backend/frontend] Add assignee through automation playbook (#7728)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team, multi-repository

#9262 [frontend] Knowledge pages Details crash if vocabulary opinion_ov is empty (#9214)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsRadar.tsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsRadarDialog.tsx
Labels: filigran team

#9266 [frontend] improve Exclusion list creation form (#8941)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/files/CustomFileUploader.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListValidator.ts
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx
  opencti-platform/opencti-graphql/src/modules/exclusionList/exclusionList-domain.ts
Labels: filigran team

#9001 [frontend] Popover entities menu support for FAB_REPLACEMENT feature flag
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectEnrichment.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventDeletion.tsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventPopover.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualDeletion.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualPopover.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationDeletion.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationPopover.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorDeletion.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorPopover.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemDeletion.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemPopover.jsx
Labels: community

#9000 [frontend] Popover threats menu support for FAB_REPLACEMENT feature flag
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignDeletion.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignPopover.jsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetDeletion.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetPopover.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupDeletion.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupPopover.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualDeletion.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualPopover.tsx
Labels: community

#8999 [frontend] Popover arsenal menu support for FAB_REPLACEMENT feature flag
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelDeletion.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelPopover.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareDeletion.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwarePopover.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolDeletion.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolPopover.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityDeletion.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityPopover.jsx
Labels: community

#8876 [frontend] Popover techniques menu support for FAB_REPLACEMENT feature flag
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDeletion.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternPopover.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/Root.tsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionPopover.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CouseOfActionDeletion.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentDeletion.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentPopover.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceDeletion.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourcePopover.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeDeletion.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativePopover.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/Root.tsx
Labels: community

#9297 [backend] fix file markings that could be undefined when building OCTI extensions (#9301)
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
Labels: filigran team

#8873 [frontend] Popover event menu support for FAB_REPLACEMENT feature flag
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/Root.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentDeletion.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentPopover.tsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataDeletion.tsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataPopover.jsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/Root.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipEditionOverview.tsx
Labels: community

#9326 [tool] fix latest tag incorrectly points to a lower semver (#9325)
  .circleci/config.yml
Labels: filigran team

#9324 Limit renovate PRs to nights and weekend
  renovate.json
Labels: filigran team

#9267 [frontend] Implement word cloud public dashboard
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsWordCloud.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_relationships/PublicStixRelationshipsWordCloud.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/usePublicDashboardWidgets.tsx
Labels: filigran team

#9306 [backend] improve load file access restrictions (#9305)
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
Labels: filigran team

#9310 [backend] Add dedicated error for orga restricted entities + Feature flag (#3345)
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/config/errors.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/access-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-organization-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/domainQueryHelper.ts
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
Labels: filigran team

#9314 [frontend] exclusion lists status (#8941)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListsStatus.tsx
Labels: filigran team

#8789 [backend] Make pattern upsertable for rename platform sync
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
Labels: filigran team

#9333 [frontend] The default "Latest Reports" dashboard widget list recent reports, not the oldest one
  opencti-platform/opencti-front/src/private/components/Dashboard.jsx
Labels: filigran team

#9313 [frontend] Hide actions in Data tab according to capability (#8243)
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceFileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceStixCoreObjects.jsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/StixSightingRelationshipExternalReferencesLines.jsx
  opencti-platform/opencti-front/src/private/components/common/files/FileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileUploader.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FreeTextUploader.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileViewer.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFiles.tsx
Labels: filigran team

#9286 [backend] fix version of path-to-regexp for CVE-2024-52798
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/yarn.lock
Labels: security, filigran team

#9175 [frontend] Show all types of containers in overview correlation widget & CTA to correlation graph (#3227)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dataGrid/DataTableWithoutFragment.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingDetails.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentDetails.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiDetails.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftDetails.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/RelatedContainers.tsx
Labels: filigran team

#9348 [frontend] Fix missing Task name on reload in related entities (#9191)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixObjectOrStixRelationshipLine.jsx
Labels: filigran team

#9347 [backend] add exclusion list file size info (#8941)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/exclusionList/exclusionList-domain.ts
  opencti-platform/opencti-graphql/src/modules/exclusionList/exclusionList-resolver.ts
  opencti-platform/opencti-graphql/src/modules/exclusionList/exclusionList-types.ts
  opencti-platform/opencti-graphql/src/modules/exclusionList/exclusionList.graphql
  opencti-platform/opencti-graphql/src/modules/exclusionList/exclusionList.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/exclusionListResolver-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/exclusionListCacheBuildManager-test.ts
  opencti-platform/opencti-graphql/tests/data/exclusionLists/exclusionListDomainValues.txt
  opencti-platform/opencti-graphql/tests/data/exclusionLists/exclusionListIPValues.txt
Labels: filigran team

#9269 [backend/frontend] add limitations to analyses graph loaded objects (#9293)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainersGraph.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainersGraphBar.jsx
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/domain/container.js
Labels: filigran team

#9345 [backend] Fix missing hashes in stix pattern for promoted indicators (#7588)
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/stixCyberObservable-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixCyberObservable-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#9219 [backend/frontend] Management panel for restricted entities - chunk1 (#4961)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/private/components/data/Management.tsx
  opencti-platform/opencti-front/src/private/components/data/ManagementMenu.tsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#9203 [frontend] Filter correlation graphs on common SCOs and indicators by default (#3227)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/utils/Graph.js
Labels: filigran team

#9249 [backend] add validation mode to askJobImport (#6728)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/http/httpServer.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/parser/csv-bundler.ts
  opencti-platform/opencti-graphql/src/schema/attribute-definition.ts
Labels: filigran team

#9396 [backend] fix OpenBAS simulation if empty result (#9311)
  opencti-platform/opencti-graphql/src/database/xtm-obas.ts
Labels: filigran team

#9165 [frontend] move enroll playbook action in headers
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectEnrollPlaybook.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectHeader.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/Root.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/Root.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableHeader.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservablePopoverFABReplaced.jsx
Labels: filigran team

#9290 [frontend] Note & Opinion displayed as unknown in relathionship creation form (#9245)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
Labels: filigran team

#9327 [frontend] Update an Exclusion list (#8941)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#9349 Fix some react issues
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects_or_stix_relationships/StixCoreObjectOrCoreRelationshipLabelsView.js
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableMalwareAnalysesDummyList.tsx
Labels: filigran team

#9342 [backend] no longer send x_opencti_files with resolved markings to elastic in stixDomainObjectFileEdit (#9285)
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixDomainObject-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#9315 [frontend] improve draft UI pages (#6577)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
  opencti-platform/opencti-front/src/private/components/common/files/FileWork.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFilesAndHistory.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftEntities.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRelationships.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRoot.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftSightings.tsx
  opencti-platform/opencti-front/src/private/components/drafts/Root.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/utils.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
  opencti-platform/opencti-graphql/src/domain/work.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/draftWorkspace/draftWorkspace-domain.ts
  opencti-platform/opencti-graphql/src/modules/draftWorkspace/draftWorkspace-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/draftWorkspace/draftWorkspace.graphql
  opencti-platform/opencti-graphql/src/resolvers/connector.js
Labels: filigran team, multi-repository

#9229 [backend] improve waiting time for obas scenario generation with AI (#8585)
  opencti-platform/opencti-graphql/src/database/ai-llm.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-domain.ts
  opencti-platform/opencti-graphql/src/modules/xtm/xtm-domain.js
Labels: filigran team

#9458 [frontend] fix infinite loading in advanced search (#9452)
  opencti-platform/opencti-front/src/private/components/search/SearchContainerQuery.tsx
Labels: filigran team

#7517 FAB replacement for widgets on dashboards
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/DashboardWidgets.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboardDetails.pageModel.ts
Labels: community

#9462 [backend] Taxii sharing: fix updating authorized members
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionEdition.tsx
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
Labels: filigran team

#9479 [frontend] empty string displayed as '-' in entities lists (#9453)
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TasksLine.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedLine.jsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookLine.tsx
  opencti-platform/opencti-front/src/private/components/data/stream/StreamLine.jsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiLine.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventLine.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationLine.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/SettingsOrganizations.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserLine.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceLine.jsx
Labels: filigran team
