Repository OpenCTI-Platform/opencti, pull requests merged in 2024-07, with the labels that each got.

#7368 [frontend] E2E tests on Dashboard - chunk 2 (#6704)
  .drone.yml
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
  opencti-platform/opencti-front/tests_e2e/auth.setup.ts
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/enableReferences/addReportObservable.spec.ts
  opencti-platform/opencti-front/tests_e2e/general/navigation.spec.ts
  opencti-platform/opencti-front/tests_e2e/logout.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/AccessRestriction.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/DashboardWidgets.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboard.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboardDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/field/DateField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/loginForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/login.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/menu/leftBar.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/settings/entitySettings.spec.ts
  opencti-platform/opencti-front/tests_e2e/settings/parameters.spec.ts
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/tests/data/data-test-stix-e2e.json
Labels: filigran team

#7551 [frontend] restore observable singular colors (#7538)
  opencti-platform/opencti-front/src/utils/Colors.js
Labels: filigran team

#7518 [Frontend] Fix labels list (#6494)
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/Labels.jsx
  opencti-platform/opencti-front/src/private/components/settings/labels/LabelCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/labels/LabelPopover.jsx
  opencti-platform/opencti-front/src/private/components/settings/labels/LabelsLines.jsx
Labels: filigran team

#7564 [drone] remove python caching causing issue with playwright
  .drone.yml
Labels: filigran team

#7513 [frontend] Fix [Bulk search] Sorting on the columns doesn't work (#7215)
  opencti-platform/opencti-front/src/private/components/SearchBulk.jsx
Labels: filigran team

#7560 [Frontend] Fix on columns (#5405)
  opencti-platform/opencti-front/src/components/ItemOpenVocab.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Malwares.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareCard.tsx
  opencti-platform/opencti-front/src/private/components/threats/Campaigns.tsx
  opencti-platform/opencti-front/src/private/components/threats/IntrusionSets.tsx
  opencti-platform/opencti-front/src/private/components/threats/ThreatActorsGroup.tsx
  opencti-platform/opencti-front/src/private/components/threats/ThreatActorsIndividual.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignCard.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetCard.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupCard.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualCard.tsx
Labels: filigran team

#7492 [frontend] New filters in Threat>Knowledge>Attack Patterns (#7287)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatterns.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatterns.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChain.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChain.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainLines.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainLines.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainMatrix.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainMatrix.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternsMatrix.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternsMatrixColumns.jsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualKnowledge.tsx
Labels: filigran team

#7549 [frontend] score bulk update only authorized on entity types with score (#6870)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#7554 [backend/frontend] Issue with public dashboard name and case sensitivity (#7344)
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareForm.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareList.tsx
  opencti-platform/opencti-front/src/public/components/PublicDashboard.tsx
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-domain.ts
Labels: filigran team

#7567 [frontend] Creating indicator from observable works, but the UI freezes and needs to be reloaded (#7545)
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableIndicators.jsx
Labels: filigran team

#7242 [frontend] Bulk create relationship in container context (#7443)
  .drone.yml
  opencti-platform/opencti-dev/1 - Frontend start.run.xml
  opencti-platform/opencti-dev/2 - Frontend on test backend.run.xml
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/SearchBulk.jsx
  opencti-platform/opencti-front/src/private/components/common/bulk/BulkSelectRawLineData.tsx
  opencti-platform/opencti-front/src/private/components/common/bulk/EntityRelationshipCard.tsx
  opencti-platform/opencti-front/src/private/components/common/bulk/dialog/BulkRelationDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/bulk/dialog/BulkRelationDialogContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/bulk/useForceUpdate.ts
  opencti-platform/opencti-front/src/private/components/common/bulk/utils/querySearchEntityByText.ts
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectThreatKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/Root.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/Root.tsx
  opencti-platform/opencti-front/src/utils/Relation.test.ts
  opencti-platform/opencti-front/src/utils/Relation.ts
  opencti-platform/opencti-front/src/utils/hooks/useAuth.ts
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#7472 [frontend] simple stix object relationship fragment update (#6865)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/SimpleStixObjectOrStixRelationshipStixCoreRelationshipLine.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipOverview.jsx
  opencti-platform/opencti-front/src/private/components/data/relationships/RelationshipsStixCoreRelationshipLine.jsx
Labels: filigran team

#7556 [backend] improve file indexing metrics performance (#7530)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
Labels: filigran team

#7374 [frontend] Initial approach to dynamic update of Title and Language for pages
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/analyses/ExternalReferences.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Groupings.tsx
  opencti-platform/opencti-front/src/private/components/analyses/MalwareAnalyses.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Notes.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Reports.tsx
  opencti-platform/opencti-front/src/utils/hooks/useDynamicHeader.ts
Labels: community

#7563 [frontend/backend] source and target filters for sightings (#7182)
  opencti-platform/opencti-front/src/private/components/events/StixSightingRelationships.tsx
  opencti-platform/opencti-graphql/src/modules/attributes/stixSightingRelationship-registrationAttributes.ts
Labels: filigran team, filters & search

#7576 [backend/frontend] Update on data tables columns (#5405)
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeader.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/threats/IntrusionSets.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.graphql
Labels: filigran team

#7553 [frontend] Malware Analysis displayed as Unknown in relationship list widget (#6922)
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsList.jsx
Labels: filigran team

#7584 [frontend] Fix colors (#7580)
  opencti-platform/opencti-front/src/components/ThemeLight.ts
  opencti-platform/opencti-front/src/private/components/common/CodeBlock.tsx
Labels: filigran team

#6727 [frontend] fix handling of references enforcment in containers
  opencti-platform/opencti-front/src/components/list_lines/ListLinesContent.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionDetails.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/Note.jsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/Root.jsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/Opinion.jsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/Root.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncident.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfi.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRft.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/Feedback.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/CaseTaskOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/CaseTasksLine.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/CaseTasksLines.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/Task.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsLines.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerContent.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectPopover.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsMapping.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsMappingLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsMappingLines.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservableLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservablesLines.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjectLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjectsLines.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixObjectOrStixRelationshipLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixObjectsOrStixRelationships.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixObjectsOrStixRelationshipsLines.tsx
  opencti-platform/opencti-graphql/src/domain/stix.js
Labels: filigran team

#7579 [frontend] correlated cases display in cases overview (#7459)
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentDetails.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiDetails.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftDetails.tsx
Labels: filigran team

#7583 [frontend] In rules, panel is not correctly aligned (#7447)
  opencti-platform/opencti-front/src/private/components/settings/RulesList.jsx
Labels: filigran team

#7578 [frontend] Not possible to update a relation between a relation and an attack pattern (#7383)
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternKnowledge.jsx
Labels: filigran team

#7548 [frontend] add tooltips to marking chips (#7519)
  opencti-platform/opencti-front/src/components/ItemMarkings.jsx
Labels: filigran team

#7590 [frontend] allow to create Malware-Analyses and Tasks from knowledge tab (#7581)
  opencti-platform/opencti-front/src/private/components/cases/tasks/TaskCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.jsx
Labels: filigran team

#7604 [frontend] remove wrong label & tooltip in export dialog (7603)
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
Labels: filigran team

#7601 [frontend] Incorrect placeholder in Security / Organizations list (#7525)
  opencti-platform/opencti-front/src/private/components/settings/SettingsOrganizations.tsx
Labels: filigran team

#7595 [frontend] Fix toggle shift and Loader (#5405)
  opencti-platform/opencti-front/src/components/Loader.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
  opencti-platform/opencti-front/src/utils/hooks/useEntityToggle.ts
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#7596 [frontend] enable to share inferred relationships with organizations in ui (#7543)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipOverview.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipSharing.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipOverview.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipSharing.tsx
Labels: filigran team

#7550 [Frontend] Fix iddle logout (#7512)
  opencti-platform/opencti-front/src/private/components/TimeoutLock.tsx
Labels: filigran team

#7573 [frontend] Fix add threat actor individual in workbench (#7346)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
Labels: filigran team

#7613 [frontend] Fix Feed creation with authorized members (#7587)
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedEdition.jsx
Labels: filigran team

#7612 [ci] Fix e2e stix data and add extended error to CI (#7611)
  .drone.yml
  opencti-platform/opencti-graphql/tests/data/data-test-stix-e2e.json
Labels: filigran team

#7592 [backend] import from date not mandatory in Rss ingester (#7451)
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-rss.ts
Labels: filigran team

#7593 [frontend] External reference URL are not properly validated during creation (#7431)
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceEditionOverview.tsx
Labels: filigran team

#7610 [backend] Ability to add relationship references in CSV mapper(#7565)
  opencti-platform/opencti-graphql/src/database/stix-ref.ts
Labels: filigran team

#7639 [frontend] fix background task on unselected entities (#7638)
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#7641 Revert "[backend/frontend] modify EntityStixCoreRelationshipsEntitiesComponent to list entities through relations (#6867)"
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesViewLines.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/domain/attackPattern.ts
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/domain/courseOfAction.js
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/domain/individual.js
  opencti-platform/opencti-graphql/src/domain/intrusionSet.js
  opencti-platform/opencti-graphql/src/domain/region.js
  opencti-platform/opencti-graphql/src/domain/sector.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/domain/system.js
  opencti-platform/opencti-graphql/src/domain/threatActor.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/domain/vulnerability.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/case/case-template/case-template-domain.ts
  opencti-platform/opencti-graphql/src/modules/dataComponent/dataComponent-domain.ts
  opencti-platform/opencti-graphql/src/modules/dataSource/dataSource-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis-domain.ts
  opencti-platform/opencti-graphql/src/modules/narrative/narrative-domain.ts
  opencti-platform/opencti-graphql/src/modules/organization/organization-domain.ts
  opencti-platform/opencti-graphql/src/modules/task/task-domain.ts
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
Labels: filigran team

#7632 [backend] allow configuring Redis Sentinel options: failoverDetector/updateSentinels (#7631)
  opencti-platform/opencti-graphql/src/database/redis.ts
Labels: filigran team

#7628 [frontend] When editing a relationship from the overview of an entity, effect is not correct (#7542)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipEdition.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipEdition.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipPopover.jsx
Labels: filigran team

#7437 [frontend] Modifies autocomplete which causes form visual validation discrepancy
  opencti-platform/opencti-front/src/components/AutocompleteField.jsx
Labels: community

#7619 [backend] Next is not mandatory for taxii feed response (#7403)
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii.ts
Labels: filigran team

#7514 [backend] Test CSV bundler with Indicators with labels and kill chain phases
  opencti-platform/opencti-graphql/tests/01-unit/domain/csv-bundler-test.ts
  opencti-platform/opencti-graphql/tests/data/csv-bundler/external-references-constants.ts
  opencti-platform/opencti-graphql/tests/data/csv-bundler/kill-chains-constants.ts
  opencti-platform/opencti-graphql/tests/data/csv-bundler/labels-constants.ts
Labels: filigran team

#7667 [frontend] add missing translation to AI menu content tab(#7649)
  opencti-platform/opencti-front/lang/front/fr.json
Labels: filigran team

#7663 [frontend] Fix alignment of loader in knowledge graph(#7532)
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
Labels: filigran team

#7668 [frontend] The year cannot be typed in a date filter (#7276)
  opencti-platform/opencti-front/src/private/components/common/lists/FilterDate.tsx
Labels: filigran team

#7661 [frontend] fix sightings link in StixObjectsOrStixRelationships (#7537)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixObjectOrStixRelationshipLine.jsx
Labels: filigran team

#7618 [frontend] contains filter in Knowledge > Related containers view (#7445)
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsContextualView.tsx
Labels: filigran team, filters & search

#7575 [frontend] Placeholders not aligned in the roles list (#7526)
  opencti-platform/opencti-front/src/private/components/settings/Groups.jsx
  opencti-platform/opencti-front/src/private/components/settings/Roles.jsx
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplates.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleLine.jsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplateLineDummy.tsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplates.tsx
Labels: filigran team

#7677 [backend] Domain name values should be case insensitive (#7311)
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
Labels: filigran team

#7680 [frontend] Remove TAXII 2.0 and 1.0 options from the UI (#7676)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiEdition.jsx
Labels: filigran team

#7655 [frontend] Bulk creation for Channel entity (#4352)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/TextField.jsx
  opencti-platform/opencti-front/src/components/fields/BulkTextField/BulkTextField.tsx
  opencti-platform/opencti-front/src/components/fields/BulkTextField/BulkTextModal.tsx
  opencti-platform/opencti-front/src/components/fields/BulkTextField/BulkTextModalButton.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/files/CustomFileUploader.tsx
  opencti-platform/opencti-front/src/private/components/common/form/CreatedByField.jsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperTestDialog.tsx
  opencti-platform/opencti-front/src/utils/String.jsx
  opencti-platform/opencti-front/src/utils/hooks/useBulkCommit.tsx
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#7683 [frontend] Task dates are not correctly filled when navigating on a task (#7630)
  opencti-platform/opencti-front/src/private/components/cases/tasks/Task.tsx
Labels: filigran team

#7032 Replaced Edit Floating Action Buttons for Analyses
  opencti-platform/opencti-front/src/components/EditEntityControlledDial.tsx
  opencti-platform/opencti-front/src/private/components/analyses/ExternalReferences.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Groupings.tsx
  opencti-platform/opencti-front/src/private/components/analyses/MalwareAnalyses.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Notes.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Reports.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/AddExternalReferences.jsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReference.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceEdition.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceHeader.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Grouping.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingEdition.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysis.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEdition.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/Note.jsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/Note.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteEdition.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/Root.jsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/StixCoreObjectOrStixCoreRelationshipNotesCards.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Report.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Report.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportEdition.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/drawer/Drawer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectHeader.jsx
  opencti-platform/opencti-front/tests_e2e/model/field/DateField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/reportDetails.pageModel.ts
Labels: community, ui

#7687 [frontend] Incorrect loader / placeholder in knowledge lists (#7523)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesViewLines.tsx
Labels: filigran team

#7673 [frontend] Bottom toolbar content is not vertically centered (#7645)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#7689 [frontend] Fix contains field options in CSV mapper form (#6408)
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributeRefForm.tsx
  opencti-platform/opencti-front/src/utils/Relation.test.ts
  opencti-platform/opencti-front/src/utils/Relation.ts
Labels: filigran team

#7686 [frontend] When using a list in dashboard widgets that is not clickable, pointer / behavior not correct (#7540)
  opencti-platform/opencti-front/src/components/dashboard/WidgetDistributionList.tsx
Labels: filigran team

#7690 [frontend] Blank space on the right for some relationships overviews (#7597)
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/Root.jsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/Root.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/Root.tsx
Labels: filigran team

#7599 Add option in deployment to disable the user interface (#6600)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
Labels: filigran team

#7699 [frontend] Distribution list widget, number is not viewable (#7521)
  opencti-platform/opencti-front/src/components/dashboard/WidgetDistributionList.tsx
Labels: filigran team

#7675 [frontend] Progress bar displayed when submitting Channels creation in bulk (#4352)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ProgressBar.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/files/CustomFileUploader.tsx
  opencti-platform/opencti-front/src/utils/hooks/useBulkCommit.tsx
Labels: filigran team

#7710 [frontend/backend] Manage authentication for csv feed.
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvMapperTestDialog.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiEdition.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/ingestionAuthentificationUtils.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-common.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-types.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/ingestion-taxii-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-taxii-test.ts
Labels: filigran team

#7714 [frontend/backend] Refresh user cache when marking update (#7694)
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Security.tsx
  opencti-platform/opencti-front/src/utils/hooks/useAuth.ts
  opencti-platform/opencti-front/src/utils/hooks/useUserMetric.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/subscriptionWrapper.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
Labels: filigran team

#7646 [frontend/backend] Support of "KEV" field for vulnerability entity (#7390)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityDetails.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionDetails.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/types/store.d.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/attribute-test.js
Labels: filigran team, multi-repository

#7633 [frontend] Massive operations / checkboxes in Arsenal (Channels / Tools / Vulnerabilities) (#4234)
  opencti-platform/opencti-front/src/private/components/arsenal/Channels.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Tools.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Vulnerabilities.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelLine.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelsLines.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolLine.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolsLines.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilitiesLines.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityLine.tsx
Labels: filigran team

#7721 [frontend] Fix analyses graph view on entity displayed as author (#7718)
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualAnalysis.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationAnalysis.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemAnalysis.jsx
Labels: filigran team

#7730 [frontend] incident type chip UX in incident overview (#7709)
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentDetails.tsx
Labels: filigran team

#7722 [frontend] no pointer mouse on non editable filters (#7647)
  opencti-platform/opencti-front/src/components/filters/FilterValues.tsx
Labels: filigran team

#7734 [frontend] Fix useCopy (#7731)
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#7256 Replaced Creation Floating Action Buttons for Events
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/CreateEntityControlledDial.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/menus/CreateEntityControlledDial.tsx
  opencti-platform/opencti-front/src/private/components/events/Incidents.tsx
  opencti-platform/opencti-front/src/private/components/events/ObservedDatas.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/EntityStixSightingRelationships.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreation.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreationFromEntity.jsx
Labels: community

#7274 FAB Replacement on container knowledge, entities, and observables tabs
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsInGraph.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsInLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsLines.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservables.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservablesLines.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjects.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjectsLines.tsx
  opencti-platform/opencti-front/tests_e2e/model/EntitiesTab.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/containerAddObservables.pageModel.ts
Labels: community

#7258 Replaced Creation Floating Action Buttons for Threats
  opencti-platform/opencti-front/src/components/list_cards/ListCards.jsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/Campaigns.tsx
  opencti-platform/opencti-front/src/private/components/threats/IntrusionSets.tsx
  opencti-platform/opencti-front/src/private/components/threats/ThreatActorsGroup.tsx
  opencti-platform/opencti-front/src/private/components/threats/ThreatActorsIndividual.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualCreation.tsx
  opencti-platform/opencti-front/tests_e2e/model/intrusionSet.pageModel.ts
Labels: community

#7157 Replaced Creation Floating Action Buttons for Cases
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/cases/CaseIncidents.tsx
  opencti-platform/opencti-front/src/private/components/cases/CaseRfis.tsx
  opencti-platform/opencti-front/src/private/components/cases/CaseRfts.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentPopover.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/FeedbackCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/CaseTaskCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TaskCreation.tsx
  opencti-platform/opencti-front/tests_e2e/incidentResponse/assets/incidentResponse.test.md
  opencti-platform/opencti-front/tests_e2e/incidentResponse/assets/incidentResponse.test.pdf
  opencti-platform/opencti-front/tests_e2e/incidentResponse/incidentResponse.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/form/incidentResponseForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/incidentResponse.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/incidentResponseDetails.pageModel.ts
Labels: community

#7257 Replaced Creation Floating Action Buttons for Observations
  opencti-platform/opencti-front/src/private/components/observations/Artifacts.tsx
  opencti-platform/opencti-front/src/private/components/observations/Indicators.tsx
  opencti-platform/opencti-front/src/private/components/observations/Infrastructures.tsx
  opencti-platform/opencti-front/src/private/components/observations/StixCyberObservables.tsx
  opencti-platform/opencti-front/src/private/components/observations/artifacts/ArtifactCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
  opencti-platform/opencti-front/tests_e2e/model/Artifact.pageModel.ts
Labels: community

#7705 [backend] Add a graphql api to send stix bundle in the ingestion process (#7696)
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorWorks.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/manager/syncManager.js
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
  opencti-platform/opencti-graphql/src/resolvers/stix.js
Labels: filigran team

#7736 [frontend] When displaying an organization or an individual as "author", right padding is not correct in knowledge (#7717)
  opencti-platform/opencti-front/src/private/components/entities/organizations/Root.jsx
Labels: filigran team

#7745 [backend] fix export of vulnerabilities ordered by CVSS3 Severity (#7724)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#7735 [frontend/backend] Possibility to update workbench entity before validate it (#7703)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/String.jsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/file.js
Labels: filigran team, critical

#7750 [frontend] channel types display in channel lines (#7747)
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelLine.tsx
Labels: filigran team

#7711 [frontend] Apply bulk creation on other entities than Channels (#4352)
  opencti-platform/opencti-front/src/components/fields/BulkTextField/BulkTextModalButton.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualCreation.tsx
Labels: filigran team

#7664 [frontend] improve content mapping and suggested mapping views (#7566)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerContent.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerMappingContent.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsMapping.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsMappingHeader.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsSuggestedMapping.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsSuggestedMappingLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerSuggestedMappingContent.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentHeader.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentRoot.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectMappableContent.tsx
Labels: multi-repository

#7757 [frontend] Share button instead of Unshare in Bulk unshare pop-up (#7723)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#7707 [backend] Add log on intialization to better understand failures (#7038)
  opencti-platform/opencti-graphql/src/http/httpServer.js
  opencti-platform/opencti-graphql/src/initialization.js
Labels: filigran team

#7769 [frontend]fix list columns not aligned correctly(#7693)
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/SortConnectorsHeader.tsx
Labels: filigran team

#7772 [frontend] The “select all” function does not take into account the search (#7771)
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#7770 [frontend] Retain Search in UI for Indicator > Knowledge/Sightings (#7754)
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/EntityStixSightingRelationships.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEntities.jsx
Labels: filigran team

#7759 [frontend] Need to refresh to display new relations added to an indicator (#7727)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipPopover.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsRelationshipsView.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEntities.jsx
Labels: filigran team

#7760 [frontend] reset order after search in lists (#7726)
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
Labels: filigran team

#7776 [backend] For Software display the version in addition to the names i…
  opencti-platform/opencti-graphql/src/utils/format.js
Labels: filigran team

#7608 [frontend] Narratives Lines views refacto (#6741)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/components/ViewSwitchingButtons.tsx
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
  opencti-platform/opencti-front/src/private/components/common/FiligranIcon.tsx
  opencti-platform/opencti-front/src/private/components/techniques/Narratives.jsx
  opencti-platform/opencti-front/src/private/components/techniques/Narratives.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeLine.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeLine.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeWithSubnarrativeLine.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativesLines.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativesLines.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativesWithSubnarrativesLines.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/narrative/narrative.graphql
Labels: filigran team

#7782 [frontend] [RBAC - User] Information not updated after modification of Groups (#6929)
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/edition/UserEditionGroups.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/edition/UserEditionOverview.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#7732 [frontend] add useOverviewLayoutCustomization hook (#6724)
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/entity_setting/EntitySettingSettings.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividual.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useAuth.ts
  opencti-platform/opencti-front/src/utils/hooks/useOverviewLayoutCustomization.ts
  opencti-platform/opencti-front/src/utils/tests/overviewLayoutCustomization.test.tsx
  opencti-platform/opencti-front/src/utils/tests/test-render.tsx
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-domain.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-types.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting.graphql
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.ts
  opencti-platform/opencti-graphql/src/schema/module.ts
  opencti-platform/opencti-graphql/src/schema/overviewLayoutCustomization-register.ts
  opencti-platform/opencti-graphql/src/schema/schema-overviewLayoutCustomization.ts
Labels: filigran team

#7810 [CI] Add pip install requirement on client python (#7809)
  .drone.yml
Labels: filigran team

#7261 Replaced Creation Floating Action Buttons for Locations
  opencti-platform/opencti-front/src/private/components/locations/AdministrativeAreas.tsx
  opencti-platform/opencti-front/src/private/components/locations/Cities.tsx
  opencti-platform/opencti-front/src/private/components/locations/Countries.tsx
  opencti-platform/opencti-front/src/private/components/locations/Positions.tsx
  opencti-platform/opencti-front/src/private/components/locations/Regions.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionCreation.tsx
Labels: community

#7260 Replaced Creation Floating Action Buttons for Entities
  opencti-platform/opencti-front/src/private/components/entities/Events.tsx
  opencti-platform/opencti-front/src/private/components/entities/Individuals.tsx
  opencti-platform/opencti-front/src/private/components/entities/Organizations.tsx
  opencti-platform/opencti-front/src/private/components/entities/Sectors.jsx
  opencti-platform/opencti-front/src/private/components/entities/Systems.tsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/AddSubSector.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemCreation.tsx
Labels: community

#7259 Replaced Creation Floating Action Buttons for Techniques
  opencti-platform/opencti-front/src/private/components/techniques/AttackPatterns.tsx
  opencti-platform/opencti-front/src/private/components/techniques/CoursesOfAction.tsx
  opencti-platform/opencti-front/src/private/components/techniques/DataComponents.tsx
  opencti-platform/opencti-front/src/private/components/techniques/DataSources.tsx
  opencti-platform/opencti-front/src/private/components/techniques/Narratives.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AddCoursesOfAction.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AddDataComponents.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AddSubAttackPattern.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/AddDataSources.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/AddDataComponents.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/AddSubNarrative.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeCreation.tsx
Labels: community

#7739 Replaced Creation Floating Action Buttons for Arsenals
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Channels.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Malwares.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Tools.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Vulnerabilities.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsInGraph.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservables.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservablesLines.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjects.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjectsLines.tsx
  opencti-platform/opencti-front/src/private/components/threats/Campaigns.tsx
  opencti-platform/opencti-front/src/private/components/threats/IntrusionSets.tsx
  opencti-platform/opencti-front/src/private/components/threats/ThreatActorsGroup.tsx
  opencti-platform/opencti-front/src/private/components/threats/ThreatActorsIndividual.tsx
Labels: community

#7713 Replaced Edit Floating Action Buttons for Cases
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncident.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentEdition.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfi.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiEdition.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRft.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftEdition.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/Feedback.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/FeedbackEdition.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/FeedbackEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/Task.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TaskEdition.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TasksEditionContainer.tsx
  opencti-platform/opencti-front/tests_e2e/model/incidentResponseDetails.pageModel.ts
Labels: community

#7751 Replaced Edit Floating Action Buttons for Locations
  opencti-platform/opencti-front/src/components/Loader.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceEdition.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingEdition.jsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEdition.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteEdition.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportEdition.jsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeArea.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaEdition.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/City.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityEdition.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/Country.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryEdition.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/Position.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionEdition.jsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/locations/positions/Root.jsx
  opencti-platform/opencti-front/src/private/components/locations/regions/Region.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionEdition.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/Root.tsx
Labels: community

#7803 [frontend] add Korean translations (#7385)
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/components/AppIntlProvider.tsx
  opencti-platform/opencti-front/src/components/DateTimePickerField.jsx
  opencti-platform/opencti-front/src/components/TimePickerField.jsx
  opencti-platform/opencti-front/src/utils/BrowserLanguage.js
Labels: community

#7792 [frontend] entities default value for existence checks in workbench (#7351)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/utils/defaultRepresentatives.ts
Labels: filigran team

#7824 [backend] get all report's properties when using csv mapper (#6947)
  opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts
Labels: filigran team, multi-repository

#7841 [frontend] Fix miniMap (#7833)
  opencti-platform/opencti-front/src/private/components/common/location/LocationMiniMap.jsx
Labels: filigran team

#7840 [backend] fix query to cleanup old work in connector manager (#7838)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/manager/connectorManager.js
Labels: filigran team

#7826 [backend/frontend] improve group and users display performance (#7533)
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Root.tsx
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
Labels: filigran team

#7665 [backend] add new capability 'Bypass mandatory fields' (#3304)
  opencti-platform/opencti-front/src/private/components/data/IngestionMenu.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/migrations/1722320850954-bypass-mandatory-fields-capability.js
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-attributeUtils.ts
  opencti-platform/opencti-graphql/src/schema/schema-validator.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/data-initialization-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/schema-validator-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/role-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
Labels: filigran team

#7569 [backend] improve update element connections performance (#7568)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#7851 [backend] Remove attributes from CSV Mapper (#7849)
  opencti-platform/opencti-graphql/src/domain/attribute-utils.ts
Labels: filigran team

#7858 [frontend] Add translation in datatable headers
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/script/extract-i18n-keyword.js
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeader.tsx
Labels: filigran team

#7871 [backend] Alias filter with nil operator (#7864)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#7850 [backend] follow up fix for the work cleanup bug and tests coverage (#7838)
  opencti-platform/opencti-graphql/src/manager/connectorManager.js
  opencti-platform/opencti-graphql/src/types/work.d.ts
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/connectorManager-test.ts
Labels: filigran team

#7856 [frontend] Layout issue in group => edition => marking definition (#7847)
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionMarkings.tsx
Labels: filigran team

#7854 [frontend] Bad alignment in Data section of an overview (#7786)
  opencti-platform/opencti-front/src/private/components/common/files/FileExternalReferencesViewer.jsx
  opencti-platform/opencti-front/src/private/components/common/files/PictureManagementViewer.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileViewer.jsx
Labels: filigran team

#7812 [backend/frontend] better management of taxii feed pagination and UI improvements (#7755)(#7813).
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/src/private/components/data/IngestionTaxiis.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiLine.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiPopover.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-types.ts
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/ingestionManager-test.ts
Labels: filigran team

#7774 [frontend] Fix the display of name in widgets when entities are named 'Unknown' (#7692)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsTimeline.jsx
  opencti-platform/opencti-front/src/utils/defaultRepresentatives.ts
  opencti-platform/opencti-graphql/src/database/entity-representative.js
Labels: filigran team

#7872 [frontend] check marking definitions existence in Workbench (#7795)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionsLines.jsx
Labels: filigran team

#7681 Fix relation uses in knowledge (#7479)
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureKnowledge.tsx
Labels: filigran team

#7773 [frontend/backend] Add authorized members on caseIncident (#4538)
  opencti-platform/opencti-front/src/private/components/cases/CaseUtils.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncident.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/Feedback.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/form/AuthorizedMembersField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/FormAuthorizedMembers.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/authorizedMembers.ts
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident-domain.ts
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident.ts
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rft/case-rft.graphql
  opencti-platform/opencti-graphql/src/modules/case/case.graphql
  opencti-platform/opencti-graphql/src/modules/case/feedback/feedback-domain.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-resolver.ts
  opencti-platform/opencti-graphql/src/utils/authorizedMembers.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/user-delete-cleanup-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/case-incident-response-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/workspace-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#7873 [frontend] Incorrect icons in massive operation toolbar are removed in trash (#7870)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team
