Repository OpenCTI-Platform/opencti, pull requests merged in 2024-06, with the labels that each got.

#7133 [backend/frontend] API types ref mapping completed (#6281)
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationExpandForm.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Relation.ts
  opencti-platform/opencti-front/src/utils/hooks/useAuth.ts
  opencti-platform/opencti-front/src/utils/tests/filtersUtils.test.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/stix-ref.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#7089 [backend] Handle external refs files upload by import document (#7080)
  opencti-platform/opencti-graphql/src/database/file-storage-helper.ts
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/domain/externalReference.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/resolvers/externalReference.js
Labels: filigran team

#7145 [frontend] Clean up entity-type filter in Correlation Graphs
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeCorrelation.jsx
Labels: community

#7002 [e2e] Add env var in local e2e run to sandbox all infra (#6704)
  opencti-platform/opencti-graphql/package.json
Labels: filigran team

#7237 [frontend] sort images by order value in carousel (#7222)
  opencti-platform/opencti-front/src/utils/edition.js
Labels: filigran team

#7225 [backend] Fix reindexing fail error (#7031)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#7244 [Frontend] Fix broken security screen (#7243)
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
Labels: filigran team

#7248 [Frontend] Fix toolbar selection in knowledge -> indicators (#7245)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsEntitiesView.tsx
Labels: filigran team

#7224 [backend] Use index with inferred relation when sharing a report to an organization (#6990)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipOverview.jsx
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
Labels: filigran team

#7212 [backend] fix missing activ users count in telemetry exports (#7211)
  opencti-platform/opencti-graphql/src/telemetry/TelemetryMeterManager.ts
Labels: filigran team

#7254 [frontend] Fix file indexing accessing to external file (#6943)
  opencti-platform/opencti-front/src/private/components/search/SearchIndexedFileLine.tsx
  opencti-platform/opencti-front/src/utils/Entity.ts
Labels: filigran team

#7253 [frontend/backend] Fix work message when timeout (#7167)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx
  opencti-platform/opencti-graphql/src/domain/work.js
Labels: filigran team

#7252 [Backend] Reset settings cache when changing organization to user (#7099)
  opencti-platform/opencti-graphql/src/domain/user.js
Labels: filigran team

#7165 [frontend] Fix Add height / weight do not work (#7118)
  opencti-platform/opencti-front/src/private/components/common/form/HeightField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/WeightField.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualEditionBiographics.tsx
Labels: filigran team

#7098 [frontend/backend] Add available filter keys to stored filters for CSV feeds
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/FilterIconButton.tsx
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/TaskFilterValue.tsx
  opencti-platform/opencti-front/src/components/TasksFilterValueContainer.tsx
  opencti-platform/opencti-front/src/components/filters/DisplayFilterGroup.tsx
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/components/filters/FilterValues.tsx
  opencti-platform/opencti-front/src/components/list_lines/index.ts
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncident.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfi.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRft.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TasksEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjects.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainertKnowledgeTimeLineBar.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/Filters.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsRelationshipsView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectThreatKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedEdition.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/EntityStixSightingRelationships.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationsToolBar.tsx
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplateTasks.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetFilters.tsx
  opencti-platform/opencti-front/src/utils/dashboard.ts
  opencti-platform/opencti-front/src/utils/filters/filtersFromOldFormat.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersHelpers-types.ts
  opencti-platform/opencti-front/src/utils/filters/filtersManageStateUtil.ts
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/filters/useFiltersState.tsx
  opencti-platform/opencti-front/src/utils/hooks/useCopy.tsx
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorageModel.ts
  opencti-platform/opencti-front/src/utils/utils.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/filterKeysSchema-test.ts
  opencti-platform/opencti-graphql/tests/data/filter-keys-schema/indicatorFilterKeys.ts
Labels: filigran team

#7266 [backend] Add status filter for Sightings (#7220)
  opencti-platform/opencti-graphql/src/domain/filterKeysSchema.ts
Labels: filigran team

#7271 [frontend/backend] Remove sorting of Description (#7017)
  opencti-platform/opencti-front/src/private/components/data/Stream.jsx
  opencti-platform/opencti-front/src/private/components/data/Taxii.tsx
  opencti-platform/opencti-front/src/private/components/settings/Vocabularies.tsx
  opencti-platform/opencti-front/src/private/components/settings/VocabularyCategories.tsx
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplateTasks.tsx
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplates.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#7134 [frontend/backend] Ability to add indicator generated from the observables of a container in the container (#6171)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/data/drawers/PromoteDrawer.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicators.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicatorsLines.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableIndicatorPopover.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableIndicators.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/taskManager-promote-values/promoteValues.ts
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/taskManager-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#7107 [frontend/backend] Max shareable markings at the group level for exports and public dashboard (#7006)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
  opencti-platform/opencti-front/src/private/components/common/form/MarkingsSelectField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/ObjectMarkingField.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFileExport.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFilesAndHistory.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservablesExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/Policies.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionMarkings.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareList.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/domain/markingDefinition.js
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/migrations/1661470342448-tlpv2.js
  opencti-platform/opencti-graphql/src/migrations/1717060854132-max-shareable-marking-in-groups.js
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-domain.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-utils.ts
  opencti-platform/opencti-graphql/src/resolvers/group.js
  opencti-platform/opencti-graphql/src/resolvers/markingDefinition.js
  opencti-platform/opencti-graphql/src/resolvers/settings.js
  opencti-platform/opencti-graphql/src/schema/internalRelationship.ts
  opencti-platform/opencti-graphql/src/types/user.d.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/publicDashboard-utils-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/marking-definition-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/taxii-filtering-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/group-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/publicDashboard-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/settings-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#7186 [frontend/backend] show effective max confidence with creators (#6878)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/form/CreatorField.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionRss/IngestionRssCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionRss/IngestionRssEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/sync/SyncCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/sync/SyncEdition.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/user.js
Labels: filigran team

#7334 [frontend] all available filters in Knowledge relationships views (#7286)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsRelationshipsView.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionEdition.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetFilters.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team, filters

#7337 [frontend] Fix name resolution for distribution (#7336)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationshipsHorizontalBars.jsx
  opencti-platform/opencti-front/src/utils/Charts.js
Labels: filigran team

#7335 [frontend] fix filter icon button operators display in widgets (#7251)
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetFilters.tsx
Labels: filigran team, filters

#7343 [frontend] Fix Infrastructure breaking Investigation (#6801)
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.jsx
Labels: filigran team

#7339 [frontend] Ignore font-family while exporting report content (#6773)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContent.jsx
Labels: filigran team

#7331 [backend] handle labels during stix core relationship creation (#7194)
  opencti-platform/opencti-graphql/src/database/data-builder.js
Labels: filigran team

#7273 [backend] added limitQuerySize option on elFindByIds (#7250)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#7353 [backend/frontend] Rework model for Max shareable (#7348)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/form/MarkingsSelectField.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionMarkings.tsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionsLines.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/markings/markingsFiltering.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/domain/markingDefinition.js
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/migrations/1717060854132-max-shareable-marking-in-groups.js
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document.ts
  opencti-platform/opencti-graphql/src/resolvers/group.js
  opencti-platform/opencti-graphql/src/schema/internalRelationship.ts
  opencti-platform/opencti-graphql/src/utils/getExportContentMarkings.ts
  opencti-platform/opencti-graphql/src/utils/getExportFilter.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#7364 [frontend] Improve content marking usage (#7348)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFileExport.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFilesAndHistory.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservablesExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
Labels: filigran team

#7135 [frontend] e2e tests on dashbaords - chunk 2 (#6704)
  .drone.yml
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/form/AuthorizedMembersFieldListItem.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetPopover.jsx
  opencti-platform/opencti-front/tests_e2e/dashboard/createDashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/dashboard/updateDashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/dataForTesting/group.data.ts
  opencti-platform/opencti-front/tests_e2e/dataForTesting/init.data.ts
  opencti-platform/opencti-front/tests_e2e/dataForTesting/role.data.ts
  opencti-platform/opencti-front/tests_e2e/dataForTesting/user.data.ts
  opencti-platform/opencti-front/tests_e2e/filters/addFilter.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/DashboardWidgets.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboard.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboardDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/filters.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/dashboardForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/indicatorDetails.pageModel.tsx
  opencti-platform/opencti-front/tests_e2e/model/malwareDetails.pageModel.ts
  opencti-platform/opencti-graphql/package.json
Labels: filigran team

#7347 [frontend] Leverage external ref's files with GenAI functions at entity level (#6826)
  opencti-platform/opencti-front/src/private/components/common/form/FilesNativeField.tsx
Labels: filigran team

#7365 [frontend] disable redirection for delete notification lines (#7308)
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationLine.tsx
Labels: filigran team

#7150 [frontend/backend] add User and Group in context activity filters values (#7101)
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/lists/SearchScopeElement.jsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-graphql/src/domain/filterKeysSchema.ts
Labels: filigran team, filters

#6671 [backend] Merged entity should also have all files of the merged entity and at the right path in S3 (#6258)
  opencti-platform/opencti-graphql/src/database/file-storage-helper.ts
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/tests/02-integration/00-inject/loader-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/stixCyberObservable-domain-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/03-import/oasis-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/00-Raw/sync-raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/01-Live/sync-live-test.js
  opencti-platform/opencti-graphql/tests/04-sync/02-Direct/sync-direct-test.js
  opencti-platform/opencti-graphql/tests/04-sync/03-Restore/sync-restore-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
Labels: filigran team

#7171 [backend] improve default trigger notification (#7127)
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/modules/notifier/notifier-statics.ts
Labels: filigran team

#7136 [frontend] Add content mapping in content tab (#5651)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/Root.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/Root.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/Root.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/Root.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentHeader.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentRoot.tsx
  opencti-platform/opencti-front/src/private/components/entities/events/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/Root.jsx
  opencti-platform/opencti-front/src/private/components/events/incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/Root.jsx
  opencti-platform/opencti-front/src/private/components/locations/regions/Root.tsx
  opencti-platform/opencti-front/src/private/components/observations/artifacts/Root.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/Root.jsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/Root.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/Root.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/Root.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/Root.jsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/Root.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/Root.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/Root.jsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/Root.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/Root.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/Root.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/Root.tsx
  opencti-platform/opencti-front/src/utils/utils.ts
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#7235 [backend] prevent wrong type for empty pid (#6968)
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
Labels: filigran team

#7376 [frontend] add dialog box to confirm deletion in notifications (#7308)
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationLine.tsx
Labels: filigran team

#7249 [backend/frontend] modify EntityStixCoreRelationshipsEntitiesComponent to list entities through relations
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesViewLines.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/domain/attackPattern.ts
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/domain/courseOfAction.js
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/domain/individual.js
  opencti-platform/opencti-graphql/src/domain/intrusionSet.js
  opencti-platform/opencti-graphql/src/domain/region.js
  opencti-platform/opencti-graphql/src/domain/sector.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/domain/system.js
  opencti-platform/opencti-graphql/src/domain/threatActor.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/domain/vulnerability.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/case/case-template/case-template-domain.ts
  opencti-platform/opencti-graphql/src/modules/dataComponent/dataComponent-domain.ts
  opencti-platform/opencti-graphql/src/modules/dataSource/dataSource-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis-domain.ts
  opencti-platform/opencti-graphql/src/modules/narrative/narrative-domain.ts
  opencti-platform/opencti-graphql/src/modules/organization/organization-domain.ts
  opencti-platform/opencti-graphql/src/modules/task/task-domain.ts
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
Labels: filigran team

#7375 [frontend] add fields that can be made mandatory in Malware Analysis creation form
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysis.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionOverview.tsx
Labels: filigran team

#7192 [backend] add askAnalysis mutation to request file or fields analysis (#6803)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/repository.js
  opencti-platform/opencti-graphql/src/domain/connector.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/listener/UserActionListener.ts
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/manager/activityManager.ts
  opencti-platform/opencti-graphql/src/resolvers/connector.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
  opencti-platform/opencti-graphql/src/schema/general.js
Labels: filigran team, multi-repository

#7404 [frontend] Ask AI button in Ask AI dialog is semi-hidden (#6829)
  opencti-platform/opencti-front/src/utils/ai/ResponseDialog.tsx
Labels: filigran team

#7232 [backend/frontend] Purge a specific queue on reset state (#3781)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/config/test.json
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
  opencti-platform/opencti-graphql/src/domain/connector.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/connector.js
  opencti-platform/opencti-graphql/src/utils/http-client.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/rabbitmq-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/connector-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/group-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/role-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#7218 [frontend/backend] Share the result of inferrence rules in TAXII collections (#7069)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/Taxii.tsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionEdition.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/utils.js
  opencti-platform/opencti-graphql/src/domain/taxii.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
Labels: filigran team

#7149 [Frontend/Backend] split cpapabilites Data Sharing & Ingestion into 3 + manage CSV + Bypass ref + Connector Api (#7428)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/form/CommitMessage.tsx
  opencti-platform/opencti-front/src/private/components/data/Feed.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionMenu.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionRss.jsx
  opencti-platform/opencti-front/src/private/components/data/IngestionTaxiis.jsx
  opencti-platform/opencti-front/src/private/components/data/ProcessingMenu.jsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/data/Stream.jsx
  opencti-platform/opencti-front/src/private/components/data/Sync.jsx
  opencti-platform/opencti-front/src/private/components/data/Taxii.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedLine.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ManageImportConnectorMessage.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvLine.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionRss/IngestionRssLine.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiLine.jsx
  opencti-platform/opencti-front/src/private/components/data/stream/StreamLine.jsx
  opencti-platform/opencti-front/src/private/components/data/sync/SyncLine.jsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiLine.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useGranted.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/externalReference.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/migrations/1638115771654-reference_capability.js
  opencti-platform/opencti-graphql/src/migrations/1718809173008-update-data-sharing-ingestion-capabilities.js
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-rss.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii.graphql
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper.graphql
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/data-initialization-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-csv-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/role-test.js
Labels: filigran team

#7399 [backend] fix max shareable markings migration (#7392)
  opencti-platform/opencti-graphql/src/migrations/1713449762001-add-platform-data-sharing-max-markings.js
  opencti-platform/opencti-graphql/src/migrations/1717060854132-max-shareable-marking-in-groups.js
  opencti-platform/opencti-graphql/src/migrations/1718631740774-remove-platform-data-sharing-markings.js
Labels: do not merge, filigran team

#7417 [backend] Fix handling of platform_entity_files_ref config (#7406)
  opencti-platform/opencti-front/src/private/components/analyses/external_references/StixCoreObjectExternalReferencesLines.tsx
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/modules/attributes/stixMetaObject-registrationAttributes.ts
Labels: filigran team

#7429 [backend/frontend] fix date filters with same name in widgets (#7350)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/src/utils/tests/FilterUtilsConstants.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixCyberObservable-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/event/event.ts
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis.ts
Labels: filigran team, filters

#7424 Use number formatter for widgets (#7315)
  opencti-platform/opencti-front/src/components/dashboard/WidgetHorizontalBars.tsx
  opencti-platform/opencti-front/src/components/dashboard/WidgetRadar.tsx
  opencti-platform/opencti-front/src/components/dashboard/WidgetTree.tsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsRadar.tsx
  opencti-platform/opencti-front/src/utils/Charts.js
Labels: filigran team

#7355 [frontend] Fix enrichment of multiple observables when shift-selecting (#7269)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservablesLines.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjectsLines.tsx
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#7137 [backend] Trigger enrichment connectors with filters (#5371)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Connector.ts
  opencti-platform/opencti-front/src/utils/filters/useFiltersState.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/connector/connector.d.ts
  opencti-platform/opencti-graphql/src/database/cache.ts
  opencti-platform/opencti-graphql/src/domain/connector.js
  opencti-platform/opencti-graphql/src/domain/enrichment.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/cacheManager.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/resolvers/connector.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/enrichment-test.ts
  opencti-platform/opencti-graphql/tests/data/connectors/internal-connectors.json
Labels: filigran team

#7270 [backend] add analysisPush, analysisClear and stixCoreObjectAnalysis queries to add, clear and retrieve analysis result (#6803)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document.ts
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
Labels: filigran team, multi-repository

#7423 [frontend] Fix Bad FR translation encrypted archives (#7291)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
Labels: filigran team

#7361 CI improvement: client-python build once and fail fast on test-api (#7359)
  .drone.yml
  opencti-platform/opencti-graphql/package.json
Labels: filigran team

#7435 [backend] Bulk deleted external reference is not working when using a filter(#7210)
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/externalReference-test.js
Labels: filigran team

#7054 Split settings capabilities (#5550)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplateTasks.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useGranted.ts
  opencti-platform/opencti-front/tests_e2e/enableReferences/addReportObservable.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/form/roleForm.pageModel.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/migrations/1719208368256-settingscapabilities.js
  opencti-platform/opencti-graphql/src/migrations/1719208388531-notifier_authorized_authorities.js
  opencti-platform/opencti-graphql/src/modules/case/case-template/case-template.graphql
  opencti-platform/opencti-graphql/src/modules/notifier/notifier-domain.ts
  opencti-platform/opencti-graphql/src/modules/notifier/notifier.graphql
  opencti-platform/opencti-graphql/src/modules/organization/organization.graphql
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary.graphql
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/data-initialization-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/role-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#7457 [frontend] Fix knowledge entities list refresh (#7442)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesView.tsx
Labels: filigran team

#7425 [frontend] Be able to filter and sort on Narratives (#6741)
  opencti-platform/opencti-front/src/private/components/techniques/Narratives.jsx
  opencti-platform/opencti-front/src/private/components/techniques/Narratives.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeLine.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeLine.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativesLines.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativesLines.tsx
Labels: filigran team

#7455 [Frontend] Fix on search for user history (#7452)
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistory.tsx
Labels: filigran team

#7462 [backend] Fix issue Int cannot represent 32-bit signed integer
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
Labels: filigran team

#7470 [frontend] Revert "be able to filter and do massive operations on Narratives" (#6741)
  opencti-platform/opencti-front/src/private/components/techniques/Narratives.jsx
  opencti-platform/opencti-front/src/private/components/techniques/Narratives.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeLine.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeLine.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativesLines.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativesLines.tsx
Labels: filigran team

#6995 [backend] Test CSV bundler with Indicators with external references …
  opencti-platform/opencti-graphql/tests/01-unit/domain/csv-bundler-test.ts
  opencti-platform/opencti-graphql/tests/data/csv-bundler/external-references-constants.ts
Labels: filigran team

#7475 [Backend] Fix rabbitmq queue access for connector message (#7473)
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
Labels: filigran team

#7456 Split capabilities : Dashboard & investigations into 2 (#5550)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Root.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceLine.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Workspaces.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraphBar.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useGranted.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/migrations/1719321008908-dashboard-and-investigations-capabilities.js
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary.graphql
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
  opencti-platform/opencti-graphql/tests/02-integration/01-database/data-initialization-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/role-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#7468 [backend] Change log level for S3 download file errors (#7467)
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
Labels: filigran team

#7471 [backend] task manager updated for indicator score replace action (#7…
  opencti-platform/opencti-graphql/src/manager/taskManager.js
Labels: filigran team

#7275 [frontend/backend] In CSV Feed Ingester, take into account Default Marking definition options from CSV Mapper
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceFileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/StixCoreObjectExternalReferencesLines.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
  opencti-platform/opencti-front/src/private/components/common/form/CsvMapperField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/ObjectMarkingField.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFilesAndHistory.jsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvMapperTestDialog.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/csvMapperUtils.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-types.ts
  opencti-platform/opencti-graphql/src/parser/csv-bundler.ts
  opencti-platform/opencti-graphql/src/parser/csv-mapper.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/csv-mapper-test.js
Labels: filigran team

#7491 merge result marking updated
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#7480 [Frontend/backend] split SETTINGS capacity (#5550)
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsDistributionList.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsDonut.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsHorizontalBars.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsList.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsMultiAreaChart.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsMultiHeatMap.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsMultiLineChart.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsMultiVerticalBars.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsNumber.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsPolarArea.tsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsRadar.jsx
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsTreeMap.jsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EEChip.tsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EETooltip.tsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EnterpriseEditionButton.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/search/SearchIndexedFiles.tsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganization.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-front/src/private/components/settings/support/SupportPackages.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useGranted.ts
  opencti-platform/opencti-front/tests_e2e/enableReferences/addReportObservable.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/form/roleForm.pageModel.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/case/case-template/case-template.graphql
  opencti-platform/opencti-graphql/src/modules/decayRule/decayRule.graphql
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting.graphql
  opencti-platform/opencti-graphql/src/modules/managerConfiguration/managerConfiguration.graphql
  opencti-platform/opencti-graphql/src/modules/notification/notification.graphql
  opencti-platform/opencti-graphql/src/modules/notifier/notifier.graphql
  opencti-platform/opencti-graphql/src/modules/support/support.graphql
  opencti-platform/opencti-graphql/src/modules/task/task-template/task-template.graphql
Labels: filigran team

#7373 [backend/frontend] Marking label and entity type chip color adjustment (#6609)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/EnrichedTooltip.jsx
  opencti-platform/opencti-front/src/components/ItemEntityType.tsx
  opencti-platform/opencti-front/src/components/ItemMarkings.jsx
  opencti-platform/opencti-front/src/components/ItemPatternType.tsx
  opencti-platform/opencti-front/src/components/ThemeLight.ts
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingLine.jsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteLine.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsMappingLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservableLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjectLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixObjectOrStixRelationshipLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainerLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixRelationshipLastContainers.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects_or_stix_relationships/StixCoreObjectOrCoreRelationshipLabelsView.js
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationshipLineAll.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationshipLineFrom.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationshipLineTo.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/SimpleStixObjectOrStixRelationshipStixCoreRelationshipLine.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityStixCoreObjectsLine.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesViewLine.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectNestedEntitiesLines.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntityLine.tsx
  opencti-platform/opencti-front/src/private/components/data/entities/EntitiesStixDomainObjectLine.jsx
  opencti-platform/opencti-front/src/private/components/data/relationships/RelationshipsStixCoreRelationshipLine.jsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentLine.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEntityLine.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorObservables.jsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureLine.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEntitiesLines.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableLine.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableNestedEntitiesLines.jsx
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjectsLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Colors.js
  opencti-platform/opencti-front/src/utils/graph/EntityDetails.tsx
  opencti-platform/opencti-front/src/utils/graph/RelationshipDetails.tsx
  opencti-platform/opencti-front/src/utils/graph/StixMetaObjectDetails.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/resolvers/user.js
Labels: community

#7496 [Frontend] Improve date checking (#7494)
  opencti-platform/opencti-front/src/components/i18n.jsx
Labels: filigran team

#7408 [backend] set x_opencti_workflow_id upsert attribute (#7114)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixCoreRelationship-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixSightingRelationship-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/dataComponent/dataComponent.graphql
  opencti-platform/opencti-graphql/src/modules/dataSource/dataSource.graphql
  opencti-platform/opencti-graphql/src/modules/narrative/narrative.graphql
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team, multi-repository

#7497 In CSV Feed Ingester, take into account Default Marking definition options from CSV Mapper - improvements
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvMapperTestDialog.tsx
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
Labels: filigran team

#7360 [frontend/backend] Ability to add indicator generated from the observables of a container in the container (#6171)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/data/drawers/PromoteDrawer.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicators.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicatorsLines.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableIndicatorPopover.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableIndicators.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/modules/index.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/stixCyberObservable/deprecated/stixCyberObservable-deprecated.ts
  opencti-platform/opencti-graphql/src/modules/stixCyberObservable/deprecated/stixCyberObservable-domain.js
  opencti-platform/opencti-graphql/src/modules/stixCyberObservable/deprecated/stixCyberObservable-resolver.js
  opencti-platform/opencti-graphql/src/modules/stixCyberObservable/deprecated/stixCyberObservable.graphql
  opencti-platform/opencti-graphql/src/modules/stixCyberObservable/stixCyberObservable.ts
  opencti-platform/opencti-graphql/src/resolvers/stixCyberObservable.js
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/taskManager-promote-values/promoteValues.ts
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/taskManager-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/06-deprecated/stixCyberObservable-domain-test.ts
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/vitest.config.dev.ts
Labels: filigran team, multi-repository

#7490 [backend] on Artifact creation pass mime_type to upload (#7486)(#7434)
  opencti-platform/opencti-graphql/src/database/file-storage-helper.ts
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/migrations/1652125339035-files_database.js
  opencti-platform/opencti-graphql/src/migrations/1661196127751-artifacts.js
  opencti-platform/opencti-graphql/src/migrations/1701354091189-files-registration.js
  opencti-platform/opencti-graphql/src/modules/internal/document/document-types.ts
  opencti-platform/opencti-graphql/src/modules/support/support-domain.ts
  opencti-platform/opencti-graphql/src/resolvers/externalReference.js
  opencti-platform/opencti-graphql/src/resolvers/file.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/stixCyberObservable-domain-test.ts
Labels: filigran team

#7493 [backend] Migration to remove representative in DB (#7484)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/migrations/1719419160224-remove-representative.js
Labels: filigran team

#7474 [Backend] Add relations ref to observable representations (#7419)
  opencti-platform/opencti-graphql/src/modules/relationsRef/stixCyberObservable-registrationRef.ts
Labels: filigran team

#7227 [backend] Ensure the valid_until date on Indicators is set to a greater value than valid_from when empty (#6836)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEditionOverview.jsx
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-converter.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-utils.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/indicator-test.ts
Labels: do not merge, filigran team

#7422 [frontend] fix themeLight for the csv mapper test result(#6887)
  opencti-platform/opencti-front/src/components/ThemeLight.ts
Labels: filigran team

#7501 [frontend] UI improvements to content mapping suggestion page (#5651)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/fields/RichTextField.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerContent.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsSuggestedMapping.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerSuggestedMappingContent.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentBar.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectMappableContent.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useDebounceCallback.ts
  opencti-platform/opencti-front/tests_e2e/model/StixDomainObjectContentTab.pageModel.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team
