Repository OpenCTI-Platform/opencti, pull requests merged in 2024-01, with the labels that each got.

#5268 [backend/frontend] Add Sighted in/at in the relationships representation list (#4846)
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperForm.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationExpandForm.tsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-front/src/utils/hooks/useAuth.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/csv-parser-test.js
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/simple-sighting-test/Threat-Actor-Group_SIGHTING_org.csv
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/simple-sighting-test/csv-mapper-mock-simple-sighting.ts
Labels: filigran team

#5349 [backend] Extract default value representative (#5348)
  opencti-platform/opencti-graphql/src/domain/attribute.ts
Labels: filigran team

#5251 [backend] Implement SSO based on HTTP headers of the reverse proxy (#5107)
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/config/providers.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
Labels: filigran team

#5344 [backend] Add option to reduce memory footprint. Default to 500
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#5310 [frontend] fix Distribution of Opinions if no opinion exist (#5306)
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsRadarDialog.tsx
  opencti-platform/opencti-front/src/utils/Localization.js
Labels: filigran team

#5359 [backend] fix workflow filter migration (#5035)
  opencti-platform/opencti-graphql/src/migrations/1701859469408-rename-workflow-filter-key.js
Labels: filigran team

#5342 [frontend] Error trying to export relationships in Data > Relationships page (#5333)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipsExportCreation.jsx
Labels: filigran team

#5357 [frontend] Fix bulk search no longer works (#5341)
  opencti-platform/opencti-front/src/private/components/SearchBulk.jsx
Labels: filigran team

#4305 In TA and Sectors, inferred relationships located-at should not have a button "unlink / delete" (#issue/4220)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js
  opencti-platform/opencti-front/src/private/components/entities/sectors/AddSubSectorsLines.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorSubSectors.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/AddLocationsThreatActorGroupLines.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupLocation.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/AddLocationsThreatActorIndividualLines.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualLocation.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#5345 [backend] Introduce /health endpoint
  opencti-platform/opencti-front/builder/dev/dev.js
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/http/httpServer.js
Labels: filigran team

#5375 [frontend] copy required static files to make PDF lib work
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/vite.config.mts
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#5391 [frontend] refactor of Indicator overview code (#2859)
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorDetails.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorDetails.tsx
Labels: filigran team

#5401 [frontend] The choice of the type of observable to create is not reset after a "cancel" (#issue/5367)
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
Labels: filigran team

#5327 [backend] Fix playbook create observables based on indicators (#5313)
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team

#5418 [frontend] Remove edit button in an Analyse screen
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwarePopover.jsx
Labels: filigran team

#5410 [backend/frontend] Improve search to include a default score criteria (#5397)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContainer.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#5334 [frontend] sort exports by export date in lists (#5316)
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
Labels: filigran team

#5343 [backend/worker] Logs improvement for python execution and worker
  opencti-platform/opencti-graphql/src/python/pythonBridge.js
  opencti-platform/opencti-graphql/src/python/runtime/stix2_create_pattern.py
  opencti-platform/opencti-graphql/src/python/runtime/utils/runtime_utils.py
  opencti-platform/opencti-graphql/src/utils/syntax.js
  opencti-platform/opencti-graphql/tests/01-unit/python/pythonBridge-test.js
  opencti-worker/src/worker.py
Labels: filigran team

#5438 [backend] fix elementId in widget dynamic filters (#5339)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team, filters

#5419 [frontend] Fix bad design in Knowledge of an Individual/Organization/System + overview of Narrative
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/techniques/Narratives.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/Narrative.jsx
Labels: filigran team

#5442 [backend] Fix widget dashboard if Dynamic from/to result is empty (#5339)
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsMultiAreaChart.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsMultiHeatMap.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsRadar.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsTimeline.jsx
  opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/domain/stixRelationship.js
Labels: filigran team, filters

#5450 [frontend] filters reset in trigger creation form (#5449)
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerLiveCreation.tsx
Labels: filigran team

#5326 [frontend] i18n, extract keyword and solution to auto-translate
  opencti-platform/opencti-front/lang/de.json
  opencti-platform/opencti-front/lang/en.json
  opencti-platform/opencti-front/lang/es.json
  opencti-platform/opencti-front/lang/fr.json
  opencti-platform/opencti-front/lang/ja.json
  opencti-platform/opencti-front/lang/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/script/extract-i18n-keyword.js
  opencti-platform/opencti-front/src/components/AppIntlProvider.tsx
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#5461 [frontend] Fix filter in report knowledge timeline view
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team, filters

#5465 [backend] fix granted organizations not taking in account during add observables (#5451)
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
Labels: filigran team

#5469 [frontend/backend] fix ordering in Activity (#5464)
  opencti-platform/opencti-front/src/private/components/settings/activity/audit/Audit.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#5470 [frontend] relationship type filter value display (#5468)
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team

#5471 [frontend] remove timeline button in Grouping Knowledge (#5458)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
Labels: filigran team

#5486 [frontend] Fix of rectangle selection
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
Labels: filigran team

#5497 [frontend] fix widget clear filters
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetFilters.tsx
  opencti-platform/opencti-front/src/utils/filters/useFiltersState.tsx
Labels: filigran team

#5496 [frontend] fix default value displayed in case of windows registry key (#5387)
  opencti-platform/opencti-front/src/utils/Graph.js
Labels: filigran team

#5489 [backend] fix interval hour in timeseries graphql queries (#5488)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/utils.js
Labels: community

#5472 [frontend] fix link resolution for file export (#5466)
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectHeader.jsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/Root.tsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/Root.jsx
  opencti-platform/opencti-front/src/utils/Entity.ts
Labels: filigran team

#5455 [frontend] truncate merged observable name (#5440)
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#5517 [frontend] fix filters reset in widgets (#5507)
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
Labels: filigran team, filters

#5524 [frontend] fix output ports handling in Playbooks (#5437)
  opencti-platform/opencti-front/src/private/components/data/playbooks/hooks/useManipulateComponents.js
  opencti-platform/opencti-front/src/private/components/data/playbooks/types/nodes/NodeWorkflow.tsx
Labels: filigran team

#5566 [frontend] Impossible to use some fields when in a graph (#5563)
  opencti-platform/opencti-front/src/utils/graph/RelationSelection.tsx
Labels: filigran team

#5567 [backend] Get only platform metadata to prevent mm-source-mtime ingestion failure (#5561)
  opencti-platform/opencti-graphql/src/database/file-storage.js
Labels: filigran team

#5565 [backend] Migration rename-workflow-filter-key fail when widgets have empty dataSelection (#5560)
  opencti-platform/opencti-graphql/src/migrations/1701859469408-rename-workflow-filter-key.js
Labels: filigran team

#5589 [frontend] Refactor IndicatorDetails
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorDetails.tsx
Labels: filigran team

#5583 [frontend] Padding in PlaybookAddComponents(#5514)
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
Labels: filigran team

#5588 [frontend] Fix the number of results in Audits List (#5578)
  opencti-platform/opencti-front/src/private/components/common/audits/AuditsList.jsx
Labels: filigran team

#5544 [frontend] Tables in description fields cannot move outside the description (#5447)
  opencti-platform/opencti-front/src/components/ExpandableMarkdown.tsx
Labels: filigran team

#5590 [frontend] Add indicator pattern filter
  opencti-platform/opencti-front/lang/de.json
  opencti-platform/opencti-front/lang/en.json
  opencti-platform/opencti-front/lang/es.json
  opencti-platform/opencti-front/lang/fr.json
  opencti-platform/opencti-front/lang/ja.json
  opencti-platform/opencti-front/lang/zh.json
  opencti-platform/opencti-front/src/private/components/observations/Indicators.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team

#5604 [frontend] Fix padding in PlaybookAddComponents(#5514)
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
Labels: filigran team

#5606 [frontend] Vulnerability CVSS3-Score not mandatory (#5586)
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionDetails.jsx
Labels: filigran team

#5317 [backend/frontend] Implementation of the core feature for indicators decay (#2859)
  opencti-platform/opencti-front/lang/de.json
  opencti-platform/opencti-front/lang/en.json
  opencti-platform/opencti-front/lang/es.json
  opencti-platform/opencti-front/lang/fr.json
  opencti-platform/opencti-front/lang/ja.json
  opencti-platform/opencti-front/lang/zh.json
  opencti-platform/opencti-front/src/private/components/observations/indicators/DecayDialog.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorDetails.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/back.js
  opencti-platform/opencti-graphql/src/boot.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/clusterManager.ts
  opencti-platform/opencti-graphql/src/manager/index.ts
  opencti-platform/opencti-graphql/src/manager/indicatorDecayManager.ts
  opencti-platform/opencti-graphql/src/manager/managerModule.ts
  opencti-platform/opencti-graphql/src/modules/indicator/decay-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-resolver.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-types.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-utils.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.graphql
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/decay-test.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/indicator-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
  opencti-platform/opencti-graphql/tests/utils/globalSetup.js
Labels: filigran team

#5609 [frontend] Unauthorized errors should redirect to Login page (#5608)
  opencti-platform/opencti-front/src/private/components/Error.jsx
Labels: filigran team

#5617 [frontend] Unable to create an export of Attack patterns (#5612)
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatterns.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectVictimologySectors.jsx
Labels: filigran team

#5587 [backend] Fix the file change right
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/listener/UserActionListener.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-types.ts
  opencti-platform/opencti-graphql/src/resolvers/externalReference.js
  opencti-platform/opencti-graphql/src/resolvers/file.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/resolvers/stixDomainObject.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
Labels: filigran team

#5630 [backend] Text filters is breaking with double quote ()
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team, filters

#5627 [frontend] empty fields with dash in CourseOfAction and Report overview (#5624)
  opencti-platform/opencti-front/src/components/ExpandableMarkdown.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionDetails.jsx
Labels: filigran team

#5634 [frontend] 'Notes' header different from other entity types header (#5628)
  opencti-platform/opencti-front/src/private/components/nav/TopMenuAnalyses.tsx
Labels: filigran team

#5631 [backend] Fix file indexing infinite retry on parsing error (#5629)
  opencti-platform/opencti-graphql/src/database/file-search.js
Labels: filigran team

#5546 [drone] Builds number reduction
  .drone.yml
Labels: filigran team

#5638 [frontend] add 'main observable type' filter for Triggers (#5637)
  opencti-platform/opencti-front/lang/en.json
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerLiveCreation.tsx
Labels: filigran team, filters

#5645 [frontend] add 'main observable type' filter in Widgets (#5637)
  opencti-platform/opencti-front/lang/de.json
  opencti-platform/opencti-front/lang/en.json
  opencti-platform/opencti-front/lang/es.json
  opencti-platform/opencti-front/lang/fr.json
  opencti-platform/opencti-front/lang/ja.json
  opencti-platform/opencti-front/lang/zh.json
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetFilters.tsx
Labels: filigran team, filters

#5663 [frontend] fix error at Digest creation (#5661)
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerDigestCreation.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/alerting/AlertDigestCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/alerting/AlertDigestEdition.tsx
Labels: filigran team

#5596 [backend] add effective_confidence_level computed field to users (#4304)
  opencti-platform/opencti-front/lang/de.json
  opencti-platform/opencti-front/lang/en.json
  opencti-platform/opencti-front/lang/es.json
  opencti-platform/opencti-front/lang/fr.json
  opencti-platform/opencti-front/lang/ja.json
  opencti-platform/opencti-front/lang/zh.json
  opencti-platform/opencti-front/src/private/Index.tsx
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/form/OptionalConfidenceLevelField.tsx
  opencti-platform/opencti-front/src/private/components/settings/Users.jsx
  opencti-platform/opencti-front/src/private/components/settings/platform_alerts/GroupWithNullConfidenceLevelAlertContent.tsx
  opencti-platform/opencti-front/src/private/components/settings/platform_alerts/PlatformCriticalAlertDialog.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/GroupUsers.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/GroupUsersLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/SettingsOrganizationUsers.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserConfidenceLevel.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEditionGroups.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserLine.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/settings.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/user-test.ts
Labels: filigran team

#5683 [frontend] exclude User entity/refs from elements to expand in Investigation graphs (#5662)
  opencti-platform/opencti-front/lang/en.json
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationExpandForm.tsx
  opencti-platform/opencti-front/src/utils/Entity.ts
Labels: filigran team

#5687 [frontend] Fix button for expanding description display in Overviews
  opencti-platform/opencti-front/src/components/ExpandableMarkdown.tsx
Labels: filigran team

#5700 [backend/frontend] Improve search complexity and error handling (#5678)
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
  opencti-platform/opencti-front/src/private/components/Error.jsx
  opencti-platform/opencti-graphql/src/config/errors.js
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/schema/schema-attributes.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/search-test.js
Labels: filigran team

#5640 [backend] load creators from cache to improve perf
  opencti-platform/opencti-graphql/src/domain/user.js
Labels: filigran team

#5705 [frontend] Fix report types display if null (#5624)
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
Labels: filigran team

#5703 [backend] Improve files migration to be more iterative to have more control / information about the process (#5702)
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/migrations/1701354091189-files-registration.js
Labels: filigran team

#5642 [backend] Improvement to limit engine memory usage
  opencti-platform/opencti-front/src/private/components/analyses/external_references/AddExternalReferencesLines.jsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceFileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/StixCoreObjectExternalReferencesLines.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/StixCoreRelationshipExternalReferencesLines.jsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/StixSightingRelationshipExternalReferencesLines.jsx
  opencti-platform/opencti-front/src/private/components/common/files/FileExportViewer.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileExternalReferencesViewer.jsx
  opencti-platform/opencti-front/src/private/components/common/files/FileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileViewer.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectContent.jsx
  opencti-platform/opencti-front/src/private/components/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableDetails.jsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/file-search.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/domain/stixRelationship.js
  opencti-platform/opencti-graphql/src/domain/taxii.js
  opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
  opencti-platform/opencti-graphql/src/migrations/1608243352290-deduplicate_observable_url.js
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-rss-resolver.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
  opencti-platform/opencti-graphql/src/modules/organization/organization-resolver.ts
  opencti-platform/opencti-graphql/src/resolvers/externalReference.js
  opencti-platform/opencti-graphql/src/resolvers/group.js
  opencti-platform/opencti-graphql/src/resolvers/internalRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/resolvers/stixDomainObject.js
  opencti-platform/opencti-graphql/src/resolvers/stixRefRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixSightingRelationship.js
  opencti-platform/opencti-graphql/src/utils/clean-relations.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
Labels: filigran team

#5685 [frontend] Improve UX filter for 'no-label' and fix date value
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersLocalStorageUtil.ts
  opencti-platform/opencti-front/src/utils/filters/filtersManageStateUtil.ts
  opencti-platform/opencti-front/src/utils/filters/useFiltersState.tsx
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
Labels: filigran team, filters

#5436 [backend/frontend] Add user and group confidence level (#4304)
  opencti-platform/opencti-front/lang/de.json
  opencti-platform/opencti-front/lang/en.json
  opencti-platform/opencti-front/lang/es.json
  opencti-platform/opencti-front/lang/fr.json
  opencti-platform/opencti-front/lang/ja.json
  opencti-platform/opencti-front/lang/zh.json
  opencti-platform/opencti-front/src/components/InputSliderField.tsx
  opencti-platform/opencti-front/src/components/list_lines/ListLinesContent.jsx
  opencti-platform/opencti-front/src/private/Index.tsx
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/Error.jsx
  opencti-platform/opencti-front/src/private/components/common/form/ConfidenceField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/GroupField.jsx
  opencti-platform/opencti-front/src/private/components/common/form/GroupField.tsx
  opencti-platform/opencti-front/src/private/components/settings/Groups.jsx
  opencti-platform/opencti-front/src/private/components/settings/Users.jsx
  opencti-platform/opencti-front/src/private/components/settings/activity/configuration/Configuration.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupConfidenceLevel.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupLine.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupsLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganizationEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/platform_alerts/GroupWithNullConfidenceLevelAlertContent.tsx
  opencti-platform/opencti-front/src/private/components/settings/platform_alerts/PlatformCriticalAlertDialog.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/GroupUsers.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/GroupUsersLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/SettingsOrganizationUsers.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserConfidenceLevel.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserConfidenceLevelField.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEditionGroups.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserLine.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UsersLines.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/grant.js
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/resolvers/settings.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/user-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/group-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/notificationManager-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#5746 [backend] remove unecessary console.log in domino patch (#5679)
  opencti-platform/opencti-graphql/patch/domino-2.1.6.patch
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#5747 [backend] avoid user deletion raising exception when authorized_member is missing (#5580)
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/user-delete-cleanup-test.ts
Labels: filigran team

#5752 [backend/frontend] Migration to yarn v4
  opencti-platform/opencti-front/.yarn/releases/yarn-3.7.0.cjs
  opencti-platform/opencti-front/.yarn/releases/yarn-4.1.0.cjs
  opencti-platform/opencti-front/.yarnrc.yml
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/.yarn/releases/yarn-3.7.0.cjs
  opencti-platform/opencti-graphql/.yarn/releases/yarn-4.1.0.cjs
  opencti-platform/opencti-graphql/.yarnrc.yml
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#5755 [backend] Invalid TAXII header when collection is exposed to public
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/http/httpTaxii.js
Labels: filigran team

#5684 [frontend/backend] CSV Mapper default values for marking definitions (#4932)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFilesAndHistory.jsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperDefaultMarking.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributeOptions.tsx
  opencti-platform/opencti-front/src/private/components/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/entity_setting/EntitySettingAttributeEdition.tsx
  opencti-platform/opencti-front/src/utils/hooks/useDefaultValues.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-utils.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-types.ts
  opencti-platform/opencti-graphql/src/parser/csv-bundler.ts
  opencti-platform/opencti-graphql/src/parser/csv-mapper.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/csv-mapper-test.js
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/data-markings.csv
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/mapper-area-marking.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/representation-marking.ts
Labels: filigran team
