Repository OpenCTI-Platform/opencti, pull requests merged in 2024-09, with the labels that each got.

#8052 [frontend/backend] authorized members bypass organization sharing for case IR (#4538)
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncident.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/Feedback.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/form/FormAuthorizedMembers.tsx
  opencti-platform/opencti-front/src/private/components/common/form/FormAuthorizedMembersDialog.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceManageAccessDialog.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/public_dashboards/PublicDashboardLineActions.tsx
  opencti-platform/opencti-front/src/utils/authorizedMembers.ts
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/src/utils/authorizedMembers.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/case-incident-response-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/organization-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixDomainObject-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#8198 [backend/frontend] remove feature flag CAPABILITY_BYPASSFIELDS (#3304)
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#8201 [front] Remove Public dashboard list FF (#6509)
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/public_dashboards/PublicDashboards.tsx
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#7823 Replaced Edit Floating Action Buttons for Entities
  opencti-platform/opencti-front/src/private/components/entities/events/Event.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/Event.tsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventEdition.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/Individual.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/Individual.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualEdition.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/Organization.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/Organization.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationEdition.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/Sector.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/Sector.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorEdition.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/System.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/System.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemEdition.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemEditionContainer.jsx
Labels: community

#7743 Replaced Edit Floating Action Buttons for Arsenals
  opencti-platform/opencti-front/src/private/components/arsenal/channels/Channel.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelEdition.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/Malware.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareEdition.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareEdition.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/Tool.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEdition.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/Vulnerability.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEdition.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionContainer.jsx
Labels: community

#8184 [frontend/backend] Global files filtering and ordering (#3016)
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/TaskFilterValue.tsx
  opencti-platform/opencti-front/src/components/TasksFilterValueContainer.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportFilesContent.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportWorkbenchesContent.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionCreation.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document.ts
  opencti-platform/opencti-graphql/src/modules/relationsRef/internalObject-registrationRef.ts
Labels: filigran team

#7744 Replaced Edit Floating Action Buttons for Techniques
  opencti-platform/opencti-front/src/private/components/techniques/DataComponents.tsx
  opencti-platform/opencti-front/src/private/components/techniques/DataSources.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPattern.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternEdition.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/Root.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfAction.tsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionEdition.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/Root.jsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponent.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentEdition.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/Root.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSource.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceEdition.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/Root.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/Narrative.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeEdition.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/Root.jsx
Labels: community

#8200 [frontend/backend] make unit mandatory for Retention Rules
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/retentionRule.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/migrations/1724916130587-add-unit-to-retention-rules.js
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/retentionManager-test.ts
Labels: filigran team

#8189 [frontend] remove feature flag for Files retention rules (#7482)
  opencti-platform/opencti-front/src/private/components/settings/Retention.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionLine.tsx
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#8236 [frontend] allow to disable line selection on datatables
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTableWithoutFragment.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableComponent.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeaders.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
Labels: filigran team

#7740 Replaced Edit Floating Action Buttons for Events
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteEdition.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/Incident.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentEdition.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedData.tsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataEdition.jsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/Root.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationship.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipOverview.jsx
Labels: community

#7741 Replaced Edit Floating Action Buttons for Observations
  opencti-platform/opencti-front/src/private/components/observations/artifacts/Root.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/Indicator.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/Indicator.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEdition.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/Root.jsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/Infrastructure.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureEdition.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/Root.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/Root.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservable.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservable.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEdition.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEdition.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableHeader.jsx
Labels: community

#7742 Replaced Edit Floating Action Buttons for Threats
  opencti-platform/opencti-front/src/private/components/threats/campaigns/Campaign.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignEdition.jsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSet.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetEdition.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroup.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupEdition.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividual.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualEdition.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualEditionContainer.tsx
Labels: community

#8169 [backend] Use of dedicated RabbitMQ queues for integrated feeders/ingestors (#7704)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/IngestionMenu.tsx
  opencti-platform/opencti-front/src/private/components/data/Sync.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
  opencti-platform/opencti-graphql/src/connector/importCsv/importCsv.ts
  opencti-platform/opencti-graphql/src/database/repository.js
  opencti-platform/opencti-graphql/src/domain/connector.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/migrations/1725468530567-ingestion-connectors.js
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-rss-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-domain.ts
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/ingestionManager-test.ts
Labels: filigran team

#8256 [backend] improve platform security (#8255)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/graphql/schema.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#8254 [backend] Fix meEdit & authorized authorities update
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/utils/access.ts
Labels: filigran team

#8262 [backend] Add telemetry counter and gauge for graphql queries and mutations
  opencti-platform/opencti-graphql/src/config/tracing.ts
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/graphql/telemetryPlugin.js
  opencti-platform/opencti-graphql/src/manager/activityManager.ts
  opencti-platform/opencti-graphql/src/manager/historyManager.ts
  opencti-platform/opencti-graphql/src/migrations/1701354091189-files-registration.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
Labels: feature

#8261 [github] Adding a workflow to auto set labels
  .github/workflows/auto-set-labels.yml
Labels: filigran team

#7924 [backend] Improve Attack Pattern knowledge matrix view performance (#6662)
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternsMatrix.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternsMatrixColumns.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/database/utils.js
  opencti-platform/opencti-graphql/src/domain/attackPattern.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/attackPattern.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/attackPattern-test.js
Labels: filigran team

#8257 [frontend] label display for user without Knowledge update capability (#8193)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects_or_stix_relationships/StixCoreObjectOrCoreRelationshipLabelsView.js
Labels: filigran team

#8247 [backend] take retention unit into account in retention rule check (#8246)
  opencti-platform/opencti-graphql/src/domain/retentionRule.js
Labels: filigran team

#8276 [backend] Connector default role should bypass mandatory attributes by default (#8275)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/migrations/1725699277745-connector-bypass-mandatory-field.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
Labels: filigran team

#8286 Implement new graphql armor protection
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/graphql/graphql.js
Labels: filigran team

#8266 [frontend] New import screens under FF (#3016)
  opencti-platform/opencti-front/src/private/components/data/ImportMenu.tsx
  opencti-platform/opencti-front/src/private/components/data/import/Import.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/data/import/Root.jsx
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#8267 [backend] retention rules on files with status complete or timeout (#7482)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/retentionRule.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/retentionManager.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/retentionManager-test.ts
Labels: filigran team

#8232 [frontend] Improve Simulation buttons CSS (#8231)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
Labels: filigran team

#8290 [frontend] Fix infinite scroll (#7906)
  opencti-platform/opencti-front/src/components/list_lines/ListLinesContent.jsx
Labels: filigran team

#8292 [frontend] Fix shift select for some data tables (#7906)
  opencti-platform/opencti-front/src/private/components/analyses/ExternalReferences.tsx
  opencti-platform/opencti-front/src/private/components/cases/Tasks.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportFilesContent.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportWorkbenchesContent.tsx
  opencti-platform/opencti-front/src/private/components/techniques/AttackPatterns.tsx
  opencti-platform/opencti-front/src/private/components/techniques/CoursesOfAction.tsx
  opencti-platform/opencti-front/src/private/components/techniques/DataComponents.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/public_dashboards/PublicDashboards.tsx
Labels: filigran team

#8233 [backend] Force LDAP bindCredentials to be a String and add docker image for dev (#7995)
  opencti-platform/opencti-dev/docker-compose.yml
  opencti-platform/opencti-graphql/src/config/providers.js
Labels: filigran team

#7860 [frontend/e2e] Navigation on groupings and malware analyses (#7378)
  opencti-platform/opencti-front/playwright.config.ts
  opencti-platform/opencti-front/src/private/components/analyses/MalwareAnalyses.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Grouping.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisDetails.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx
  opencti-platform/opencti-front/tests_e2e/enableReferences/addReportObservable.spec.ts
  opencti-platform/opencti-front/tests_e2e/groupings/createGrouping.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/MalwareAnalyses.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/MalwareAnalysesDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/SDOTabs.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/StixCoreObjectHistoryTab.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/grouping.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/groupingDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/report.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/reportDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/navigation/navigation.spec.ts
  opencti-platform/opencti-front/tests_e2e/report/report.spec.ts
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/tests/data/data-test-stix-e2e.json
Labels: filigran team

#8229 [frontend] Remove feature flag for bulk entities (#4352)
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualCreation.tsx
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#8308 [backend/frontend] Finalize Overview layout customization (#6724)
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncident.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/CaseTasksLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/SubType.tsx
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-domain.ts
Labels: filigran team

#8315 [backend] Add feature flag for schema attributes (#4538)
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident.ts
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.ts
  opencti-platform/opencti-graphql/src/modules/case/case-rft/case-rft.ts
  opencti-platform/opencti-graphql/src/modules/grouping/grouping.ts
  opencti-platform/opencti-graphql/src/schema/attribute-definition.ts
  opencti-platform/opencti-graphql/src/schema/schema-attributes.ts
Labels: filigran team

#8302 [frontend] Bulk entity creation of SDO/SCO with Copy/Pasting (#4352)
  opencti-platform/opencti-front/src/private/components/common/bulk/BulkSelectRawLineData.tsx
  opencti-platform/opencti-front/src/private/components/common/bulk/EntityRelationshipCard.tsx
  opencti-platform/opencti-front/src/private/components/common/bulk/dialog/BulkRelationDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/bulk/dialog/BulkRelationDialogContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.jsx
  opencti-platform/opencti-front/src/utils/Relation.ts
  opencti-platform/opencti-front/src/utils/hooks/useEntityToggle.ts
Labels: filigran team

#8328 [frontend] Bulk entity creation of SDO/SCO with Copy/Pasting (#4352)
  opencti-platform/opencti-front/src/private/components/common/bulk/BulkSelectRawLineData.tsx
  opencti-platform/opencti-front/src/private/components/common/bulk/dialog/BulkRelationDialog.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
Labels: filigran team

#8326 [frontend] remove Connectors list in Data>Import
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
Labels: filigran team

#8342 [backend/frontend] Remove feature flag for bulk create relations (#4352)(#7500)
  .drone.yml
  opencti-platform/opencti-front/src/private/components/common/bulk/dialog/BulkRelationDialogContainer.tsx
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#8320 [backend/frontend] Implement dedicated queues for playbooks and synchronizers
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionRss.jsx
  opencti-platform/opencti-front/src/private/components/data/IngestionTaxiis.jsx
  opencti-platform/opencti-front/src/private/components/data/Playbooks.tsx
  opencti-platform/opencti-front/src/private/components/data/Sync.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvLine.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionRss/IngestionRssLine.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiLine.jsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookHeader.tsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookLine.tsx
  opencti-platform/opencti-front/src/private/components/data/sync/SyncLine.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
  opencti-platform/opencti-graphql/src/database/repository.js
  opencti-platform/opencti-graphql/src/database/utils.js
  opencti-platform/opencti-graphql/src/domain/connector.ts
  opencti-platform/opencti-graphql/src/domain/rabbitmqMetrics.js
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/manager/syncManager.js
  opencti-platform/opencti-graphql/src/migrations/1726085514007-sync-playbook-queues.js
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-domain.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook.graphql
  opencti-platform/opencti-graphql/src/resolvers/connector.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/rabbitmq-test.js
  opencti-worker/src/worker.py
Labels: filigran team

#8351 [frontend] Fixes on DataTable (#7906)
  opencti-platform/opencti-front/src/components/Breadcrumbs.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTableFilters.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTablePagination.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableComponent.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeader.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
  opencti-platform/opencti-front/src/components/nestedMenu/NestedMenuButton.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects_or_stix_relationships/StixCoreObjectOrCoreRelationshipLabelsView.js
  opencti-platform/opencti-front/src/static/css/index.css
Labels: filigran team

#8338 [frontend] Authorized members default value should not contain me user (#8311)
  opencti-platform/opencti-front/src/private/components/common/form/AuthorizedMembersField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/FormAuthorizedMembers.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/entity_setting/EntitySettingAttributeEdition.tsx
Labels: filigran team

#8364 [frontend] no pointer if Item Marking/Status is not clickable (#8314)
  opencti-platform/opencti-front/src/components/ItemMarkings.jsx
  opencti-platform/opencti-front/src/components/ItemStatus.jsx
Labels: filigran team

#8363 [backend] add verification on file download (#8361)
  opencti-platform/opencti-graphql/src/database/file-storage-helper.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
  opencti-platform/opencti-graphql/src/modules/support/support-domain.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/document-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-helper-test.ts
Labels: filigran team

#8367 [frontend] Multiple fixes on DataTables (#7906)
  opencti-platform/opencti-front/src/components/dashboard/WidgetListCoreObjects.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTableWithoutFragment.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableComponent.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeaders.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsList.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/observations/Indicators.tsx
  opencti-platform/opencti-front/src/private/components/threats/Campaigns.tsx
  opencti-platform/opencti-front/src/private/components/threats/IntrusionSets.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsList.tsx
Labels: filigran team

#8218 [backend] filtering-utils fixes and tests
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/filtering-utils-test.ts
Labels: filigran team

#8370 Revert "Update dependency @xmldom/xmldom to v0.9.2"
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#8369 [frontend] adjust data tables styling
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableComponent.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Malwares.tsx
  opencti-platform/opencti-front/src/private/components/threats/Campaigns.tsx
  opencti-platform/opencti-front/src/private/components/threats/IntrusionSets.tsx
  opencti-platform/opencti-front/src/private/components/threats/ThreatActorsGroup.tsx
  opencti-platform/opencti-front/src/private/components/threats/ThreatActorsIndividual.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/public_dashboards/PublicDashboards.tsx
Labels: filigran team

#8381 [frontend] Bulk entity creation of SDO/SCO with Copy/Pasting (#4352)
  opencti-platform/opencti-front/src/private/components/common/bulk/dialog/BulkRelationDialog.tsx
Labels: filigran team

#8301 [backend/frontend] improve organization sharing (#4538)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/case-incident-response-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#8402 [frontend] Fix ctrl+click on DataTable (#8394)
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
Labels: filigran team

#8404 [backend] Fix orga sharing tests (#4538)
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
Labels: filigran team

#8406 [frontend] Fix number of elements (#8396)
  opencti-platform/opencti-front/src/utils/Number.js
Labels: filigran team

#8382 [frontend] Fix search in Containers Correlation view (#8162)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeCorrelation.jsx
Labels: filigran team

#8309 [frontend] Observables exports list of containers should be independant (#8241)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservables.tsx
Labels: filigran team

#7966 [backend] display created field for csv mapper (#7226)
  opencti-platform/opencti-graphql/src/domain/attribute-utils.ts
Labels: filigran team

#8377 [front] add missing breadcrumb in multiple entites (#8274)
  opencti-platform/opencti-front/src/private/components/analyses/external_references/Root.jsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/Root.tsx
Labels: filigran team

#8412 [platform] Prepare new branch pre-release
  .circleci/config.yml
  .drone.yml
Labels: filigran team

#8420 [front] add missing breadcrumbs in customization+ fix(#8274)
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayRule.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/Root.tsx
Labels: filigran team

#8423 [frontend] added missing exportContext in global search (#8421)
  opencti-platform/opencti-front/src/private/components/Search.tsx
Labels: filigran team

#8331 Update body-parser to 1.20.3 for transitive dependencies
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/yarn.lock
Labels: dependencies, filigran team

#8408 [frontend] deleted 2nd scrollbar from dashboard-details-page (#8401)
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Root.jsx
Labels: community

#8386 [frontend] center loader (#8280)
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
Labels: filigran team

#8400 [frontend] Bulk edition of status regression fix (#8393)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#8431 [frontend] Fix attack patterns matrix columns sorting by score (#8424)
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternsMatrixColumns.jsx
Labels: filigran team

#8417 [backend] add 'unauthorized' in event scope filter values (#8414)
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
Labels: filigran team

#8437 [frontend] enhancing the settings panels layout (#8240)
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessages.tsx
Labels: filigran team

#8450 [frontend] enable latitude and longitude removing from UI (#8440)
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionEditionOverview.jsx
Labels: filigran team

#8285 [frontend] fixed workbench creation pop-up in case of error (#8265)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileCreator.tsx
Labels: community

#8517 [frontend] Need to refresh the page to see the new attack patterns added in Techniques / Attack Patterns (#8516)
  opencti-platform/opencti-front/src/private/components/techniques/AttackPatterns.tsx
Labels: filigran team

#8466 [backend] Add remote logout_remote value to openId options (#7766)
  opencti-platform/opencti-graphql/src/config/providers.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
Labels: filigran team

#8397 [dev] Add a profile to run opensearch locally
  opencti-platform/opencti-dev/docker-compose.yml
Labels: filigran team

#8528 [backend] Fix the detection and usage of dedicated headers
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/graphql/graphql.js
  opencti-platform/opencti-graphql/src/http/httpServer.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/identifier-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/administrativeArea-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#7478 [Backend] Add OpenID Connect SSO support for Microsoft ADFS to get user claims from the id_token
  opencti-platform/opencti-graphql/src/config/providers.js
Labels: community

#8436 [backend] store enum filters values in constants
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/domain/vulnerability.js
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/manager/retentionManager.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification.ts
Labels: technical improvement, filigran team
