Repository OpenCTI-Platform/opencti, pull requests merged in 2024-05, with the labels that each got.

#6831 [backend] restrict knowledge widgets to core relationships, sightings and 'contains' (#6777)
  opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/domain/stixRelationship.js
Labels: filigran team

#6869 [backend] fix input.objectMarking being optional at entity creation (#5823)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#6789 [backend/frontend] Restore elements from trash + mass operations on the Trash (#1536)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/Index.tsx
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/trash/Trash.tsx
  opencti-platform/opencti-front/src/private/components/trash/all/DeleteOperationLine.tsx
  opencti-platform/opencti-front/src/private/components/trash/all/DeleteOperationPopover.tsx
  opencti-platform/opencti-front/src/private/components/trash/all/DeleteOperationsLines.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/defaultRepresentatives.ts
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-builder.js
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/domain/stixObjectOrStixRelationship.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/garbageCollectionManager.ts
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-domain.ts
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-resolvers.ts
  opencti-platform/opencti-graphql/src/schema/attribute-definition.ts
  opencti-platform/opencti-graphql/src/schema/internalObject.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/deleteOperation-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/sync-utils.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#6868 [backend] missing opts definition file_marking for file upload(#5548)
  opencti-platform/opencti-graphql/src/database/file-storage-helper.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-helper-test.ts
  opencti-platform/opencti-graphql/tests/data/file-storage-helper-test.txt
Labels: filigran team

#6682 [frontend/backend] e2e tests for CRUD operations on Reports (#5648)
  .drone.yml
  opencti-platform/opencti-front/.eslintrc.js
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/playwright.config.ts
  opencti-platform/opencti-front/src/components/AutocompleteField.jsx
  opencti-platform/opencti-front/src/components/fields/SelectField.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportPopover.jsx
  opencti-platform/opencti-front/src/private/components/common/form/ConfidenceField.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects_or_stix_relationships/StixCoreObjectOrCoreRelationshipLabelsView.js
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectOverview.jsx
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/tests_e2e/Export file/exportReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/dashboard/createDashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/dashboard/updateDashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/enableReferences/addReportObservable.spec.ts
  opencti-platform/opencti-front/tests_e2e/groupings/createGrouping.spec.ts
  opencti-platform/opencti-front/tests_e2e/intrusionSet/createIntrusionSetRelationship.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/field/AutocompleteField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/field/ConfidenceField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/field/DateField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/field/FileField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/field/SelectField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/field/TextField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/authorForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/dashboardForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/externalReferenceForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/formExport.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/groupForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/groupingForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/intrusionSetForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/labelForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/reportForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/roleForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/stixCoreRelationshipCreationFromEntityForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/userForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/menu/leftBar.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/report.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/reportDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/reportForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/toolbar.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/report/assets/report.test.html
  opencti-platform/opencti-front/tests_e2e/report/assets/report.test.md
  opencti-platform/opencti-front/tests_e2e/report/assets/report.test.pdf
  opencti-platform/opencti-front/tests_e2e/report/assets/report.test.txt
  opencti-platform/opencti-front/tests_e2e/report/createReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/report/deleteReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/report/report.spec.ts
  opencti-platform/opencti-front/tests_e2e/report/updateReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/settings/entitySettings.spec.ts
  opencti-platform/opencti-front/tests_e2e/utils.ts
  opencti-platform/opencti-graphql/builder/dev/dev.js
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/script/script-insert-dataset.js
  opencti-platform/opencti-graphql/script/script-wait-for-api.js
Labels: filigran team

#6872 [backend] fix relationship_type check in distributions queries (#6777)
  opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/domain/stixRelationship.js
Labels: filigran team

#6875 [backend/frontend] Add restore message in history event (#1536)
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-graphql/src/database/generate-message.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-domain.ts
  opencti-platform/opencti-graphql/src/types/event.d.ts
Labels: filigran team

#6841 [backend] Add missing auth directives
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/authDirective.js
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard.graphql
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/backgroundTask-test.ts
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
Labels: filigran team

#6857 [frontend] improve confidence overrides edition + bugfixes (#6837)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/form/ConfidenceField.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserConfidenceLevel.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/edition/UserConfidenceOverrideField.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/edition/UserEditionConfidence.tsx
  opencti-platform/opencti-front/src/utils/hooks/useConfidenceLevel.ts
  opencti-platform/opencti-front/src/utils/hooks/useDefaultValues.ts
  opencti-platform/opencti-graphql/src/utils/confidence-level.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/confidence-level-test.ts
Labels: filigran team

#6815 [backend] Marking definition filters to export files (#5797)
  opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFileExport.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFilesAndHistory.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservablesExportCreation.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/domain/stixObjectOrStixRelationship.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
  opencti-platform/opencti-graphql/src/resolvers/stixObjectOrStixRelationship.js
  opencti-platform/opencti-graphql/src/utils/getExportContentMarkings.ts
  opencti-platform/opencti-graphql/src/utils/getExportFilter.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
Labels: filigran team

#6885 [backend] Introduce credential provider for elasticsearch / redis and minio (#6883)
  opencti-platform/opencti-graphql/src/config/credentials.ts
  opencti-platform/opencti-graphql/src/config/providers.js
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/initialization.js
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/index-file-test.js
  opencti-platform/opencti-graphql/tests/utils/globalSetup.ts
  opencti-platform/opencti-graphql/tests/utils/testSetup.js
Labels: filigran team

#6634 [frontend/backend] Implement Telemetry in OpenCTI (#6292)
  opencti-platform/opencti-dev/docker-compose.yml
  opencti-platform/opencti-dev/otlp-config.yaml
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/src/private/components/settings/support/SupportPackageLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/support/SupportPackageLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/support/SupportPackages.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/platformModulesHelper.ts
  opencti-platform/opencti-graphql/.gitignore
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/test.json
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/back.js
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/config/tracing.ts
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
  opencti-platform/opencti-graphql/src/database/session.js
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/index.ts
  opencti-platform/opencti-graphql/src/manager/managerModule.ts
  opencti-platform/opencti-graphql/src/manager/telemetryManager.ts
  opencti-platform/opencti-graphql/src/modules/support/support-domain.ts
  opencti-platform/opencti-graphql/src/modules/support/support.graphql
  opencti-platform/opencti-graphql/src/telemetry/BatchExportingMetricReader.ts
  opencti-platform/opencti-graphql/src/telemetry/MetricFileExporter.ts
  opencti-platform/opencti-graphql/src/telemetry/TelemetryMeterManager.ts
  opencti-platform/opencti-graphql/src/types/connector.d.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/support-unit-test.ts
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#6860 [backend] Upgrade of notification model + Auto trigger on assignee/pa…
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/form/NotifierField.tsx
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/stixObjectOrStixRelationship.ts
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/activityManager.ts
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/migrations/1714734961164-default-notifiers-user.js
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-types.ts
  opencti-platform/opencti-graphql/src/modules/notifier/notifier-domain.ts
  opencti-platform/opencti-graphql/src/modules/notifier/notifier-statics.ts
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/src/types/user.d.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-stix/stix-testers.ts
Labels: filigran team

#6889 [backend] Fix no country flag next to IP addresses in observables list (#6888)
  opencti-platform/opencti-graphql/src/domain/region.js
Labels: filigran team

#6900 [github] update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: filigran team

#6902 [backend] build relationship type fixed (#6894)
  opencti-platform/opencti-graphql/src/domain/stixRelationship.js
Labels: filigran team

#6895 [backend] Support-Package: use Redis instead of elastic for Node status. (#5548)
  opencti-platform/opencti-front/src/private/components/settings/support/SupportPackageLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/listener/supportPackageListener.ts
  opencti-platform/opencti-graphql/src/modules/support/support-converter.ts
  opencti-platform/opencti-graphql/src/modules/support/support-domain.ts
  opencti-platform/opencti-graphql/src/modules/support/support-types.ts
  opencti-platform/opencti-graphql/src/modules/support/support.graphql
  opencti-platform/opencti-graphql/src/modules/support/support.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/support-unit-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/support-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/06-listener/supportPackageListener-test.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
Labels: filigran team

#6908 [frontend] Remove copy/paste button for simpleError component (#5548-fix-frontend)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/Error.jsx
Labels: filigran team

#6917 [backend/frontend] Improve log management to take care of user interface errors (#6904)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/Error.jsx
  opencti-platform/opencti-front/src/private/components/settings/support/SupportPackages.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/boot.js
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/database/data-builder.js
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/file-search.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/migration.js
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/database/stix-representative.ts
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js
  opencti-platform/opencti-graphql/src/manager/indicatorDecayManager.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/support/support-domain.ts
  opencti-platform/opencti-graphql/src/parser/csv-parser.ts
  opencti-platform/opencti-graphql/src/resolvers/log.js
  opencti-platform/opencti-graphql/src/schema/identifier.js
  opencti-platform/opencti-graphql/src/schema/schema-attributes.ts
  opencti-platform/opencti-graphql/src/schema/schema-validator.ts
Labels: filigran team

#6931 [backend] Improve playbook to implement looping control and avoid extra execution (#6930)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/malware.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/graphql.js
  opencti-platform/opencti-graphql/src/manager/playbookManager.ts
  opencti-platform/opencti-graphql/src/modules/attributes/basicObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/basicRelationship-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-types.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook.graphql
  opencti-platform/opencti-graphql/src/schema/attribute-definition.ts
  opencti-platform/opencti-graphql/src/types/user.d.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/attribute-test.js
  opencti-worker/src/worker.py
Labels: filigran team

#6935 [frontend] Fix double encoding on search
  opencti-platform/opencti-front/src/utils/SearchUtils.js
  opencti-platform/opencti-front/src/utils/SearchUtils.ts
Labels: filigran team

#6901 Fix flaky e2e test
  opencti-platform/opencti-front/tests_e2e/model/form/reportForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/report/report.spec.ts
Labels: filigran team

#6926 [frontend] 'sighting' export from an entity exports all the sightings of the platform (#6761)
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/EntityStixSightingRelationships.tsx
Labels: bug, filigran team

#6964 [frontend] fix icons/chips colors in triggers list (#6956)
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerLine.tsx
Labels: filigran team

#6965 [frontend] always enable confidence level field in admin screens (#6718)
  opencti-platform/opencti-front/src/components/InputSliderField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/ConfidenceField.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/edition/UserConfidenceLevelField.tsx
Labels: filigran team

#6955 [frontend] Fix Navigation issue (#6934)
  opencti-platform/opencti-front/src/private/components/RootSearch.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Root.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/Root.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/Root.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/Root.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/Root.jsx
  opencti-platform/opencti-front/src/private/components/cases/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/Root.tsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/events/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/Root.jsx
  opencti-platform/opencti-front/src/private/components/events/Root.jsx
  opencti-platform/opencti-front/src/private/components/events/incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/Root.jsx
  opencti-platform/opencti-front/src/private/components/locations/regions/Root.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/observations/Root.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/Root.tsx
  opencti-platform/opencti-front/src/private/components/profile/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/private/components/techniques/Root.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/Root.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/Root.jsx
  opencti-platform/opencti-front/src/private/components/threats/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/Root.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/Root.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/Root.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/Root.tsx
Labels: filigran team

#6966 [backend] fix public dashboard with platform organization (#6948)
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-utils.ts
Labels: filigran team

#6927 [frontend] Complete Reports e2e tests (#5648)
  opencti-platform/opencti-front/src/private/components/common/lists/ListFilters.jsx
  opencti-platform/opencti-front/tests_e2e/model/EntitiesTab.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/ObservablesTab.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/field/FilterField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/field/TextField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/reportDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/report/report.spec.ts
  opencti-platform/opencti-front/tests_e2e/utils.ts
Labels: filigran team

#6890 [frontend] indicator generation Text displayed false (#6845)
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/data/drawers/PromoteDrawer.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/Root.tsx
Labels: filigran team

#6971 [frontend] Fix all filters usage
  opencti-platform/opencti-front/src/components/FilterIconButton.tsx
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/components/list_cards/ListCards.jsx
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
  opencti-platform/opencti-front/src/private/components/Search.tsx
  opencti-platform/opencti-front/src/private/components/StixObjectOrStixRelationship.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainertKnowledgeTimeLineBar.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/DialogFilters.jsx
  opencti-platform/opencti-front/src/private/components/common/lists/Filters.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/stream/StreamCollectionCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/stream/StreamCollectionEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionEdition.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerLiveCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionEdition.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetFilters.tsx
  opencti-platform/opencti-front/src/utils/filters/SearchEntitiesUtil.ts
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team

#6924 [frontend] displays ContainerStixCoreObjectPopover if update capability (#6920)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsMappingLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservableLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjectLine.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixObjectOrStixRelationshipLine.jsx
Labels: filigran team

#6982 [backend] Add initializer to file engine to allow async loading of the configuration (#6952)
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/initialization.js
  opencti-platform/opencti-graphql/tests/utils/globalSetup.ts
  opencti-platform/opencti-graphql/tests/utils/testSetup.js
Labels: filigran team

#6985 [Backend] Fix relationship_type get from rule page
  opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixCoreRelationship-test.js
Labels: filigran team

#6981 [Backend] Fix marking getting in settings if not existing
  opencti-platform/opencti-graphql/src/domain/settings.js
Labels: filigran team

#6970 [frontend] Fix relationships widgets not using the date attribute (#6732)
  opencti-platform/opencti-front/src/components/ExportButtons.jsx
  opencti-platform/opencti-front/src/private/components/common/form/AuthorizedMembersField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/AuthorizedMembersFieldListItem.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsDistributionList.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsDonut.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsHorizontalBars.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsMap.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsMultiHorizontalBars.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsPolarArea.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsRadar.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsTreeMap.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
  opencti-platform/opencti-front/tests_e2e/model/dashboardDetails.pageModel.ts
Labels: filigran team

#6987 [frontend] remove unnecessary abstract types in entity type filter list (#6976)
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
Labels: filigran team

#6988 [frontend] fix incorrect query used in RuleList (#6873)
  opencti-platform/opencti-front/src/private/components/settings/RulesList.jsx
  opencti-platform/opencti-front/tests_e2e/report/report.spec.ts
  opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixCoreRelationship-test.js
Labels: filigran team

#6957 [frontend/backend] Fix the separator in CSV feed's header(#6658)
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedLine.jsx
  opencti-platform/opencti-graphql/src/http/httpRollingFeed.ts
Labels: filigran team

#7007 [frontend] use i18n properly to insert links in text
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/Error.jsx
Labels: filigran team

#7025 [frontend] Fix the Shift key multi-select issue in the data/entities(#6783)
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#6986 [frontend/backend] Fix Can't unlink a task from a case template (#6834)
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplateTasksPopover.tsx
  opencti-platform/opencti-graphql/src/modules/case/case-template/case-template-domain.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/caseTemplate-test.ts
Labels: filigran team

#7004 [backend] Add an option in logger to enable logging of data from Error. (#6818)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/test.json
  opencti-platform/opencti-graphql/src/config/conf.js
Labels: filigran team

#7021 [backend] remove concurrency in reportDeleteWithElements (#7015)
  opencti-platform/opencti-graphql/src/domain/report.js
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation.ts
Labels: filigran team

#6811 [backend] check user access rights before deletion(#6421)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#6958 [frontend] improve large HTML content editing (#6383)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectContent.jsx
  opencti-platform/opencti-front/src/private/components/events/incidents/Root.tsx
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#7045 [frontend] hide share as public dashboard button for investigation (#7042)
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
Labels: filigran team

#7033 [frontend] Fix workbench SDO deduplication (#6797)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
Labels: filigran team

#7046 [frontend] Workbench: use octi observable type instead of stix type to compute observable value (#6996)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
Labels: filigran team

#7067 [frontend]Error message for the dashboard form is missing(#6704)
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceCreation.jsx
Labels: filigran team

#7010 [frontend] Tooltip on group confidence level, displaying overrides
  opencti-platform/opencti-front/src/private/components/settings/Overrides.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupConfidenceLevel.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserConfidenceLevel.tsx
Labels: filigran team

#7076 [backend] Fix error in OpenBas scenario generation (#7078)
  opencti-platform/opencti-front/vite.config.mts
  opencti-platform/opencti-graphql/src/modules/xtm/xtm-domain.js
Labels: filigran team

#7059 [backend/frontend] Add an option in user to force stateless session (#7058)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/users/edition/UserEditionOverview.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
Labels: filigran team

#7019 [backend/frontend] Improve search to prevent score ordering when specific ordering is requested (#7018)
  opencti-platform/opencti-front/src/components/list_cards/ListCards.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEdition.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/SearchUtils.ts
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/administrativeArea/administrativeArea.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rft/case-rft.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-template/case-template.graphql
  opencti-platform/opencti-graphql/src/modules/case/case.graphql
  opencti-platform/opencti-graphql/src/modules/case/feedback/feedback.graphql
  opencti-platform/opencti-graphql/src/modules/channel/channel.graphql
  opencti-platform/opencti-graphql/src/modules/dataComponent/dataComponent.graphql
  opencti-platform/opencti-graphql/src/modules/dataSource/dataSource.graphql
  opencti-platform/opencti-graphql/src/modules/decayRule/decayRule.graphql
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation.graphql
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting.graphql
  opencti-platform/opencti-graphql/src/modules/event/event.graphql
  opencti-platform/opencti-graphql/src/modules/grouping/grouping.graphql
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-rss.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii.graphql
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper.graphql
  opencti-platform/opencti-graphql/src/modules/language/language.graphql
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis.graphql
  opencti-platform/opencti-graphql/src/modules/narrative/narrative.graphql
  opencti-platform/opencti-graphql/src/modules/notification/notification.graphql
  opencti-platform/opencti-graphql/src/modules/notifier/notifier.graphql
  opencti-platform/opencti-graphql/src/modules/organization/organization.graphql
  opencti-platform/opencti-graphql/src/modules/playbook/playbook.graphql
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard.graphql
  opencti-platform/opencti-graphql/src/modules/task/task-template/task-template.graphql
  opencti-platform/opencti-graphql/src/modules/task/task.graphql
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.graphql
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary.graphql
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
Labels: filigran team

#7030 [frontend/backend] Default dashboard available in popover
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/DashboardSettings.jsx
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
Labels: filigran team

#6923 [frontend] Selecting a domain as a nested object of an Ipv4 crashes the front (#6919)
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
Labels: filigran team

#7057 [frontend/backend] Add available filter keys to stored filters for Taxii collections
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionEdition.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/tests/FilterUtilsConstants.ts
  opencti-platform/opencti-front/src/utils/tests/filtersUtils.test.tsx
  opencti-platform/opencti-front/src/utils/tests/test-render.tsx
  opencti-platform/opencti-front/src/utils/utils.ts
  opencti-platform/opencti-front/vitest.config.ts
  opencti-platform/opencti-graphql/src/domain/filterKeysSchema.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/filterKeysSchema-test.ts
  opencti-platform/opencti-graphql/tests/data/filter-keys-schema/stix-core-object.ts
  opencti-platform/opencti-graphql/tests/data/filter-keys-schema/stix-core-relationship.ts
Labels: filigran team

#7047 [backend] adapt effective confidence level computation (#6878)
  opencti-platform/opencti-graphql/src/utils/confidence-level.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/confidence-level-test.ts
Labels: filigran team

#7074 [backtend] create sharing task when add or delete relations (#6991)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#7048 [backend/frontend] Create 2 capabilities to access audit logging (#5549)
  opencti-platform/opencti-front/src/private/components/DashboardSettings.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/activity/audit/Audit.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/audit/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/configuration/Configuration.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useGranted.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/domain/log.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/migrations/1716392968109-capabilities-audits-security.js
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/data-initialization-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/audit-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/role-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
Labels: filigran team

#6925 [frontend/backend] Ability to filter on representatives in streams/playbooks/triggers (#6799)
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
  opencti-platform/opencti-front/src/private/components/data/stream/StreamCollectionCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/stream/StreamCollectionEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/stream/StreamLine.jsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerLine.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerLiveCreation.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/domain/filterKeysSchema.ts
  opencti-platform/opencti-graphql/src/utils/filtering/boolean-logic-engine.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-stix/stix-testers.ts
  opencti-platform/opencti-graphql/tests/01-unit/database/stix-filtering-testers-test.ts
  opencti-platform/opencti-graphql/tests/data/stream-events/stream-event-stix2-observables.json
Labels: filigran team, filters

#6862 [platform] Improve CSV mapper behavior to allow correct count and failure tracking (#6844)
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributeForm.tsx
  opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-domain.ts
  opencti-platform/opencti-graphql/src/parser/csv-bundler.ts
  opencti-platform/opencti-graphql/src/parser/csv-parser.ts
  opencti-platform/opencti-graphql/src/python/requirements.txt
  opencti-platform/opencti-graphql/src/types/stix-common.d.ts
  opencti-worker/src/worker.py
Labels: filigran team

#7008 [backend] fix nested filters query with eq operator (#6921)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
Labels: filigran team, filters

#7095 Add warning messages on report entities and observables tabs + translations (#7073)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservables.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjects.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsEntitiesView.tsx
  opencti-platform/opencti-front/tests_e2e/model/menu/leftBar.pageModel.ts
Labels: filigran team

#6938 [frontend] new filters in nested relationships from entity creation list (#6918)
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/components/filters/FilterValues.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team, filters

#7075 [frontend] E2E Dashboards - add data for testing purpose (#6704)
  opencti-platform/opencti-front/playwright.config.ts
  opencti-platform/opencti-front/tests_e2e/dataForTesting/README.md
  opencti-platform/opencti-front/tests_e2e/dataForTesting/init.data.ts
  opencti-platform/opencti-front/tests_e2e/dataForTesting/user.data.ts
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/script/script-insert-dataset.js
  opencti-platform/opencti-graphql/tests/data/data-test-stix-e2e.json
Labels: filigran team

#6756 Replaced Creation Floating Action Buttons for Analyses
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
  opencti-platform/opencti-front/src/private/components/analyses/ExternalReferences.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Groupings.tsx
  opencti-platform/opencti-front/src/private/components/analyses/MalwareAnalyses.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Notes.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Reports.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/AddExternalReferences.jsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/AddExternalReferencesLines.jsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/AddNotesFunctionalComponent.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/StixCoreObjectOrStixCoreRelationshipNotesCards.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/drawer/Drawer.tsx
  opencti-platform/opencti-front/src/private/components/common/menus/CreateEntityControlledDial.tsx
  opencti-platform/opencti-front/src/utils/hooks/useApiMutation.ts
  opencti-platform/opencti-front/tests_e2e/model/containerAddObservables.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/grouping.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/report.pageModel.ts
Labels: community

#7094 allow to resolve imports from src
  opencti-platform/opencti-front/tsconfig.json
  opencti-platform/opencti-front/vite.config.mts
Labels: filigran team

#7170 [backend]Authorized members in the customization of a feedback(#7151)
  opencti-platform/opencti-graphql/src/modules/case/feedback/feedback.ts
Labels: filigran team

#7001 [frontend] Add ability to override confidence per entity type in Group (#6878)
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupConfidenceLevel.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionConfidence.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/edition/ConfidenceOverrideField.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/edition/UserEditionConfidence.tsx
Labels: filigran team

#7172 [frontend] list exports with a search term (#7168)
  opencti-platform/opencti-front/src/private/components/Search.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservablesExportCreation.jsx
Labels: filigran team

#7166 [frontend] fix available relationship types in 'in regards of' filter (#7153)
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
Labels: filigran team, filters

#7155 [frontend] local mode switching for entity_type filter in relationship creation from entity (#7154)
  opencti-platform/opencti-front/src/components/filters/FilterValues.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
Labels: filigran team, filters

#7063 [CI] Enable multi-repository build from forks (#7062)
  .drone.yml
  scripts/clone-dependencies.sh
Labels: filigran team, multi-repository

#7130 [backend] fix user capabilities check for notification (#7109)
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/resolvers/note.js
  opencti-platform/opencti-graphql/src/resolvers/opinion.js
  opencti-platform/opencti-graphql/src/utils/access.ts
Labels: filigran team

#7126 [backend] Improve alias generation and resolution to improve data ingestion (#7020)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/migrations/1716392968110-alias_migration.js
  opencti-platform/opencti-graphql/src/schema/identifier.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/identifier-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
  opencti-platform/opencti-graphql/tests/utils/globalSetup.ts
Labels: filigran team

#7193 [frontend] Mutliple nested relations does not work (#7064)
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
Labels: filigran team

#7190 [backend] Allow external ID to be mapped in CSV mapper (#6813)
  opencti-platform/opencti-graphql/src/domain/attribute-utils.ts
Labels: filigran team

#7203 [backend] Add keyPrefix for sentinel redis mode
  opencti-platform/opencti-graphql/src/database/redis.ts
Labels: filigran team
