Repository OpenCTI-Platform/opencti, pull requests merged in 2024-10, with the labels that each got.

#8464 [frontend] Allow middle-mouse button to click on DataTable (#8394)
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
Labels: filigran team

#8521 [frontend] remove valid_until column in indicators list (#8520)
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/observations/Indicators.tsx
Labels: filigran team

#8555 [frontend] correlated reports policies size (#8514)
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
Labels: filigran team

#8567 [frontend] Fix right menu in security not being correctly highlighted when entering roles, users, or groups. (#8273)
  opencti-platform/opencti-front/src/private/components/common/menus/NavToolbarMenu.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/Root.tsx
Labels: filigran team

#8098 [frontend] Group members are inconsistent and can lead to mistakes on managing RBAC (#8050)
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionContainer.tsx
Labels: filigran team

#8574 [frontend] Revert unnecessary changes in DataTableWithoutFragment (#4230)
  opencti-platform/opencti-front/src/components/ThemeLight.ts
  opencti-platform/opencti-front/src/components/dashboard/WidgetListCoreObjects.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTableWithoutFragment.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableComponent.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/ResetColumnsButton.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionUsers.tsx
Labels: filigran team

#8573 [frontend] Fix margin (#8568)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx
Labels: filigran team

#8508 [frontend] Ability to duplicate a CSV feed data sharing, a CSV feed ingestion, a CSV mapper (#7400)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/CsvMappers.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperCreationContainer.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperForm.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperPopover.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedPopover.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvPopover.tsx
Labels: filigran team

#8504 [frontend] Change the "representation" key used in an investigation for an observable of type "File" (#7634)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.jsx
  opencti-platform/opencti-front/src/utils/Graph.js
  opencti-platform/opencti-front/src/utils/graph/EntityDetails.tsx
Labels: filigran team

#8537 [Backend] Add SAML option to get email from attribute (#8536)
  opencti-platform/opencti-graphql/src/config/providers.js
Labels: filigran team

#8277 [frontend] fixed header colors (#8249)
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEditionContainer.jsx
Labels: community

#8586 [frontend] Add pop up warning when activate organization segregation (#8284)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/Policies.tsx
Labels: filigran team

#8595 [frontend] English grammar errors in the toggle labels for the "Update a group" panel (#8445)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionOverview.tsx
Labels: filigran team

#8590 [backend/frontend] Dashboard selection fix + some widget alignment (#8433)
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetText.jsx
  opencti-platform/opencti-graphql/src/domain/user.js
Labels: filigran team

#8509 [backend/frontend] Implementation of sensitive configuration protection (#8284)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/Policies.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/CapabilitiesList.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/Role.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useSensitiveModifications.ts
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/domain/grant.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/user-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/data-initialization-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/role-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
Labels: filigran team

#8603 [frontend] Trial for color in DangerZone (#8284)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/Breadcrumbs.tsx
  opencti-platform/opencti-front/src/components/Theme.d.ts
  opencti-platform/opencti-front/src/components/ThemeDark.ts
  opencti-platform/opencti-front/src/components/ThemeLight.ts
  opencti-platform/opencti-front/src/private/components/common/dangerZone/DangerZoneBlock.tsx
  opencti-platform/opencti-front/src/private/components/common/dangerZone/DangerZoneChip.tsx
  opencti-platform/opencti-front/src/private/components/common/drawer/Drawer.tsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EnterpriseEdition.tsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EnterpriseEditionButton.tsx
  opencti-platform/opencti-front/src/private/components/settings/Policies.tsx
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/private/components/settings/file_indexing/FileIndexingMonitoring.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/CapabilitiesList.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/Role.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleLine.jsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RolePopover.jsx
  opencti-platform/opencti-front/src/private/components/settings/roles/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/Root.tsx
  opencti-platform/opencti-front/src/utils/hooks/useSensitiveModifications.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/user-test.ts
Labels: filigran team

#8569 [Backend] Enhance retention policy deletion performances / speed (#4864)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/domain/retentionRule.js
  opencti-platform/opencti-graphql/src/manager/managerModule.ts
  opencti-platform/opencti-graphql/src/manager/retentionManager.ts
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#8609 [frontend] fix danger zone display in capabilities (#8284)
  opencti-platform/opencti-front/src/private/components/settings/roles/CapabilitiesList.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
Labels: filigran team

#8581 [frontend] Fix Errorboundary to prevent rendering whole page when changine tab
  opencti-platform/opencti-front/src/private/Index.tsx
  opencti-platform/opencti-front/src/private/components/Error.jsx
  opencti-platform/opencti-front/src/private/components/analyses/Root.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/Root.tsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/entities/Root.tsx
  opencti-platform/opencti-front/src/private/components/events/Root.jsx
  opencti-platform/opencti-front/src/private/components/locations/Root.tsx
  opencti-platform/opencti-front/src/private/components/observations/Root.tsx
  opencti-platform/opencti-front/src/private/components/profile/Root.jsx
  opencti-platform/opencti-front/src/private/components/techniques/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/Root.tsx
  opencti-platform/opencti-front/src/private/components/trash/Root.tsx
  opencti-platform/opencti-front/src/public/PublicRoot.tsx
Labels: filigran team

#8594 [frontend] Narrative list wrong icon + alignment issue (#8533)
  opencti-platform/opencti-front/src/private/components/techniques/Narratives.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativesWithSubnarrativesLines.tsx
Labels: filigran team

#8548 [Backend] External reference fail creation as checked attribute is not the good one (#8545)
  opencti-platform/opencti-graphql/src/schema/schema-attributes.ts
Labels: filigran team

#8592 [Backend] Get all objects pagination can stop for invalid global count (#8579)
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/domain/container.js
Labels: filigran team

#8605 [frontend] Fix english grammar errors in the titles of the default dashboard widgets (#8442)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/Dashboard.jsx
Labels: filigran team

#8589 [backend/frontend] Use ID instead of label when resolving expectation from OpenBAS
  opencti-platform/opencti-front/vite.config.mts
  opencti-platform/opencti-graphql/src/database/xtm-obas.ts
Labels: filigran team

#8625 [backend] use component name in traces and fix warn issue.(#8352)(#8310)
  opencti-platform/opencti-graphql/src/manager/playbookManager.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team

#8591 [frontend] Remove links from Notifications (#6657)
  opencti-platform/opencti-front/src/components/ExpandableMarkdown.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorDetails.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationLine.tsx
Labels: filigran team

#8628 [frontend] External reference overview panels not aligned (#8223)
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceFileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceOverview.tsx
Labels: filigran team

#8632 [frontend] Display fixes (#8284)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/dangerZone/DangerZoneBlock.tsx
  opencti-platform/opencti-front/src/private/components/common/dangerZone/DangerZoneChip.tsx
  opencti-platform/opencti-front/src/private/components/common/drawer/Drawer.tsx
  opencti-platform/opencti-front/src/private/components/settings/Policies.tsx
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/CapabilitiesList.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/Role.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RolePopover.jsx
Labels: filigran team

#8617 [backend] Add feed queue control. Only add jobs if current queue is empty
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
Labels: filigran team

#8637 [frontend] Fix flag display for observables (#8635)
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
Labels: filigran team

#8633 [frontend] Fix bulk search
  opencti-platform/opencti-front/src/private/components/SearchBulk.jsx
Labels: filigran team

#8644 [frontend] Fix the positions when adding an entity in all the Knowlege graph view (#7298)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.jsx
Labels: filigran team

#8645 [frontend] fix ui after apexcharts update 3.54.0
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
Labels: filigran team

#8220 [backend/frontend] Add derived-from relationship in SDO & SCO of same type (#7962)
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualKnowledge.tsx
  opencti-platform/opencti-graphql/src/database/stix.ts
  opencti-platform/opencti-graphql/src/modules/administrativeArea/administrativeArea.ts
  opencti-platform/opencti-graphql/src/modules/channel/channel.ts
  opencti-platform/opencti-graphql/src/modules/dataComponent/dataComponent.ts
  opencti-platform/opencti-graphql/src/modules/dataSource/dataSource.ts
  opencti-platform/opencti-graphql/src/modules/event/event.ts
  opencti-platform/opencti-graphql/src/modules/grouping/grouping.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.ts
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis.ts
  opencti-platform/opencti-graphql/src/modules/narrative/narrative.ts
  opencti-platform/opencti-graphql/src/modules/organization/organization.ts
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.ts
Labels: filigran team

#8341 Additional Threat Actor Relationship Types
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualKnowledge.tsx
  opencti-platform/opencti-front/src/utils/Colors.js
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.ts
  opencti-platform/opencti-graphql/src/schema/stixCoreRelationship.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/filterKeysSchema-test.ts
Labels: community

#8666 [backend] Do not impact entities targeted by related to relations from observables (#8665)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#8662 [frontend] Rollback on unclear code and fix navigation (#8647)
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
Labels: filigran team

#8664 [backend] Ensure that all connectors queues are initialized at platform start (#8642)
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
  opencti-platform/opencti-graphql/src/initialization.js
Labels: filigran team

#8634 [frontend] Update relationship creation and display (#8576)
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsRelationshipsView.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualKnowledge.tsx
Labels: filigran team

#8496 [backend] ignore objectOrganization in reindexing (#8495)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#8669 [frontend] Bad icons replaced in connector overview(#8225)
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.jsx
Labels: filigran team

#8670 [frontend] Fix the height of the Observables distribution graph(#8599)
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentDetails.tsx
Labels: filigran team

#8668 [frontend] Fix time filters in relationships counters (#8630)
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsNumber.jsx
Labels: filigran team

#8678 [frontend] In Investigation graph fix date display after node modification (#8557)
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.jsx
Labels: filigran team

#8577 [frontend/backend] Migrate CK Editor to 9.3 (#8151)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/components/CKEditor.tsx
  opencti-platform/opencti-front/src/components/fields/RichTextField.jsx
  opencti-platform/opencti-front/src/front.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContent.jsx
  opencti-platform/opencti-front/src/utils/ai/ResponseDialog.tsx
  opencti-platform/opencti-front/tests_e2e/model/StixDomainObjectContentTab.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/field/TextField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/settings/entitySettings.spec.ts
  opencti-platform/opencti-front/vite.config.mts
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#8587 [backend] Fix missing entites in shared report (#8333)
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/schema/stixRefRelationship.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/organization-sharing-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/data/organization-sharing/20241003_Report_to_test_orga_sharing_full.json
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
Labels: filigran team

#8459 [backend/frontend] fix multiple issues for Organisation Admins (#8101)
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/python/testing/local_synchronizer.py
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#8679 [backend] observables value key added on resolver (#8312)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-converter.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-resolver.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-types.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.graphql
  opencti-platform/opencti-graphql/src/types/store.d.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
  opencti-platform/opencti-graphql/tests/data/csv-bundler/external-references-constants.ts
  opencti-platform/opencti-graphql/tests/data/csv-bundler/kill-chains-constants.ts
  opencti-platform/opencti-graphql/tests/data/csv-bundler/labels-constants.ts
Labels: filigran team, multi-repository

#8701 [frontend] Improve vite config for development purpose (#8703)
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/vite.config.mts
Labels: filigran team

#8690 [frontend] Containers list in Analysis tab of Organization display as Author (#8681)
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainers.jsx
Labels: filigran team

#8695 redirect link updated for observables
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/EntityStixSightingRelationshipLine.tsx
Labels: filigran team

#8627 [frontend] rework UI for connector error screen (#8614)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemCopy.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorWorks.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorWorksErrorLine.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/parseWorkErrors.ts
Labels: filigran team

#8674 [frontend] Enable enrichment with the selectAll of observables and stix-domain-objects of the same type (#5582)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/tests/filtersUtils.test.tsx
Labels: filigran team

#8719 [frontend] Missing author column in the home dashboard reports list (#8712)
  opencti-platform/opencti-front/src/components/dashboard/WidgetListCoreObjects.tsx
Labels: filigran team

#8699 [frontend] Danger zone: rule engine, EE deactivation, marking lists and file indexing (#8284)
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/dangerZone/DangerZoneBlock.tsx
  opencti-platform/opencti-front/src/private/components/settings/RulesList.jsx
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionLine.jsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionPopover.jsx
  opencti-platform/opencti-front/src/utils/hooks/useSensitiveModifications.ts
Labels: filigran team

#8199 Popover Removal - Locations
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaDeletion.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaPopover.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityDeletion.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityPopover.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryDeletion.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryPopover.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionDeletion.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionPopover.jsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionPopoverDeletion.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionDeletion.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionPopover.tsx
Labels: community

#8717 [backend] check indicator pattern syntax when update (#8683)
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
Labels: filigran team

#8747 [frontend] fix assignee query to prevent impact on aliases (#4333)
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectHeader.jsx
Labels: filigran team

#8722 [frontend] Fixing node positions in graphs (#7298)
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftEditionOverview.tsx
Labels: filigran team

#8731 [backend] replace plyara with yara-python for yara indicator check (#8291)
  opencti-platform/opencti-graphql/src/python/requirements.txt
  opencti-platform/opencti-graphql/src/python/runtime/check_indicator.py
  opencti-platform/opencti-graphql/tests/01-unit/python/pythonBridge-test.js
Labels: filigran team

#8757 [frontend] Container content: Move download file actions directly in file line (#3402)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContent.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentBar.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFiles.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
Labels: filigran team

#8775 [backend] update cookie from 0.6.0 to 0.7.0
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/yarn.lock
Labels: security, dependencies, filigran team

#8787 [frontend] Migrate CK Editor to 9.3 (#8151)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/components/CKEditor.tsx
  opencti-platform/opencti-front/src/components/fields/RichTextField.jsx
  opencti-platform/opencti-front/src/front.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContent.jsx
  opencti-platform/opencti-front/src/utils/ai/ResponseDialog.tsx
  opencti-platform/opencti-front/tests_e2e/model/StixDomainObjectContentTab.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/field/TextField.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/settings/entitySettings.spec.ts
  opencti-platform/opencti-front/vite.config.mts
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#8121 Popover Removal - Cases
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentDeletion.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentPopover.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiDeletion.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiPopover.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftDeletion.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftPopover.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/FeedbackDeletion.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/FeedbackEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/FeedbackPopover.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TaskDeletion.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TaskPopover.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TasksEditionOverview.tsx
  opencti-platform/opencti-front/tests_e2e/model/incidentResponseDetails.pageModel.ts
Labels: community

#8786 [backend] deduplication check is now done with SYSTEM user (#8740)
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#8106 Popover Removal - Analyses (Updated)
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceDeletion.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferencePopover.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/StixCoreObjectExternalReferencesLines.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/StixCoreRelationshipExternalReferencesLines.jsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/StixSightingRelationshipExternalReferencesLines.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingDeletion.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingPopover.jsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisDeletion.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisPopover.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteDeletion.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NotePopover.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDeletion.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportPopover.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportPopoverDeletion.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectEnrichment.jsx
  opencti-platform/opencti-front/tests_e2e/model/reportDetails.pageModel.ts
Labels: community

#8725 [backend] Adding info logs to task manager (#8720)
  opencti-platform/opencti-graphql/src/manager/taskManager.js
Labels: filigran team

#8732 [CI] Update scripts to use PR target branch instead of hardcoded master (#8656)
  .drone.yml
  scripts/clone-dependencies.sh
Labels: filigran team

#8718 [frontend] filter utils tests
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/tests/filtersUtils.test.tsx
Labels: filigran team

#8738 [backend] Attributes can't have same label and different names in schema (#8726)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixCyberObservable-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixMetaObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii.ts
  opencti-platform/opencti-graphql/src/modules/managerConfiguration/managerConfiguration.ts
  opencti-platform/opencti-graphql/src/modules/notifier/notifier.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook.ts
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.ts
  opencti-platform/opencti-graphql/src/schema/schema-attributes.ts
Labels: filigran team

#8746 [frontend] Extension is not always set to .json (#7720)
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/widgetExportHandler.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/workspaceExportHandler.tsx
Labels: filigran team

#8802 [frontend] Fix delete button behaviour
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReference.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportPopover.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportPopoverDeletion.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/FeedbackEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionEditionOverview.tsx
Labels: filigran team

#8702 [backend] Implement exclusion lists pattern check (#8312)
  opencti-platform/opencti-graphql/src/utils/exclusionLists.ts
  opencti-platform/opencti-graphql/src/utils/exclusionListsTypes.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/exclusionLists-test.ts
Labels: filigran team

#8805 [frontend] Add some unit tests (#8804)
  opencti-platform/opencti-front/src/components/dashboard/WidgetNumber.test.tsx
  opencti-platform/opencti-front/src/utils/hooks/useAuth.test.ts
Labels: filigran team

#8828 [frontend] Fix enrichment button (#8825)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectEnrichment.jsx
Labels: filigran team

#8782 [frontend] Add defaultStartTime and stopTime for StixCoreRelationship creation (#8575)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationForm.js
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraphBar.jsx
Labels: filigran team

#8801 [frontend] connector errors UI - resolve entities - improve design (#8614)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorWorks.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorWorksErrorLine.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/parseWorkErrors.ts
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#8823 [frontend] UI fix scrollbar useless in custom dashboard (#8282)
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
Labels: filigran team

#8741 [backend/frontend] Danger zone: Add config in platform settings (#8284)
  opencti-platform/opencti-front/src/components/Breadcrumbs.tsx
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/danger_zone/DangerZoneBlock.tsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EnterpriseEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/Policies.tsx
  opencti-platform/opencti-front/src/private/components/settings/RulesList.jsx
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/private/components/settings/file_indexing/FileIndexingMonitoring.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/CapabilitiesList.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/Role.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleLine.jsx
  opencti-platform/opencti-front/src/private/components/settings/roles/Root.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useSensitiveModifications.test.ts
  opencti-platform/opencti-front/src/utils/hooks/useSensitiveModifications.ts
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/settings.js
Labels: filigran team

#8854 [frontend] rename parsedWorkError.tsx (#8614)
  opencti-platform/opencti-front/src/private/components/data/connectors/parseWorkErrors.tsx
Labels: filigran team
