Repository OpenCTI-Platform/opencti, pull requests merged in 2024-08, with the labels that each got.

#7912 [frontend] Cleaning up unused props
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#7913 [frontend] Fix simulation alignment (#7904)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
  opencti-platform/opencti-front/src/private/components/events/incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/Root.tsx
Labels: filigran team

#7195 [frontend] Allow Users to Add an Entity as Context When Uploading File
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/FilterIconButton.tsx
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileImportMarkingSelectionPopup.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileUploader.tsx
  opencti-platform/opencti-front/src/private/components/common/form/AssociatedEntityField.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: community, ui

#7911 [frontend/backend] Fix default value of variable "first" that cannot be null (#7905)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionsLines.jsx
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/markingDefinition-test.js
Labels: filigran team, critical

#7936 [frontend] directory default value in workbench (#7910)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/utils/defaultRepresentatives.ts
Labels: filigran team

#7698 [backend/frontend] Retention rules for files and workbench (#7482)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/FilterIconButton.tsx
  opencti-platform/opencti-front/src/private/components/settings/Retention.jsx
  opencti-platform/opencti-front/src/private/components/settings/Retention.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionEdition.jsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionLine.jsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionLines.jsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionLines.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/database/file-storage-helper.ts
  opencti-platform/opencti-graphql/src/domain/retentionRule.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/clusterManager.ts
  opencti-platform/opencti-graphql/src/manager/index.ts
  opencti-platform/opencti-graphql/src/manager/managerModule.ts
  opencti-platform/opencti-graphql/src/manager/retentionManager.js
  opencti-platform/opencti-graphql/src/manager/retentionManager.ts
  opencti-platform/opencti-graphql/src/managers.js
  opencti-platform/opencti-graphql/src/migrations/1722320850955-add-retention-rule-knowledge-scope.js
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
  opencti-platform/opencti-graphql/src/resolvers/file.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/administrativeArea-test.js
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/retentionManager-test.ts
Labels: filigran team

#7941 [frontend] authorize Case Incident organization sharing (#7939)
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/form/FormAuthorizedMembersDialog.tsx
Labels: filigran team

#6550 [backend] nil filter operators for empty strings and dates (#6517)
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
  opencti-platform/opencti-graphql/tests/04-sync/00-Raw/sync-raw-test.js
  opencti-platform/opencti-graphql/tests/data/DATA-TEST-STIX2_v2.json
Labels: filigran team, filters & search

#7909 [frontend] fix attack patterns details with not "empty" signs "-" (#7869)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectKillChainPhasesView.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternCoursesOfAction.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDataComponents.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternDetails.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternSubAttackPatterns.jsx
Labels: filigran team

#7938 [frontend] Duplicates exist in the Korean translation (#7866)
  opencti-platform/opencti-front/lang/front/ko.json
Labels: filigran team

#7947 [backend] Add feature flag for active users count (#7943)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/manager/telemetryManager.ts
Labels: filigran team

#7825 [backend] Edit customization through the API (#6724)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/entity_setting/EntitySettingSettings.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-domain.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-types.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting.graphql
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting.ts
  opencti-platform/opencti-graphql/src/schema/module.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/threatActorIndividual-test.ts
Labels: filigran team

#7800 [frontend] Add in bulk entities and some observables in knowledge and containers tabs (#4352)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/fields/BulkTextField/BulkTextField.tsx
  opencti-platform/opencti-front/src/components/fields/BulkTextField/BulkTextModal.tsx
  opencti-platform/opencti-front/src/components/fields/BulkTextField/BulkTextModalButton.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsInLine.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualCreation.tsx
  opencti-platform/opencti-front/src/utils/String.jsx
  opencti-platform/opencti-front/src/utils/hooks/useBulkCommit.tsx
  opencti-platform/opencti-front/tests_e2e/enableReferences/addReportObservable.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/EntitiesTab.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/containerObservables.pageModel.ts
Labels: filigran team

#7802 [frontend/backend] Add EPSS Support for Vulnerability Entity (#3568)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityDetails.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionDetails.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/types/store.d.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/attribute-test.js
  opencti-platform/yarn.lock
Labels: filigran team, multi-repository

#7949 [backend] Fix Bypass external ref issue (#7945)
  opencti-platform/opencti-graphql/src/schema/schema-validator.ts
Labels: filigran team

#7963 [backend] Disable count active users (#7943)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/manager/telemetryManager.ts
Labels: filigran team

#7976 [backend] Fix too_long_http_line_exception error on splunk stream (#7975)
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
Labels: filigran team

#7959 [backend/frontend] Fix Kill all session button in the user overview (#7837)
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
  opencti-platform/opencti-graphql/src/database/session.js
Labels: filigran team

#7956 [backend/frontend] add sorting on retention rules view (#7482)
  opencti-platform/opencti-front/src/private/components/settings/Retention.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionLines.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#7960 [frontend] Disable labels and in_platform sorting in Workbench content (#7798)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
Labels: filigran team

#7958 [frontend] fix detection field focus in Attack Pattern edition form (#7940)
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternEditionDetails.jsx
Labels: filigran team

#7981 [backend] Add logs in CSV ingestion manager
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
Labels: filigran team

#7980 [backend] Kill session on synchro when an HTTP error is send to client. (#7842)
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
  opencti-platform/opencti-graphql/src/manager/syncManager.js
Labels: filigran team

#7783 [backend] Allow iframe usage for public dashboard (#7756)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
Labels: filigran team

#7990 [backend] Change how CSV Ingestion hashes are generated (#7988)
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/utils/hash.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/hash-test.ts
Labels: filigran team

#7991 [backend] fix entity organization sharing for users outside platform organization (#7974)
  opencti-platform/opencti-graphql/src/database/data-builder.js
Labels: filigran team

#7985 [frontend] change chart's background color (#7737)
  opencti-platform/opencti-front/src/utils/Charts.js
Labels: filigran team

#8002 [frontend] [Workbench] Can't create relationship with Area entity type (#7907)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/utils/Entity.ts
Labels: filigran team

#8008 [frontend] start and stop time edition for nested ref (#7968)
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipEditionOverview.jsx
Labels: filigran team

#8028 [backend] Works batching
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/resolvers/file.js
Labels: filigran team

#8031 [backend] Trial for improving import page
  opencti-platform/opencti-front/src/private/components/data/import/Import.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContentContainer.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportFilesContent.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportWorkbenchesContent.tsx
  opencti-platform/opencti-front/src/private/components/data/import/Root.jsx
  opencti-platform/opencti-graphql/src/boot.js
Labels: filigran team

#8029 [backend] lower verbosity of feature flag logs
  opencti-platform/opencti-graphql/src/boot.js
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/initialization.js
Labels: filigran team

#8036 [frontend] display reliability in one line (#8026)
  opencti-platform/opencti-front/src/components/ItemOpenVocab.tsx
Labels: filigran team

#8049 [frontend] lines in connector centered vertically (#8027)
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
Labels: filigran team

#8071 [backend] Apollo errors for version 4 refactor to comply with previous version
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/boot.js
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/config/errors.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/connector.ts
  opencti-platform/opencti-graphql/src/domain/externalReference.js
  opencti-platform/opencti-graphql/src/domain/feed.ts
  opencti-platform/opencti-graphql/src/graphql/graphql.js
  opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js
  opencti-platform/opencti-graphql/src/initialization.js
  opencti-platform/opencti-graphql/src/manager/activityManager.ts
  opencti-platform/opencti-graphql/src/manager/connectorManager.js
  opencti-platform/opencti-graphql/src/manager/expiredManager.js
  opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
  opencti-platform/opencti-graphql/src/manager/historyManager.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/manager/managerModule.ts
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/manager/playbookManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/manager/ruleManager.ts
  opencti-platform/opencti-graphql/src/manager/syncManager.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-domain.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-validators.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-utils.ts
  opencti-platform/opencti-graphql/src/schema/schema-attributes.ts
  opencti-platform/opencti-graphql/src/schema/schema-validator.ts
  opencti-platform/opencti-graphql/tests/01-unit/database/validateDataBeforeIndexing-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/schema-validator-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/entitySetting-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/publicDashboard-test.js
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#8072 [worker] Introduce new mecanic to split bundle and requeue
  opencti-worker/src/worker.py
Labels: filigran team

#8104 [frontend] Fix toolbar for merge on entities (#8103)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#7702 [frontend/backend] Dashboard refacto - split view between dashboard and public dashboards
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncident.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/Feedback.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Root.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceLine.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Workspaces.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Root.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/publicDashboards/PublicDashboardLineActions.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/publicDashboards/PublicDashboards.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/authorizedMembers.ts
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/menu/leftBar.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/navigation/navigation.spec.ts
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/domain/basicObject.ts
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/schema.js
  opencti-platform/opencti-graphql/src/migrations/1723192290000-remove-authorized-members-public-dashboard.js
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-domain.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-types.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-utils.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard.graphql
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-resolver.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
  opencti-platform/opencti-graphql/src/resolvers/basicObject.ts
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
  opencti-platform/opencti-graphql/src/schema/schema-attributes.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/publicDashboard-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#8112 [backend] Fix migration timestamp (#6509)
  opencti-platform/opencti-graphql/src/migrations/1724139009000-remove-authorized-members-public-dashboard.js
Labels: filigran team

#8054 [backend] Fix UI issue when changing organization in a user (#7682)
  opencti-platform/opencti-graphql/src/domain/user.js
Labels: filigran team

#8118 [backend] History is not correct when you impact the score with a background task (#7885)
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
Labels: filigran team

#8126 [frontend] roll back apexcharts to 3.51.0 (#8124)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#8130 [frontend] display alias value in place of alias label in form field (#8053)
  opencti-platform/opencti-front/src/components/AutocompleteFreeSoloField.jsx
Labels: filigran team

#8136 [frontend] allow transparent background Radar option (#8113)
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsRadar.tsx
  opencti-platform/opencti-front/src/utils/Charts.js
Labels: filigran team

#6629 [frontend/backend] Added persona/moniker support
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableDetails.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/AddIndividualsThreatActorIndividual.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/AddIndividualsThreatActorIndividualLines.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/AddPersonasThreatActorIndividual.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/AddPersonasThreatActorIndividualLines.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualDetails.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualDetailsChips.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/threatActorIndividualMutations.ts
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Colors.js
  opencti-platform/opencti-front/src/utils/Entity.ts
  opencti-platform/opencti-front/src/utils/Graph.js
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/file-storage-helper.ts
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/database/stix-representative.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/migrations/1724250605381-vocabulary-add-persona-types.js
  opencti-platform/opencti-graphql/src/modules/attributes/stixCyberObservable-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.ts
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary-types.ts
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary-utils.ts
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary.graphql
  opencti-platform/opencti-graphql/src/python/runtime/stix2_create_pattern.py
  opencti-platform/opencti-graphql/src/schema/identifier.js
  opencti-platform/opencti-graphql/src/schema/stixCoreRelationship.ts
  opencti-platform/opencti-graphql/src/schema/stixCyberObservable.ts
  opencti-platform/opencti-graphql/src/types/stix-sco.d.ts
  opencti-platform/opencti-graphql/src/types/store.d.ts
  opencti-platform/opencti-graphql/src/utils/format.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/filterKeysSchema-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/persona-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/00-Raw/sync-raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/sync-utils.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  scripts/clone-dependencies.sh
Labels: community, multi-repository, datamodel

#8143 [frontend] Add forgotten feature flag (#8134)
  opencti-platform/opencti-front/src/private/components/data/ImportMenu.tsx
  opencti-platform/opencti-front/src/private/components/data/import/Root.jsx
Labels: filigran team

#8148 [frontend] Fix for TAI mutations (#8149)
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/AddIndividualsThreatActorIndividualLines.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/AddPersonasThreatActorIndividualLines.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/threatActorIndividualMutations.ts
  opencti-platform/opencti-front/src/utils/Colors.js
Labels: filigran team

#7937 [backend/frontend] Remove last SETTINGS capabilities (#3304)
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useGranted.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/migrations/1724405107527-trigger-authorized-authorities.js
  opencti-platform/opencti-graphql/src/modules/notification/notification-domain.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
Labels: filigran team

#8155 [backend/worker] Release 6.2.15
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/python/requirements.txt
  opencti-worker/src/requirements.txt
Labels: filigran team

#8016 [frontend] fix filters format for organizations queries (#8013)
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/SettingsOrganizationUserCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/edition/UserEditionOverview.tsx
  opencti-platform/opencti-graphql/src/modules/organization/organization.graphql
Labels: filigran team

#8141 [frontend] Change light theme accent (#8129)
  opencti-platform/opencti-front/src/components/ThemeLight.ts
Labels: filigran team

#7993 [ci] Allow retry for e2e tests (#7378)
  opencti-platform/opencti-front/package.json
Labels: filigran team

#8034 [frontend] [Bulk search] The column ordering of markings doesn't work (#7623)
  opencti-platform/opencti-front/src/private/components/SearchBulk.jsx
Labels: filigran team

#8163 [backend] Fix capabilities check on background tasks
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
Labels: filigran team

#8114 [frontend/backend] Create public dashboards from dashboard list pages (#6509)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareButton.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareForm.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareList.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/public_dashboards/PublicDashboardCreation.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/public_dashboards/PublicDashboardCreationForm.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/public_dashboards/PublicDashboards.tsx
  opencti-platform/opencti-front/vite.config.mts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-domain.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-utils.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/publicDashboard-test.js
Labels: filigran team

#8135 [backend] Be able to use Vulnerability specific fields in playbook filters (#7409)
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-stix/stix-testers.ts
Labels: filigran team

#8165 [frontend] Allow clicking on External References (#8156)
  opencti-platform/opencti-front/src/private/components/analyses/external_references/AddExternalReferencesLines.jsx
Labels: filigran team

#8181 [backend] Change kill_chain_phase.order attribute upsert value (#8182)
  opencti-platform/opencti-graphql/src/modules/attributes/stixMetaObject-registrationAttributes.ts
Labels: filigran team

#8166 [ci] Add upload of test results to JFrog (#7378)
  .drone.yml
  opencti-platform/opencti-front/playwright.config.ts
Labels: filigran team

#8206 [backend] Add a missing basePath (#8205)
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/http/httpServer.js
Labels: filigran team

#8209 [backend] [Workbench] Campaign object unrecognized in relationships (#6758)
  opencti-platform/opencti-graphql/src/database/stix.ts
Labels: filigran team

#8030 [backend] Fix organization admin user can't delete/edit user account status (#8011)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-graphql/src/database/session.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/modules/notification/notification-domain.ts
  opencti-platform/opencti-graphql/src/modules/organization/organization-domain.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#8187 [e2e] Enable back end to end test on background tasks (#7378)
  opencti-platform/opencti-front/tests_e2e/backgroundTask/backgroundTask.spec.ts
Labels: filigran team

#8217 [frontend] Fixing note creation auto-scroll when layout is custom (#6724)
  opencti-platform/opencti-front/src/private/components/analyses/notes/StixCoreObjectOrStixCoreRelationshipNotesCards.tsx
Labels: filigran team

#8158 [backend/frontend] massive delete operations for public dashboard and workspaces (#6509)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/Breadcrumbs.tsx
  opencti-platform/opencti-front/src/components/TaskScope.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableComponent.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceCreation.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceLine.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Workspaces.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacesLines.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/public_dashboards/PublicDashboards.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Entity.ts
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/investigations/createInvestigation.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboard.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/investigationDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/investigations.pageModel.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/backgroundTask-common-test.ts
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team
