Repository OpenCTI-Platform/opencti, pull requests merged in 2024-04, with the labels that each got.

#6524 [backend] Improve template loading if available in cache (#6516)
  opencti-platform/opencti-graphql/src/manager/cacheManager.ts
  opencti-platform/opencti-graphql/src/resolvers/status.ts
Labels: filigran team

#6519 [frontend] possibility to select attributes in entity widgets (#6515)
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
Labels: filigran team

#6531 [frontend] change icon for PolarArea
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
Labels: filigran team

#6533 [backend] Improve connection drop handling for importCSV connector (#6314)
  opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
Labels: filigran team

#6529 [frontend/backend] Add validation on authentication field content for Taxii authentication (#6403)
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiEdition.jsx
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-types.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/ingestion-taxii-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-taxii-test.ts
Labels: filigran team

#6163 [backend] Filter observables creation with refs from indicators (#5293)
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
  opencti-platform/opencti-graphql/src/utils/syntax.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/indicator-test.ts
Labels: filigran team

#6548 [frontend] fix bulk search not returning HashedObservable (#6522)
  opencti-platform/opencti-front/src/private/components/SearchBulk.jsx
  opencti-platform/opencti-front/src/private/components/search/SearchStixCoreObjectsLines.tsx
Labels: filigran team

#6532 [frontend] Uncheck the 'select all' box when launching a background task (#6526)
  opencti-platform/opencti-front/src/private/components/profile/Notifications.tsx
Labels: filigran team

#6410 [frontend] fix EE button in organization edition is not clickable (#6378)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EEField.tsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EnterpriseEditionAgreement.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganizationEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEdition.tsx
Labels: filigran team

#6553 [backend] fix instance context redirection in Activity events (#6549)
  opencti-platform/opencti-graphql/src/resolvers/log.js
Labels: filigran team

#6554 [frontend] replace primary color by marking color (#6542)
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionMarkings.tsx
Labels: filigran team

#6565 [backend] Fix No error when merging two entities with a higher confidence level (#6502)
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/utils/confidence-level.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/confidence-level-test.ts
Labels: filigran team

#6574 [frontend] Fix "Select all" not available for relationship creation (#6407)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntityLines.jsx
Labels: filigran team

#6591 [frontend] fix error when searching attack patterns (#6551)
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternsMatrixColumns.jsx
Labels: filigran team

#6468 [frontend] roll back investigation graph after expanding a node (#3167)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/Dialog/InvestigationRollBackExpandDialog.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/utils/investigationStorage.ts
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/utils/setStackDataInSessionStorage/setStackDataInSessionStorage.test.ts
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/utils/setStackDataInSessionStorage/setStackDataInSessionStorage.ts
Labels: feature, filigran team

#6624 [frontend] fix editing panel closing (#6601)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipOverview.jsx
Labels: filigran team

#6631 [frontend] relationship page - remove padding right
  opencti-platform/opencti-front/src/private/components/events/observed_data/Root.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableKnowledge.jsx
Labels: filigran team

#6639 [frontend] replace icon anchor on minimap (#6599)
  opencti-platform/opencti-front/src/private/components/common/location/LocationMiniMap.jsx
Labels: filigran team

#6590 [frontend] CI Verify translation automatically
  .drone.yml
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/script/extract-i18n-keyword.js
  opencti-platform/opencti-front/script/extract-label-keyword.js
  opencti-platform/opencti-front/script/sort-translation-files.js
  opencti-platform/opencti-front/script/verify-translation.js
Labels: filigran team

#6636 [backend] fix rels batch loading (#6635)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsLine.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityStixCoreObjectsLine.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjectsLine.tsx
  opencti-platform/opencti-graphql/src/resolvers/stix.js
Labels: filigran team

#6640 [backend] Improve objects resolutions event loop usage for large report (#6638)
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/redis.ts
Labels: filigran team

#6649 [frontend/backend] fix translations (#6648)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/activity/audit/Audit.tsx
Labels: filigran team

#6663 [frontend] fix filters group sorting in filter list (#6655)
  opencti-platform/opencti-front/src/private/components/common/lists/ListFilters.jsx
Labels: filigran team, filters

#6664 [frontend/backend] Fix 'User experience' and 'Unit system translation(#6…
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
Labels: filigran team

#6665 [backend] Remove unwanted .zip on filename inside zip (#6384)
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
Labels: filigran team

#6677 [backend] use reverse relation on countries located at regions (#6528)
  opencti-platform/opencti-graphql/src/domain/region.js
Labels: filigran team

#6693 [frontend] disable mode switching for unmodifiable entity type filter in relationship entities list (#6692)
  opencti-platform/opencti-front/src/components/FilterIconButton.tsx
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/filters/FilterValues.tsx
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggerLiveCreation.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team, filters

#6712 [backend] improve users loading using cache (#6702)
  opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts
  opencti-platform/opencti-graphql/src/database/cache.ts
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/csvMapper-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixCyberObservable-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/csv-mapper-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#6736 [frontend/backend] Multiple bugfixes
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/common/charts/Chart.tsx
  opencti-platform/opencti-front/src/relay/environment.jsx
  opencti-platform/opencti-front/src/utils/hooks/useFormEditor.ts
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#6721 [frontend] update frontend when adding a user to a group (#6703)
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionUsers.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionUsers.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/GroupUsers.tsx
Labels: filigran team

#6723 [backend] add email in search attributes (#6717)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#6701 [frontend] Add property 'name' on ObservedData queries (#6687)
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainerLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixRelationshipLastContainers.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsList.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectBookmarksList.jsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsList.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_domain_objects/PublicStixDomainObjectBookmarksList.tsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
Labels: filigran team

#6714 [backend] handle string fields trimming in create/update operations (#6708)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#6683 [backend] fix stix_id upsert (#6559)
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#6672 Fix playbook Container Wrapper producing bundles that cannot be ingested (#6302)
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixRelationshipLastContainers.jsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/Playbook.jsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
  opencti-platform/opencti-front/src/utils/hooks/useEntityTranslation.ts
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
  opencti-platform/opencti-graphql/src/schema/general.js
Labels: filigran team

#6752 [frontend] do nothing on click in error export file (#6650)
  opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx
Labels: filigran team

#6755 [backend] Fix manager configuration schema (#6697)
  opencti-platform/opencti-graphql/src/modules/managerConfiguration/managerConfiguration.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/index-file-test.js
Labels: filigran team

#6754 [backend] Fix public dashboard area chart time serie (#6753)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#6418 [frontend/backend] Public dashboards (#4903)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/script/sort-translation-files.js
  opencti-platform/opencti-front/src/components/dashboard/WidgetDistributionList.tsx
  opencti-platform/opencti-front/src/components/dashboard/WidgetListCoreObjects.tsx
  opencti-platform/opencti-front/src/components/dashboard/WidgetListRelationships.tsx
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/form/MarkingsSelectField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/ObjectMarkingField.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperTestDialog.tsx
  opencti-platform/opencti-front/src/private/components/settings/Policies.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareButton.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareForm.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareList.tsx
  opencti-platform/opencti-front/src/public/PublicRoot.tsx
  opencti-platform/opencti-front/src/public/components/PublicDashboard.tsx
  opencti-platform/opencti-front/src/public/components/PublicDataSharing.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsDistributionList.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsList.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsTimeline.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_relationships/PublicStixRelationshipsDistributionList.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_relationships/PublicStixRelationshipsList.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_relationships/PublicStixRelationshipsTimeline.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/usePublicDashboardWidgets.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/cacheManager.ts
  opencti-platform/opencti-graphql/src/migrations/1704893567321-capability-publish-knowledge.js
  opencti-platform/opencti-graphql/src/migrations/1713449762000-investigations-and-dashboards-capabilities.js
  opencti-platform/opencti-graphql/src/migrations/1713449762001-add-platform-data-sharing-max-markings.js
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-converter.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-domain.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-types.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-utils.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard.graphql
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard.ts
  opencti-platform/opencti-graphql/src/resolvers/settings.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/publicDashboard-utils-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/publicDashboard-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/settings-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#6592 [backend] Confidence level by users: Overrides by Entity types (chunk 1) (#4900)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/utils/confidence-level.ts
  opencti-platform/opencti-graphql/tests/01-unit/database/validateDataBeforeIndexing-test.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/confidence-level-test.ts
Labels: filigran team

#6627 [frontend] disable nested relation creation in Knowledge graph if relation doesn't exist (#3389)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromKnowledgeGraphContent.tsx
Labels: filigran team

#6776 [frontend] fix redirectionUtils in horizontal bars (#6764)
  opencti-platform/opencti-front/src/utils/hooks/useDistributionGraphData.ts
Labels: filigran team

#6780 [frontend] Fix Translation in french for light theme is not correct (#6768)
  opencti-platform/opencti-front/lang/front/fr.json
Labels: filigran team

#6782 [frontend] Fix Relationships of observables are not correctly displayed (#6765)
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/Root.jsx
Labels: filigran team

#6781 [backend] created and modified attributes not available for observables (#6779)
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixMetaObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/schema/general.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/attribute-test.js
Labels: filigran team

#6030 [frontend/backend] Apply marking definition to export files (#5797)
  opencti-platform/opencti-front/.yarn/releases/yarn-4.1.1.cjs
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/AutocompleteField.jsx
  opencti-platform/opencti-front/src/private/components/common/files/FileExportViewer.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
  opencti-platform/opencti-front/src/private/components/common/form/ObjectMarkingField.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFileExport.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFilesAndHistory.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservablesExportCreation.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/markings/markingsFiltering.ts
  opencti-platform/opencti-front/src/utils/tests/markingsFiltering.test.ts
  opencti-platform/opencti-front/tests_e2e/Export file/exportReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/formExport.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/reportDetails.pageModel.ts
  opencti-platform/opencti-graphql/.yarn/releases/yarn-4.1.1.cjs
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/domain/work.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-domain.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document-types.ts
  opencti-platform/opencti-graphql/src/modules/internal/document/document.ts
  opencti-platform/opencti-graphql/src/modules/relationsRef/internalObject-registrationRef.ts
  opencti-platform/opencti-graphql/src/python/testing/local_exporter.py
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/resolvers/stixDomainObject.js
  opencti-platform/opencti-graphql/src/schema/general.js
  opencti-platform/opencti-graphql/src/schema/identifier.js
  opencti-platform/opencti-graphql/src/schema/stixMetaObject.ts
  opencti-platform/opencti-graphql/src/schema/stixRefRelationship.ts
  opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
Labels: filigran team

#6711 [backend/frontend] Logical deletion part 1.5 : apply acces restriction to trash items and add deletedBy filtering
  opencti-platform/opencti-front/src/private/components/trash/Trash.tsx
  opencti-platform/opencti-front/src/private/components/trash/all/DeleteOperationLine.tsx
  opencti-platform/opencti-front/src/private/components/trash/all/DeleteOperationPopover.tsx
  opencti-platform/opencti-front/src/private/components/trash/all/DeleteOperationsLines.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-converter.ts
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-domain.ts
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-types.ts
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation.graphql
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation.ts
  opencti-platform/opencti-graphql/src/schema/stixDomainObject.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/deleteOperation-test.ts
Labels: filigran team

#6513 [backend] Linked-to migration to related-to chunk1
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/utils/Colors.js
  opencti-platform/opencti-front/src/utils/Relation.ts
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/database/stix.ts
  opencti-platform/opencti-graphql/src/database/utils.js
  opencti-platform/opencti-graphql/src/domain/attribute-utils.ts
  opencti-platform/opencti-graphql/src/migrations/1713944533370-convert_linked-to_related-to.js
  opencti-platform/opencti-graphql/src/modules/relationsRef/stixCoreObject-registrationRef.ts
  opencti-platform/opencti-graphql/src/modules/relationsRef/stixCyberObservable-registrationRef.ts
  opencti-platform/opencti-graphql/src/modules/relationsRef/stixDomainObject-registrationRef.ts
  opencti-platform/opencti-graphql/src/schema/stixRefRelationship.ts
  opencti-platform/opencti-graphql/src/types/stix-common.d.ts
  opencti-platform/opencti-graphql/src/types/store.d.ts
Labels: filigran team

#6812 [backend] Fix restrict organization access capability name (#6809)
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/migrations/1714034457885-fix-knowledge-orga-restrict-capability-name.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/data-initialization-test.ts
Labels: filigran team

#6808 [frontend] test e2e with feature flags : override Drone config
  .drone.yml
Labels: filigran team

#6810 [frontend] tab attribution view displays participate-in relationship (#6787)
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignKnowledge.jsx
Labels: filigran team

#6747 [backend] update GQL API: names cannot be blank (#6742)
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceCreation.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/graphql/graphql.js
  opencti-platform/opencti-graphql/src/graphql/schema.js
  opencti-platform/opencti-graphql/src/modules/administrativeArea/administrativeArea.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rft/case-rft.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-template/case-template.graphql
  opencti-platform/opencti-graphql/src/modules/case/feedback/feedback.graphql
  opencti-platform/opencti-graphql/src/modules/channel/channel.graphql
  opencti-platform/opencti-graphql/src/modules/dataComponent/dataComponent.graphql
  opencti-platform/opencti-graphql/src/modules/dataSource/dataSource.graphql
  opencti-platform/opencti-graphql/src/modules/decayRule/decayRule.graphql
  opencti-platform/opencti-graphql/src/modules/event/event.graphql
  opencti-platform/opencti-graphql/src/modules/grouping/grouping.graphql
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-rss.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii.graphql
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper.graphql
  opencti-platform/opencti-graphql/src/modules/language/language.graphql
  opencti-platform/opencti-graphql/src/modules/narrative/narrative.graphql
  opencti-platform/opencti-graphql/src/modules/notification/notification.graphql
  opencti-platform/opencti-graphql/src/modules/notifier/notifier.graphql
  opencti-platform/opencti-graphql/src/modules/organization/organization.graphql
  opencti-platform/opencti-graphql/src/modules/playbook/playbook.graphql
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard.graphql
  opencti-platform/opencti-graphql/src/modules/task/task-template/task-template.graphql
  opencti-platform/opencti-graphql/src/modules/task/task.graphql
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.graphql
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary.graphql
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#6802 [backend] Add garbage collection manager (#1536)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/utils/platformModulesHelper.ts
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/manager/garbageCollectionManager.ts
  opencti-platform/opencti-graphql/src/manager/index.ts
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-domain.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
Labels: filigran team

#6710 [frontend] Control on markings (#6699)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/StixCoreObjectOrStixCoreRelationshipNotesCards.tsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/OpinionCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/CaseTaskCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TaskCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileToolbar.jsx
  opencti-platform/opencti-front/src/private/components/common/form/ObjectMarkingField.tsx
  opencti-platform/opencti-front/src/private/components/common/identities/IdentityCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFileExport.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFilesAndHistory.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationForm.js
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectsExportCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionRss/IngestionRssEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreationForm.js
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualCreation.tsx
Labels: filigran team

#6823 [frontend] Fix global search routes (#6820)
  opencti-platform/opencti-front/src/private/Index.tsx
  opencti-platform/opencti-front/src/private/components/RootSearch.tsx
  opencti-platform/opencti-front/src/private/components/search/SearchContainerQuery.tsx
Labels: filigran team

#6788 [backend] Fix parse_exception: request body is required (#6552)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#6840 [frontend] Fix OpenCTI doesn't have the same logo spacing on light and dark mode (#6827)
  opencti-platform/opencti-front/src/static/images/logo_text_light.png
Labels: filigran team

#6838 [frontend] Fix Impossible to add an override for a new user who doesn't have an initialized user confidence level. (#6837)
  opencti-platform/opencti-front/src/private/components/settings/users/edition/UserEditionConfidence.tsx
Labels: filigran team

#6853 [frontend] fix relationships widget filters (#6832)
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetFilters.tsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
Labels: filigran team, filters
