Repository OpenCTI-Platform/opencti, pull requests merged in 2024-02, with the labels that each got.

#5774 [frontend] fix user edition on fields other than confidence level (#5772)
  opencti-platform/opencti-front/src/private/components/settings/users/UserEditionOverview.tsx
Labels: filigran team

#5707 [frontend] improve the readability of connector names (#3154)
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorWorks.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorWorks.tsx
Labels: filigran team

#5404 [backend/frontend] Enable CSV Feed Ingester (#4569)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/AutocompleteField.jsx
  opencti-platform/opencti-front/src/components/DateTimePickerField.jsx
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/private/components/common/form/CreatorField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/CsvMapperField.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionMenu.tsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperForm.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvLine.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvLines.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvMapperTestDialog.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvPopover.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-front/src/utils/edition.js
  opencti-platform/opencti-graphql/graphql-codegen.yml
  opencti-platform/opencti-graphql/src/domain/work.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/index.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-converter.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-graphql.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-types.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-utils.ts
  opencti-platform/opencti-graphql/src/parser/csv-parser.ts
  opencti-platform/opencti-graphql/src/types/work.d.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-csv-test.ts
Labels: filigran team

#5780 [backend] Fix mailer / sending emails in the platform
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/modules/notifier/notifier-statics.ts
Labels: filigran team

#5782 [backend] Implement PingThread for each consumer thread in the worker (#5778)
  opencti-platform/opencti-graphql/src/python/runtime/snort/snort_dicts.py
  opencti-platform/opencti-graphql/src/python/runtime/stix2_create_pattern.py
  opencti-worker/src/worker.py
Labels: filigran team

#5784 [backend/frontend] Add missing search fields for activities + adapt line index to prevent collision (#5775)
  opencti-platform/opencti-front/src/components/list_cards/ListCardsContent.jsx
  opencti-platform/opencti-front/src/components/list_lines/ListLinesContent.jsx
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#5791 [backend] Refactor aws sdk to use the standard approach of the readme
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#5820 [backend] Indicators created with same name should not be deduplicated (#5819)
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.ts
Labels: filigran team

#5802 [backend/frontend] Introduce dev flags to deactivate feature in ongoing development
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/utils/platformModulesHelper.ts
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/test.json
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/manager/indicatorDecayManager.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-types.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.ts
Labels: architecture, filigran team

#5811 [frontend] fix filters on defaultValue in analyst workbench (#5810)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsLine.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityStixCoreObjectsLine.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsList.jsx
  opencti-platform/opencti-front/src/private/components/data/relationships/RelationshipsStixCoreRelationshipLine.jsx
  opencti-platform/opencti-front/src/private/components/search/SearchStixCoreObjectLine.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjectsLine.tsx
  opencti-platform/opencti-front/src/utils/Graph.js
  opencti-platform/opencti-front/src/utils/graph/EntityDetails.tsx
  opencti-platform/opencti-front/src/utils/graph/RelationShipFromAndTo.tsx
  opencti-platform/opencti-front/src/utils/graph/StixMetaObjectDetails.tsx
Labels: filigran team, filters

#5840 [frontend] fix MalwareAnalysis name display in relationships lists (#5816)
  opencti-platform/opencti-front/src/private/components/data/relationships/RelationshipsStixCoreRelationshipLine.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEntitiesLines.jsx
Labels: filigran team

#5834 [backend] 'reliability of author' filter with not_eq operator (#5833)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
Labels: filigran team, filters

#5846 [backend] add test coverage on indicator upsert issue (#5819).
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#5869 [frontend] Fixed remaining links from old /dashboard/data/connectors address to new /dashboard/data/ingestion/connectors
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
Labels: filigran team

#5866 [frontend] Added 'application/vnd.ms-excel' as an accepted MIME type in csv mapper
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperTestDialog.tsx
Labels: filigran team

#5851 [frontend] restrict entity_type filter options to Containers in the Analyses tab (5850)
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainers.jsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-front/src/utils/hooks/useAttributes.ts
Labels: filigran team, filters

#5847 [backend] Rename data sharing capability description (#5831)
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/migrations/1707487253148-rename-data-sharing-capability-description.js
Labels: filigran team

#5920 [backend] Improve deletion for large entities (#5803)
  opencti-platform/opencti-graphql/config/test.json
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/database/utils.js
  opencti-platform/opencti-graphql/src/manager/ruleManager.ts
  opencti-platform/opencti-graphql/src/migrations/1681899432316-roles_groups_missing.js
  opencti-platform/opencti-graphql/src/migrations/1694352490408-stream-access.js
  opencti-platform/opencti-graphql/src/rules/containerWithRefsBuilder.ts
  opencti-platform/opencti-graphql/src/types/event.d.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/05-rules/report-refs-observable-based-on-test.js
Labels: filigran team

#5936 [frontend] Added missing markdown handling in Role and Group description
  opencti-platform/opencti-front/src/private/components/settings/groups/Group.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/Role.tsx
Labels: filigran team

#5940 [backend] Rollback on anticipated activation
  opencti-platform/opencti-graphql/config/default.json
Labels: filigran team

#5946 [frontend] Fix data import redirect from workbench (#5805)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFilePopover.jsx
Labels: filigran team

#5937 [backend] Broken attack patterns matrix everywhere (#5841)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/config/providers.js
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/file-search.js
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/domain/stixRelationship.js
  opencti-platform/opencti-graphql/src/domain/work.js
Labels: filigran team

#5821 [backend/frontend] Add "From/To" attributes ref in sightings relationships(#5814)
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributeRefForm.tsx
  opencti-platform/opencti-graphql/src/domain/attribute-utils.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-domain.ts
Labels: filigran team

#5942 [backend] fix reverse relation (#5836)
  opencti-platform/opencti-graphql/src/modules/task/task-domain.ts
Labels: filigran team

#5959 [frontend] Systems display in BreadCrumbs
  opencti-platform/opencti-front/src/private/components/entities/Systems.tsx
Labels: filigran team

#5945 [frontend] Decay improvement: remove moment usage, remove zoom on chart (#2859)
  opencti-platform/opencti-front/src/components/i18n.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/DecayDialog.tsx
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayChart.tsx
Labels: filigran team

#5958 [backend] Introduce fuzzy search and wildcard prefix options
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
Labels: filigran team

#5949 [frontend] show right navigation menu when some manager are disabled.
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionRss.jsx
  opencti-platform/opencti-front/src/private/components/data/IngestionTaxiis.jsx
  opencti-platform/opencti-front/src/private/components/data/Sync.jsx
  opencti-platform/opencti-front/src/private/components/data/Tasks.jsx
  opencti-platform/opencti-front/src/private/components/settings/Retention.jsx
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
Labels: filigran team

#5962 [backend] Fixed issue with skip char line parameter in csv mapper (#5764)
  opencti-platform/opencti-graphql/src/parser/csv-bundler.ts
  opencti-platform/opencti-graphql/src/parser/csv-parser.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/csv-parser-test.js
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/simple-skip-line-test/Threat-Actor-Group_list_skip_double_quoted_data_line.csv
Labels: filigran team

#5975 [frontend] fix filters representation when filters with regardingOf (4974)
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
Labels: filigran team, filters

#5781 [frontend/backend] highlight selected filter
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/FilterValuesContent.tsx
  opencti-platform/opencti-front/src/components/TaskFilterValue.tsx
  opencti-platform/opencti-front/src/components/filters/DisplayFilterGroup.tsx
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/components/filters/FilterValues.tsx
  opencti-platform/opencti-front/src/components/filters/FiltersModel.ts
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/filters/SearchEntitiesUtil.ts
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team, filters

#5876 [backend/frontend] Organizations types to be in the vocabularies (#3470)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationDetails.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationDetails.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/SettingsOrganizations.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganizationDetails.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganizationEdition.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/migrations/1707916268729-vocabulary-add-organization-types.js
  opencti-platform/opencti-graphql/src/modules/organization/organization.ts
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary-types.ts
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary-utils.ts
  opencti-platform/opencti-graphql/src/modules/vocabulary/vocabulary.graphql
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/00-Raw/sync-raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/sync-utils.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#5931 [frontend] Not possible to empty CVSS score in vulnerabilities (#5808)
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionDetails.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionOverview.jsx
Labels: filigran team

#5332 [backend/frontend] Map with CSV mapper a file containing columns sha1, sha256, md5, sha-512 (#4806)
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/AttributeUtils.ts
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributeForm.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributeOptions.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributeRefForm.tsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributesForm.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-domain.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-types.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-utils.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper.graphql
  opencti-platform/opencti-graphql/src/parser/csv-bundler.ts
  opencti-platform/opencti-graphql/src/parser/csv-mapper.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/csv-mapper-utils-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/csvMapper-test.js
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/csv-mapper-test.js
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/mapper-area-malware.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/mapper-area-marking.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/representation-area.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/representation-individual.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/representation-killchainphase.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/representation-malware.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/representation-marking.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/default-values/representation-rel-targets.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/entities-with-booleans/mapper.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/files-hashes/data.csv
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/files-hashes/mapper-files.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/files-hashes/representation-file.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/real-use-case/csv-mapper-mock-real-use-case.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/simple-entity-test/csv-mapper-mock-simple-entity.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/simple-entity-with-ref-test/csv-mapper-mock-simple-entity-with-ref.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/simple-relationship-test/csv-mapper-mock-simple-relationship.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/simple-sighting-test/csv-mapper-mock-simple-sighting.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/simple-skip-line-test/csv-mapper-mock-simple-skip-line.ts
  opencti-platform/opencti-graphql/tests/data/csv-mapper-mock-simple-different-entities.ts
Labels: filigran team

#5633 [backend] manage long text filter like description and add search operator #4940
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/private/components/analyses/Reports.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
Labels: filigran team, filters

#5985 [backend] fix x_opencti_worfklow_id filter (5977)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team, filters

#5984 [frontend] fix CSV Feeds title in the breadcrumb
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
Labels: filigran team

#5988 [frontend] remove badge in the top bar trigger icon
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
Labels: filigran team

#5987 [frontend] remove column 'source' from task errors (#5885)
  opencti-platform/opencti-front/src/private/components/data/tasks/TasksList.jsx
Labels: filigran team

#5992 [frontend/backend] Multiple fixes on admin Orga (#5980, #5981, #5982,…
  opencti-platform/opencti-front/src/private/components/settings/AccessesMenu.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEditionGroups.jsx
  opencti-platform/opencti-graphql/src/domain/user.js
Labels: filigran team

#5994 [frontend] Fix subsector search
  opencti-platform/opencti-front/src/private/components/entities/sectors/AddSubSector.jsx
Labels: filigran team

#5948 [backend/frontend] update messages and translations for decay (#2859)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayRules.tsx
  opencti-platform/opencti-graphql/src/modules/decayRule/decayRule-domain.ts
Labels: filigran team

#5993 [backend] Fix orga sharing on Cases
  opencti-platform/opencti-graphql/src/schema/stixDomainObject.ts
Labels: filigran team

#5800 [backend] enforce user max confidence on create/delete/update/upsert (#5697)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectPopover.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/data/tasks/TasksList.jsx
  opencti-platform/opencti-front/src/relay/environment.jsx
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/utils/confidence-level.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/confidence-level-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/taxii-filtering-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/00-Raw/sync-raw-test.js
  opencti-platform/opencti-graphql/tests/05-rules/located-at-located-test.js
  opencti-platform/opencti-graphql/tests/05-rules/observe-sighting-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-worker/src/worker.py
Labels: filigran team

#5978 [frontend] Align Nested Object panel with other in the platform (#4931)
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectNestedEntities.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntityLine.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntityLines.jsx
Labels: filigran team

#5979 [frontend/backend] Verify access to csv mapper in UI and API (#5954)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/setup-relay-for-vitest.ts
  opencti-platform/opencti-front/src/app.test.tsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessagesBanner.test.tsx
  opencti-platform/opencti-front/src/utils/Security.test.tsx
  opencti-platform/opencti-front/vitest.config.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper.graphql
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-csv-test.ts
Labels: filigran team

#6007 [frontend] Fixes on label creation/deletion and user breadcrumb
  opencti-platform/opencti-front/src/private/components/settings/labels/LabelsLines.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/Root.jsx
  opencti-platform/opencti-front/src/utils/store.js
Labels: filigran team

#5964 [backend/frontend] remove 'remove' operation from playbook (#5950)
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team

#6008 [backend] enable local mode switching for nested relation filters (#6001)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team, filters

#6006 [Backend] Enrich model to add update attribute protection
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/modules/attributes/basicRelationship-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/schema/attribute-definition.ts
  opencti-platform/opencti-graphql/src/schema/schema-validator.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
Labels: filigran team

#6011 [frontend] Fix malware analyses unknown display
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/Root.tsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-graphql/src/database/entity-representative.js
Labels: filigran team

#6029 [backend] Improve batch loading error control and deletion capabilities
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
Labels: filigran team

#5613 [backend] extends Audits context filters to Knowledge events (#5611)
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/listener/UserActionListener.ts
  opencti-platform/opencti-graphql/src/manager/historyManager.ts
  opencti-platform/opencti-graphql/src/types/stix-common.d.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/listener-test.ts
Labels: filigran team, filters

#6033 [backend/frontend] user's confidence level shall be the highest among user's group(s)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserConfidenceLevel.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserConfidenceLevelField.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEditionOverview.tsx
  opencti-platform/opencti-graphql/src/utils/confidence-level.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/confidence-level-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
Labels: filigran team

#5555 [frontend] Add playwright
  .drone.yml
  opencti-platform/opencti-front/.eslintrc.js
  opencti-platform/opencti-front/.gitignore
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/playwright.config.ts
  opencti-platform/opencti-front/src/private/components/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/analyses/Reports.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.jsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/public/components/Login.tsx
  opencti-platform/opencti-front/tests_e2e/auth.setup.ts
  opencti-platform/opencti-front/tests_e2e/fixtures/baseFixtures.ts
  opencti-platform/opencti-front/tests_e2e/logout.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboard.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/login.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/menu/topMenuProfile.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/report.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/reportDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/reportForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/settings.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/report/createReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/report/deleteReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/report/updateReport.spec.ts
  opencti-platform/opencti-front/vite.config.mts
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#6038 [frontend] Fix creation page + align CSV Mapper option panel
  opencti-platform/opencti-front/src/components/AutocompleteField.jsx
  opencti-platform/opencti-front/src/components/AutocompleteFreeSoloField.jsx
  opencti-platform/opencti-front/src/components/ColorPickerField.jsx
  opencti-platform/opencti-front/src/components/DateTimePickerField.jsx
  opencti-platform/opencti-front/src/components/MarkdownField.jsx
  opencti-platform/opencti-front/src/components/RichTextField.jsx
  opencti-platform/opencti-front/src/components/SelectField.jsx
  opencti-platform/opencti-front/src/components/SimpleMarkdownField.jsx
  opencti-platform/opencti-front/src/components/SimpleTextField.jsx
  opencti-platform/opencti-front/src/components/SliderField.jsx
  opencti-platform/opencti-front/src/components/SwitchField.jsx
  opencti-platform/opencti-front/src/components/TextField.jsx
  opencti-platform/opencti-front/src/components/TimePickerField.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectContent.jsx
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributeOptions.tsx
Labels: filigran team

#6039 [backend/frontend] In Dashboard Network Traffic Attribute Fields Returning Nothing (#5473)
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsDistributionList.jsx
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
Labels: filigran team

#6002 [frontend] Fix quick subcription button(#5963)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectQuickSubscriptionContent.tsx
Labels: filigran team

#6004 [backend/frontend] Indicator decay rules improvements (#2859)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/form/DefaultValueField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/ObservableTypesField.tsx
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayRule.tsx
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayRuleCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayRuleEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayRuleValidator.ts
  opencti-platform/opencti-graphql/src/modules/decayRule/decayRule-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/decayRule-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/decayRule-test.ts
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
Labels: filigran team

#6040 [frontend] Fix names truncated when exporting a Radar widget as CSV(#5969)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationshipsHorizontalBars.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsHorizontalBars.jsx
  opencti-platform/opencti-front/src/utils/Charts.js
Labels: filigran team

#6055 [frontend] use of istanbul plugin dynamic
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/vite.config.mts
Labels: filigran team

#6057 [test] First tests on navigation and parameters
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/playwright.config.ts
  opencti-platform/opencti-front/src/components/Breadcrumbs.tsx
  opencti-platform/opencti-front/src/private/components/cases/CaseIncidents.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/tests_e2e/fixtures/baseFixtures.ts
  opencti-platform/opencti-front/tests_e2e/general/navigation.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/menu/leftBar.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/report.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/report/createReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/settings/parameters.spec.ts
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#6064 [backend/frontend] entity_type filter available for abstract types
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-front/tests_e2e/filters/addFilter.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/filters.pageModel.ts
  opencti-platform/opencti-graphql/src/domain/filterKeysSchema.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/filterKeysSchema-test.ts
Labels: filigran team, filters

#6058 [backend/frontend] Fix malware analyses pagination error on submission date if null (#6054)
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisEditionOverview.tsx
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
Labels: filigran team

#6078 [backend] Fix of creation with associated file in entities
  opencti-platform/opencti-front/tests_e2e/general/navigation.spec.ts
  opencti-platform/opencti-front/tests_e2e/report/createReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/report/updateReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/settings/parameters.spec.ts
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#6051 [backend] Update taskManager to handle extension attributes from toolbar actions
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/schema/schema-validator.ts
Labels: filigran team

#6067 [frontend/backend] extends widget filters and fix relationship_type filter in widgets (#6065)
  opencti-platform/opencti-front/src/private/components/common/lists/ListFilters.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetFilters.tsx
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-test.js
Labels: filigran team, filters

#6084 [frontend] fix limit results to display correlation view (#5996)
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeCorrelation.jsx
Labels: filigran team

#6092 [frontend] fix trigger filters not aligned
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
Labels: filigran team

#6095 [frontend] fix empty source entity filters list in relationship widget
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetFilters.tsx
Labels: filigran team, filters

#6096 [frontend] new filters UI in Playbooks (#6094)
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
Labels: filigran team, filters

#6097 [frontend] fix filter operator size
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
Labels: filigran team, filters

#6091 [backend] includes 'object' relationship in Number widgets (#6089)
  opencti-platform/opencti-graphql/src/domain/stixRelationship.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixRelationship-test.ts
Labels: filigran team, filters

#6073 [backend] Fix observables query for network traffic with dst_port (#6070)
  opencti-platform/opencti-graphql/src/utils/format.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixCyberObservable-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#6098 [backend] inferred data always have the Rule Manager's confidence (#6093)
  opencti-platform/opencti-graphql/src/rules/rules-utils.js
  opencti-platform/opencti-graphql/tests/05-rules/attribution-merge-test.js
  opencti-platform/opencti-graphql/tests/05-rules/attribution-use-test.js
  opencti-platform/opencti-graphql/tests/05-rules/located-at-located-test.js
  opencti-platform/opencti-graphql/tests/05-rules/observe-sighting-test.js
Labels: filigran team

#6103 [backend] Add OpenID proxy configuration capability
  opencti-platform/opencti-graphql/src/config/providers.js
Labels: filigran team

#6105 [backend] Creating a user with a group is bypassing default group belonging (#6104)
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/group-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.js
Labels: filigran team

#6116 [frontend] fix spacing issue
  opencti-platform/opencti-front/src/utils/Graph.js
Labels: filigran team

#6035 [frontend] fix bad behaviour onBlur Markdown fields (#5943)
  opencti-platform/opencti-front/src/components/MarkdownField.jsx
Labels: filigran team

#6118 [frontend] fix incorrect explanatory text about users and default groups
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/users/UserCreation.jsx
Labels: filigran team

#6123 [frontend] fix tasks losing filters before start
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team, filters

#6090 [frontend] Fix error message when attempting to create an artifact without file (#6052)
  opencti-platform/opencti-front/src/private/components/common/files/CustomFileUploader.tsx
  opencti-platform/opencti-front/src/private/components/observations/Artifacts.tsx
  opencti-platform/opencti-front/src/private/components/observations/artifacts/ArtifactCreation.jsx
  opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/Artifact.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx
Labels: filigran team

#6088 [frontend] Improve playwright process
  .drone.yml
  opencti-platform/opencti-front/builder/dev/dev.js
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/playwright.config.ts
  opencti-platform/opencti-front/tests_e2e/fixtures/baseFixtures.js
  opencti-platform/opencti-front/tests_e2e/fixtures/baseFixtures.ts
  opencti-platform/opencti-front/vite.config.mts
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#6130 [frontend] Fix red color issue(#6117)
  opencti-platform/opencti-front/src/private/components/common/form/GroupField.tsx
Labels: filigran team

#6128 [frontend] fix position of ai button
  opencti-platform/opencti-front/src/private/components/common/form/TextFieldAskAI.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectContent.jsx
Labels: filigran team

#6127 [frontend] fix display confidence initial value
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationEditionOverview.tsx
Labels: filigran team

#6069 [backend] Based on relationship should inherit markings & restrictions when created from Indicators or observables (#6068)
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team

#6136 [frontend] add eslint config to e2e tests
  opencti-platform/opencti-front/.eslintrc.js
  opencti-platform/opencti-front/tests_e2e/artifact/createArtifact.spec.ts
  opencti-platform/opencti-front/tests_e2e/auth.setup.ts
  opencti-platform/opencti-front/tests_e2e/filters/addFilter.spec.ts
  opencti-platform/opencti-front/tests_e2e/fixtures/baseFixtures.js
  opencti-platform/opencti-front/tests_e2e/general/navigation.spec.ts
  opencti-platform/opencti-front/tests_e2e/logout.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/Artifact.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/ArtifactImport.pageModel.tsx
  opencti-platform/opencti-front/tests_e2e/model/dashboard.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/filters.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/login.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/menu/leftBar.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/menu/topMenuProfile.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/report.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/reportDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/reportForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/settings.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/report/createReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/report/deleteReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/report/updateReport.spec.ts
  opencti-platform/opencti-front/tests_e2e/settings/entitySettings.spec.ts
  opencti-platform/opencti-front/tests_e2e/settings/parameters.spec.ts
  opencti-platform/opencti-front/tsconfig.json
Labels: filigran team

#6139 [backend] fix workflow_id throw error
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#6124 [frontend] fix creator filter in user history redirection
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistory.tsx
Labels: filigran team, filters

#6086 [frontend/backend] add filters based on schema definition in the Add entities panels
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjects.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjects.jsx
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis.ts
Labels: filigran team, filters

#6144 [frontend] Linter fix v2 (#5963)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectQuickSubscription.tsx
Labels: filigran team

#6080 Prevent input name collision with db name for refs (#6056)
  .drone.yml
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableMalwareAnalyses.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/stix-converter.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis-types.ts
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis.graphql
  opencti-platform/opencti-graphql/src/schema/identifier.js
  opencti-platform/opencti-graphql/src/schema/schema-relationsRef.ts
  opencti-platform/opencti-graphql/src/schema/stixRefRelationship.ts
  opencti-platform/opencti-graphql/src/types/store.d.ts
  opencti-platform/opencti-graphql/tests/01-unit/database/modelConsistency-test.js
Labels: filigran team

#6101 [backend] Organization sharing behavior change for upsert and enrichment
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/enrichment.js
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/modules/administrativeArea/administrativeArea.graphql
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rft/case-rft.graphql
  opencti-platform/opencti-graphql/src/modules/case/case.graphql
  opencti-platform/opencti-graphql/src/modules/case/feedback/feedback.graphql
  opencti-platform/opencti-graphql/src/modules/channel/channel.graphql
  opencti-platform/opencti-graphql/src/modules/dataComponent/dataComponent.graphql
  opencti-platform/opencti-graphql/src/modules/dataSource/dataSource.graphql
  opencti-platform/opencti-graphql/src/modules/event/event.graphql
  opencti-platform/opencti-graphql/src/modules/grouping/grouping.graphql
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.graphql
  opencti-platform/opencti-graphql/src/modules/language/language.graphql
  opencti-platform/opencti-graphql/src/modules/malwareAnalysis/malwareAnalysis.graphql
  opencti-platform/opencti-graphql/src/modules/narrative/narrative.graphql
  opencti-platform/opencti-graphql/src/modules/organization/organization.graphql
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
  opencti-platform/opencti-graphql/src/modules/task/task.graphql
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.graphql
  opencti-platform/opencti-graphql/src/resolvers/stix.js
  opencti-platform/opencti-graphql/src/schema/stixDomainObject.ts
Labels: filigran team

#6147 [backend] Infinite upload when two platforms synchronize on each other
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/externalReference.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
  opencti-platform/opencti-graphql/src/resolvers/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/resolvers/stixDomainObject.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/index-file-test.js
Labels: filigran team

#6063 [frontend] Cannot add tag to a dashboard/investigation (#5861)
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Workspaces.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Root.jsx
  opencti-platform/opencti-front/tests_e2e/dashboard/createDashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/dashboard/updateDashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboard.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboardDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboardForm.pageModel.ts
Labels: filigran team

#6142 [backend] Fix validation and schema for ThreatActors
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.ts
  opencti-platform/opencti-graphql/src/schema/schema-validator.ts
Labels: filigran team

#6148 [backend] Handle revoked input for Indicators without valid_until date (#6099)
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-utils.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/indicator-test.ts
Labels: filigran team

#6100 [backend] Fix upsert indicator score since decay (#2859)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/observations/indicators/DecayDialog.tsx
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayChart.tsx
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/manager/indicatorDecayManager.ts
  opencti-platform/opencti-graphql/src/modules/decayRule/decayRule-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/decayRule-test.ts
Labels: filigran team

#6150 [backend] Fix carousel for TA
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/threatActorIndividual/threatActorIndividual.ts
Labels: filigran team

#6151 [backend] Improve csv feed
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvLine.tsx
  opencti-platform/opencti-graphql/src/parser/csv-bundler.ts
  opencti-platform/opencti-graphql/src/parser/csv-parser.ts
Labels: filigran team

#6153 [frontend] Fix broken screen from localStorage error
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjects.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjects.jsx
Labels: filigran team

#6152 [frontend] fix content mapping view
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjects.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjects.jsx
Labels: filigran team

#6157 [backend] add missing capa for effective level computation
  opencti-platform/opencti-graphql/src/domain/user.js
Labels: filigran team

#6155 [frontend] Fix fetch of containers in workspace
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceTurnToContainerDialog.tsx
  opencti-platform/opencti-front/tests_e2e/settings/parameters.spec.ts
Labels: filigran team

#6173 [frontend] Fix on perf issue
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectHeader.jsx
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/python/requirements.txt
  opencti-worker/src/requirements.txt
Labels: filigran team

#6168 [frontend] fix breadcrumbs (#6164)
  opencti-platform/opencti-front/src/private/components/cases/Feedbacks.tsx
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayRules.tsx
Labels: filigran team
