Repository OpenCTI-Platform/opencti, pull requests merged in 2024-03, with the labels that each got.

#6180 [backend/frontend] fix creator replaced by user in workbench (#6048)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-graphql/src/database/file-storage.js
Labels: filigran team

#6184 [backend] Fix dashboard import minimal version check (#6181)
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
  opencti-platform/opencti-graphql/src/utils/version.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/version-test.ts
Labels: filigran team

#6195 [backend] fix filter key 'objects', usable in any sro and sco (#6188)
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-graphql/src/domain/filterKeysSchema.ts
Labels: filigran team

#6194 [frontend] Fix localStorage useless method
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-front/src/utils/utils.ts
Labels: filigran team

#6199 Fix on instance trigger incorrect message when updating the standard Id
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-resolution.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-stix/stix-testers.ts
  opencti-platform/opencti-graphql/tests/01-unit/database/stix-filtering-testers-test.ts
Labels: filigran team

#6202 [frontend] Fix pagination Options for SDO creation in container
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjects.jsx
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectsField.jsx
Labels: filigran team

#6209 [frontend] Clear search input on click clearFilters button
  opencti-platform/opencti-front/src/components/SearchInput.jsx
Labels: filigran team

#6207 [backend] Add path resolution in filtering
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-resolution.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-stix/stix-testers.ts
Labels: filigran team

#6160 [frontend/backend] Add PAP at init + fix leftbar
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/marking-definition-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/markingDefinition-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#6271 [backend] Generate observables/indicators for all objects in bundle (#6266)
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team

#6269 [frontend] fix entity type filter right bar in containers (#6268)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjects.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjects.tsx
  opencti-platform/opencti-front/src/private/components/observations/Indicators.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorsRightBar.tsx
Labels: filigran team, filters

#6159 [frontend] fix content mapping view
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjects.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjects.jsx
Labels: filigran team

#6286 [frontend] add System in author update via background task (#6282)
  opencti-platform/opencti-front/src/private/components/common/identities/IdentityCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#6300 [frontend] harmonise the size of dashboard icons (#6296)
  opencti-platform/opencti-front/src/private/components/DashboardSettings.jsx
Labels: filigran team

#5796 [backend] extend our vitest config for easier dev process
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/tests/02-integration/00-inject/loader-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/05-parser/csv-mapper-test.js
  opencti-platform/opencti-graphql/tests/utils/globalSetup.js
  opencti-platform/opencti-graphql/tests/utils/globalSetup.ts
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
  opencti-platform/opencti-graphql/vitest.config.test.ts
Labels: filigran team

#6046 [backend] validate elUpdateElement input value against schema before indexing (#5696)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/modules/internal/document/document.ts
  opencti-platform/opencti-graphql/src/schema/attribute-definition.ts
  opencti-platform/opencti-graphql/src/schema/schema-attributes.ts
  opencti-platform/opencti-graphql/src/schema/schema-validator.ts
  opencti-platform/opencti-graphql/src/types/store.d.ts
  opencti-platform/opencti-graphql/tests/01-unit/database/validateDataBeforeIndexing-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/group-test.js
Labels: filigran team

#6289 [frontend] horizontal bars representing labels should not be clickable
  opencti-platform/opencti-front/src/utils/Charts.js
Labels: filigran team

#6299 [frontend] dont disable when value > limit (#6294)
  opencti-platform/opencti-front/src/components/InputSliderField.tsx
Labels: filigran team

#6317 [frontend] Fix instance triggers subscription (#6313)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectQuickSubscription.tsx
Labels: filigran team

#6272 [frontend] Fix cannot add TTP directly from matrix (#6112)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
Labels: filigran team

#6331 [frontend] Fix mass selection with the shift key in incidents container (#6283)
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentLine.tsx
Labels: filigran team

#6309 [backend]Verify createdBy type on malware creation (#6291)
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/domain/stixObjectOrStixRelationship.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/malware-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/malware-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#6305 [frontend] fix history filters in activity tab (#6293)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx
  opencti-platform/opencti-graphql/src/schema/attribute-definition.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/filterKeysSchema-test.ts
Labels: filigran team

#6336 [frontend] allow all relationship types in 'in regards of' filter (#6335)
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/utils/filters/SearchEntitiesUtil.ts
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
Labels: filigran team, filters

#6339 [frontend] fix FR translations
  opencti-platform/opencti-front/lang/front/fr.json
Labels: filigran team

#6338 [frontend] fix bulk edition field changing (#6334)
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#6333 [frontend] increase and sort values in bulk update lists (#6326)
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
Labels: filigran team

#6340 [frontend] Fix Data > Ingestion and Processing menus access (#6312) (#6328) (#6329)
  opencti-platform/opencti-front/src/private/components/data/IngestionMenu.tsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
Labels: filigran team

#6352 [backend] fix targetEntity and sourceEntity filters (#6350)
  opencti-platform/opencti-graphql/src/modules/attributes/basicRelationship-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixCoreRelationship-registrationAttributes.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/filterKeysSchema-test.ts
Labels: filigran team, filters

#6349 [frontend] fix filters adding for TimeLine views, Alert Live, and label icon (#6348)
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainertKnowledgeTimeLineBar.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/Filters.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/alerting/AlertLiveCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/alerting/AlertLiveEdition.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
Labels: filigran team, filters

#6367 [frontend] improve e2e tests (#6343)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/tests_e2e/intrusionSet/createIntrusionSetRelationship.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/intrusionSetDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/stixCoreRelationshipCreationFromEntityForm.pageModel.ts
Labels: filigran team

#6394 [backend] Fix search broken in kill chain phases and marking definition (#6308 & #6318)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#6376 [frontend] Fix Files search EE button not aligned (#6346)
  opencti-platform/opencti-front/src/components/SearchInput.jsx
  opencti-platform/opencti-front/src/private/components/SearchRoot.tsx
Labels: filigran team

#6203 [backend] Fix connectors work cleanup perf (#6031)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/manager/connectorManager.js
Labels: filigran team

#6337 [backend] Add samples attribute to Malware in API
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/malware.js
Labels: filigran team

#6330 [backend] fix workflow filter with not_eq operator (#6307)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
Labels: filigran team, filters

#6366 [backend] Update errors that are not retryable
  opencti-platform/opencti-graphql/src/config/errors.js
  opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js
Labels: filigran team

#6387 [backend] Improve bulk Stix loader to support 100K+ relations loading in one bulk (#6386)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#6398 [backend] during boot: add try/catch at each step to improve debug (#4090)
  opencti-platform/opencti-graphql/src/boot.js
Labels: community

#6402 [backend] Fix Promote observable component crashes (#6399)
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team

#6395 [backend/frontend] fromOrTo relations filters with different operators/modes combinations (#6390)
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectThreatKnowledge.tsx
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/modules/attributes/basicRelationship-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixCoreRelationship-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/filterKeysSchema-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
Labels: filigran team, filters

#6414 [frontend] remove duplicate header (#6401)
  opencti-platform/opencti-front/src/private/components/entities/events/EventKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/Root.jsx
Labels: filigran team

#6413 [frontend] Fix filtering for toolbar
  opencti-platform/opencti-front/src/components/TasksFilterValueContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsRelationshipsView.tsx
  opencti-platform/opencti-front/src/private/components/data/Relationships.tsx
  opencti-platform/opencti-front/src/private/components/data/ToolBar.jsx
  opencti-platform/opencti-front/src/private/components/data/tasks/TasksList.jsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationsToolBar.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team

#6419 implement route 'infra / knowledge / incident' (#6415)
  opencti-platform/opencti-front/src/private/components/locations/positions/Root.jsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/Root.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/Root.jsx
Labels: filigran team

#6451 [backend/frontend] Connector page in GUI not available after proxy set up (#6185)
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvMapperTestDialog.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiLine.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
  opencti-platform/opencti-graphql/src/domain/connector.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-types.ts
  opencti-platform/opencti-graphql/src/utils/http-client.ts
Labels: filigran team

#6466 [frontend] fix widgets number alignment on default dashboard (#6412)
  opencti-platform/opencti-front/src/private/components/Dashboard.jsx
Labels: filigran team

#6371 [frontend/backend] Cannot hide entity type "External references" (#6327)
  opencti-platform/opencti-front/src/private/components/settings/hidden_types/HiddenTypesField.tsx
  opencti-platform/opencti-front/tests_e2e/auth.setup.ts
  opencti-platform/opencti-front/tests_e2e/settings/entitySettings.spec.ts
  opencti-platform/opencti-front/tests_e2e/settings/parameters.spec.ts
  opencti-platform/opencti-graphql/src/domain/subType.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-utils.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/entitySetting-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/subType-test.js
Labels: filigran team

#6397 [frontend] add entity_type filter in Victimology tab (#6391)
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
  opencti-platform/opencti-front/src/private/components/common/lists/ListFilters.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectVictimology.jsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/src/modules/relationsRef/stixDomainObject-registrationRef.ts
Labels: filigran team, filters

#6467 [backend] Fix error deleting a file from a data tab (#6389)
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
Labels: filigran team

#6469 [frontend] use good StixType for Infrastucture link (#6400)
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureKnowledge.tsx
Labels: filigran team

#6489 [backend] Allow passwords with digits only for initial admin (#6382)
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/providers-test.ts
Labels: filigran team

#6504 Revert "Replace dependency passport-saml with @node-saml/passport-saml 4.0.4"
  opencti-platform/opencti-dev/docker-compose.yml
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/config/providers.js
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team, critical

#6178 [frontend] Add Playwright teams webhook
  .drone.yml
  opencti-platform/opencti-front/playwright.config.ts
  opencti-platform/opencti-front/tests_e2e/webhooks/teams-webhook.js
Labels: filigran team

#6512 [frontend] fix redirection link to entity for WidgetDistributionList (#6490)
  opencti-platform/opencti-front/src/components/dashboard/WidgetDistributionList.tsx
Labels: filigran team

#6491 [frontend] fix remove relation ref from Grouping Knowledge graph (#6482)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphQuery.js
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraphQuery.js
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphQuery.js
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphQuery.js
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphQuery.js
  opencti-platform/opencti-front/src/private/components/common/containers/KnowledgeGraphQuery.tsx
Labels: filigran team

#6511 [frontend] hide create widget button for read-only dashboard (#6464)
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
Labels: filigran team

#6420 'in regards of' filter display in background tasks
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/TaskFilterValue.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: filigran team, filters

#6487 [frontend] Fix date attribute for list and timeLine widgets (#6145)
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsTimeline.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
Labels: filigran team

#6473 [backend] Improve config restrictions / visibility for batch rel loading
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorWorks.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#6341 [frontend] Added auto collapse and submenu icon switches to settings
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/tests_e2e/model/menu/leftBar.pageModel.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/resolvers/user.js
Labels: community
