Repository OpenCTI-Platform/opencti, pull requests merged in 2025-01, with the labels that each got.

#9465 [frontend] Improve the Apply buttons in Suggestions (#9291)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsSuggestions.jsx
Labels: filigran team

#9476 [frontend] chosen value still displayed on click away (#8983)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#9478 Fix grammar in the French file
  opencti-platform/opencti-front/lang/front/fr.json
Labels: community

#9480 [CI] Add a test-result folder in backend to help debug stream count issues.
  .drone.yml
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/03-streams/01-Live/live-test.js
  opencti-platform/opencti-graphql/tests/utils/testOutput.ts
Labels: filigran team

#9471 [backend/frontend] Introduce TAXII push endpoints
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/IngestionMenu.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionTaxiiCollections.jsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxiiCollection/IngestionTaxiiCollectionCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxiiCollection/IngestionTaxiiCollectionEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxiiCollection/IngestionTaxiiCollectionLine.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxiiCollection/IngestionTaxiiCollectionLines.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxiiCollection/IngestionTaxiiCollectionPopover.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/domain/connector.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/http/httpTaxii.js
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/index.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-converter.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-collection-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-collection-graphql.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-collection-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-collection.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-collection.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-types.ts
Labels: filigran team

#9467 [backend] logout URL missing for Auth0 strategy (#9466)
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/config/providers.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#9474 [frontend] Fix loading issue when exporting as an image or PDF in the opposite theme mode (#9231 #9011)
  opencti-platform/opencti-front/src/components/ExportButtons.jsx
Labels: filigran team

#9494 Revert "Update dependency react-pdf to v9.2.1"
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#9248 [backend] filter notifications by trigger (#7309)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/src/private/components/profile/Notifications.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationLine.tsx
  opencti-platform/opencti-front/src/private/components/profile/triggers/TriggersQueries.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-domain.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-resolver.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-types.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification.graphql
  opencti-platform/opencti-graphql/src/modules/notification/notification.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/trigger-test.js
Labels: filigran team

#9312 [frontend/backend] Remove authorized members action on Restricted entities view - chunk 2
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/data/Management.tsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/src/utils/authorizedMembers.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/taskManager-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#9256 [frontend] Improve work errors parsing. (#9233)
  opencti-platform/opencti-front/src/private/components/data/connectors/parseWorkErrors.tsx
Labels: filigran team

#9502 [frontend] enroll playbook translations (#9473)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectEnrollPlaybook.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectEnrollPlaybookLines.jsx
Labels: filigran team

#9501 [frontend] Delete background task for Playbooks (#9500)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/data/Playbooks.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#9455 [backend] fix file access restriction to also target trash index (#9424)
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/python/testing/local_exporter.py
  opencti-platform/opencti-graphql/src/python/testing/local_uploader.py
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/deleteOperation-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#9507 [frontend] fix `Network-Traffic` name in workbench observables list (#9506)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
Labels: filigran team

#9475 [backend] Domain Name Creation Error (#9457)
  opencti-platform/opencti-graphql/src/utils/syntax.js
  opencti-platform/opencti-graphql/tests/01-unit/utils/syntax-test.ts
Labels: filigran team

#9399 [backend/frontend] [Playbook] Modify severity field with playbooks (#7648)
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team, multi-repository

#9510 [backend] Add static mime resolution for custom files extension upload
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/file-storage.js
Labels: filigran team

#9505 [frontend] In custom dashboard list, the call to action hover effect is semi-hidden (#8534)
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceCreation.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceDuplicationDialog.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceLine.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Workspaces.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacesLines.tsx
Labels: filigran team

#9495 [frontend] scos list updated (#8941)
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListUtils.ts
Labels: filigran team

#9498 [frontend] add missing `Task`/`Report`/`Grouping`/`Malware Analysis` in knowledge > related entities (#9497)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationshipLineAll.jsx
Labels: filigran team

#9483 [frontend] Widgets code refacto
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/widgets/WidgetConfig.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationDataSelection.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationParameters.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationPerspective.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationTypes.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetFilters.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetText.jsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetUpsert.tsx
  opencti-platform/opencti-front/src/private/components/widgets/widgetExportHandler.tsx
  opencti-platform/opencti-front/src/private/components/widgets/widgetUtils.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfig.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WorkspaceWidgetConfig.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WorkspaceWidgetPopover.jsx
  opencti-platform/opencti-front/src/public/components/PublicDashboard.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/usePublicDashboardWidgets.tsx
  opencti-platform/opencti-front/src/utils/filters/useFiltersState.tsx
  opencti-platform/opencti-front/src/utils/widget/widget.d.ts
  opencti-platform/opencti-front/tests_e2e/model/DashboardWidgets.pageModel.ts
Labels: filigran team

#9486 [frontend] fix Sightings tab under Observables and Indicators (#8814)
  opencti-platform/opencti-front/src/private/components/observations/indicators/Root.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/Root.tsx
Labels: filigran team

#9513 [backend] Move specific case inside the config + unit tests (#9509)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
Labels: filigran team

#9213 [frontend] Make markdown content "preview" by default
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContent.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectMappableContent.tsx
Labels: filigran team

#9316 [frontend] Add enroll/enrich to note & grouping popover menu (#9217)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingPopover.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NotePopover.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/Root.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectEnrollPlaybook.jsx
Labels: filigran team

#9535 [frontend] display creators in Intrusion set list (#9534)
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetCard.tsx
Labels: filigran team

#9528 [frontend] sort groups in user creation form (#9273)
  opencti-platform/opencti-front/src/private/components/common/form/GroupField.tsx
Labels: filigran team

#9544 [backend] Build and push docker images in ghcr.io
  .circleci/config.yml
Labels: filigran team

#9519 [frontend] add hover effect on datatables rows
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
Labels: filigran team

#9553 [backend] Ensure log lines would be efficiently streamed to log visualization tools (#4199)
  opencti-platform/opencti-graphql/src/boot.js
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/config/providers.js
  opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/migration.js
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/domain/retentionRule.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/domain/work.js
  opencti-platform/opencti-graphql/src/graphql/graphql.js
  opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/http/httpServer.js
  opencti-platform/opencti-graphql/src/listener/supportPackageListener.ts
  opencti-platform/opencti-graphql/src/manager/activityManager.ts
  opencti-platform/opencti-graphql/src/manager/connectorManager.js
  opencti-platform/opencti-graphql/src/manager/expiredManager.js
  opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
  opencti-platform/opencti-graphql/src/manager/garbageCollectionManager.ts
  opencti-platform/opencti-graphql/src/manager/historyManager.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/manager/managerModule.ts
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/manager/playbookManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/manager/retentionManager.ts
  opencti-platform/opencti-graphql/src/manager/ruleManager.ts
  opencti-platform/opencti-graphql/src/manager/syncManager.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/modules/xtm/xtm-domain.js
  opencti-platform/opencti-graphql/src/parser/csv-bundler.ts
  opencti-platform/opencti-graphql/src/python/pythonBridge.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/tests/01-unit/utils/logger-test.ts
Labels: filigran team

#9551 [frontend] Error when accessing the Observables tab in a workbench (#9543)
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
Labels: filigran team

#9557 [backend] Fix auth0 provider for env variable (#9554)
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/config/providers.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/tests/01-unit/utils/logger-test.ts
Labels: filigran team

#9571 [frontend] translations added (#8941)
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListUtils.ts
Labels: filigran team

#9555 [backend] keep increasing back pressure delay if queue size keeps increasing (#9358)
  opencti-platform/opencti-graphql/src/manager/syncManager.js
Labels: filigran team

#9527 [frontend] Enable the ordering in Observables / nested objects panel (#9280)
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
Labels: filigran team

#9524 [frontend] Logout button miss placed if connected user as no knowledge capability (#9428)
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
Labels: filigran team

#9574 [backend] fix capability check on feeds (#9573)
  opencti-platform/opencti-graphql/src/http/httpRollingFeed.ts
  opencti-platform/opencti-graphql/src/http/httpTaxii.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/csvFeed-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.ts
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#9592 [frontend] sync icon and translations (#8941)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListsStatus.tsx
Labels: filigran team

#9218 [backend] fix internal_id being removed during observable fullsync (#8986)
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
Labels: filigran team

#9230 [frontend] Preview on correlated case (#3227)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dashboard/WidgetHorizontalBars.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingDetails.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportDetails.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentDetails.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiDetails.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftDetails.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/RelatedContainers.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/related_containers/RelatedContainers.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/related_containers/RelatedContainersDetails.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/related_containers/RelatedContainersDetailsTable.tsx
  opencti-platform/opencti-front/src/utils/Charts.js
Labels: filigran team

#9609 [backend/frontend] Introduce EE license mechanism
  .drone.yml
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemBoolean.jsx
  opencti-platform/opencti-front/src/components/Loader.tsx
  opencti-platform/opencti-front/src/private/Analytics.tsx
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EnterpriseEditionAgreement.tsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EnterpriseEditionButton.tsx
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/Settings.jsx
  opencti-platform/opencti-front/src/private/components/settings/activity/alerting/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/configuration/Configuration.tsx
  opencti-platform/opencti-front/src/public/LoginRoot.tsx
  opencti-platform/opencti-front/src/public/components/Login.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useEnterpriseEdition.ts
  opencti-platform/opencti-front/tests_e2e/settings/parameters.spec.ts
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/domain/filterKeysSchema.ts
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/enterprise-edition/copyright.md
  opencti-platform/opencti-graphql/src/enterprise-edition/ee.ts
  opencti-platform/opencti-graphql/src/enterprise-edition/opencti_ca.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/manager/activityManager.ts
  opencti-platform/opencti-graphql/src/manager/cacheManager.ts
  opencti-platform/opencti-graphql/src/manager/fileIndexManager.ts
  opencti-platform/opencti-graphql/src/manager/playbookManager.ts
  opencti-platform/opencti-graphql/src/manager/telemetryManager.ts
  opencti-platform/opencti-graphql/src/migrations/1734016708002-license.js
  opencti-platform/opencti-graphql/src/modules/ai/ai-domain.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/fintelTemplate/fintelTemplate-domain.ts
  opencti-platform/opencti-graphql/src/modules/settings/licensing.js
  opencti-platform/opencti-graphql/src/modules/xtm/xtm-domain.js
  opencti-platform/opencti-graphql/src/resolvers/settings.js
  opencti-platform/opencti-graphql/src/types/settings.d.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/fintelTemplate-test.ts
  opencti-platform/opencti-graphql/tests/utils/testQueryHelper.ts
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#9541 [frontend] display virtual types in entity type filter list (#7637)
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-graphql/src/schema/schemaUtils.js
  opencti-platform/opencti-graphql/tests/01-unit/utils/schemaUtils-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
Labels: filigran team

#9603 [frontend] Sighting redirection from an entity Sighting tab (#8146)
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/EntityStixSightingRelationshipLine.tsx
Labels: filigran team

#9328 [backend] Migrate graphQL playground to GraphiQL (#7363)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
  opencti-platform/opencti-front/src/public/LoginRoot.tsx
  opencti-platform/opencti-front/src/public/PublicRoot.tsx
  opencti-platform/opencti-front/src/public/components/Playground.tsx
  opencti-platform/opencti-front/src/public/components/PublicDashboard.tsx
  opencti-platform/opencti-front/src/public/components/PublicTopBar.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/graphql/graphql.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/http/httpServer.js
  opencti-platform/opencti-graphql/src/resolvers/settings.js
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#9560 [backend/frontend] Remove authorized members for containers feature flag (#4961)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident.ts
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.ts
  opencti-platform/opencti-graphql/src/modules/case/case-rft/case-rft.ts
  opencti-platform/opencti-graphql/src/modules/case/feedback/feedback.ts
  opencti-platform/opencti-graphql/src/modules/grouping/grouping.ts
Labels: filigran team

#9622 [frontend] remove Playground button in profile when disabled from settings (#7363)
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
  opencti-platform/opencti-front/src/utils/platformModulesHelper.ts
Labels: filigran team

#9558 [backend] handle inferred organizations in organization sharing
  opencti-platform/opencti-front/src/private/components/settings/users/edition/UserEditionOverview.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware-loader.ts
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/src/types/user.d.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/notificationManager-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#9620 [frontend] replace the wrong variable
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/Root.tsx
Labels: filigran team

#9525 [frontend] Tools entity version are not fillable (#9330)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/arsenal/tools/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/Tool.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolDetails.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolDetails.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEdition.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEdition.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolPopover.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolPopover.tsx
Labels: filigran team

#9594 Refactor Data/import and set tab title
  opencti-platform/opencti-front/src/private/components/common/files/FileImportMarkingSelectionPopup.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileUploader.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileWork.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportWorkbenchesContent.tsx
Labels: filigran team

#9608 [frontend] spacing on entity's form (#9567)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionCreation.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupCreation.tsx
Labels: filigran team

#9602 [frontend/backend] EXCLUSION_LIST feature flag removed (#8941)
  opencti-platform/opencti-front/src/private/components/settings/CustomizationMenu.tsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-graphql/script/script-insert-dataset.js
  opencti-platform/opencti-graphql/src/database/exclusionListCache.ts
  opencti-platform/opencti-graphql/src/initialization.js
  opencti-platform/opencti-graphql/src/manager/exclusionListCacheBuildManager.ts
  opencti-platform/opencti-graphql/src/manager/exclusionListCacheSyncManager.ts
  opencti-platform/opencti-graphql/src/modules/exclusionList/exclusionList-domain.ts
  opencti-platform/opencti-graphql/src/modules/exclusionList/exclusionList.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/tests/utils/globalSetup.ts
  opencti-platform/opencti-graphql/tests/utils/testSetup.js
Labels: filigran team

#9621 [frontend] History tab top margin / spacing (#9568)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectLatestHistory.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectLatestHistory.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetDetails.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetDetails.tsx
Labels: filigran team

#9402 [frontend/backend] Enabled/disabled “authorized members” in Containers' form creation + default values (#4961)
  opencti-platform/opencti-front/src/components/Accordion.jsx
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/form/AuthorizedMembersField.tsx
  opencti-platform/opencti-front/src/private/components/data/Management.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/entity_setting/EntitySettingAttributeEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/entity_setting/EntitySettingAttributes.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useDefaultValues.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/case/case-incident/case-incident.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.graphql
  opencti-platform/opencti-graphql/src/modules/case/case-rft/case-rft.graphql
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-domain.ts
  opencti-platform/opencti-graphql/src/modules/grouping/grouping.graphql
Labels: filigran team

#9638 [frontend] align Profile buttons to the right for consistency
  opencti-platform/opencti-front/src/private/components/profile/ProfileLocalStorage.tsx
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
Labels: filigran team

#9591 [frontend] reset searchTerm when highlighting changes in content mapping (#9520)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjects.jsx
Labels: filigran team

#9650 [frontend] UI update (#8941)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/AlertInfo.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/private/components/data/Management.tsx
  opencti-platform/opencti-front/src/private/components/data/Sync.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListsStatus.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/exclusionList/exclusionList-domain.ts
  opencti-platform/opencti-graphql/src/modules/exclusionList/exclusionList.graphql
Labels: filigran team

#9250 [frontend/backend] Specify arch and platform when creating injects for OpenBAS (#8820)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResultContainer.jsx
  opencti-platform/opencti-front/src/private/components/events/incidents/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/Root.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/database/xtm-obas.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/xtm/deprecated/xtm-deprecated.ts
  opencti-platform/opencti-graphql/src/modules/xtm/deprecated/xtm-domain.js
  opencti-platform/opencti-graphql/src/modules/xtm/deprecated/xtm-resolver.ts
  opencti-platform/opencti-graphql/src/modules/xtm/deprecated/xtm.graphql
  opencti-platform/opencti-graphql/src/modules/xtm/xtm-domain.js
  opencti-platform/opencti-graphql/src/modules/xtm/xtm-resolver.ts
  opencti-platform/opencti-graphql/src/modules/xtm/xtm.graphql
Labels: filigran team

#9680 [backend] fix node script starting e2e server
  opencti-platform/opencti-graphql/package.json
Labels: filigran team

#9532 [frontend] Columns customisation interface for relationship list widget (#7295)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dashboard/WidgetListRelationships.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableComponent.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsList.jsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetConfig.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationParameters.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetListsDefaultColumns.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WidgetConfigColumnsCustomization.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_relationships/PublicStixRelationshipsList.tsx
Labels: filigran team

#9661 [frontend] put the auth member admin panel under EE (#4961)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/data/Management.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
Labels: filigran team

#9686 [frontend] reverse condition check valid EE
  opencti-platform/opencti-front/src/private/components/settings/activity/configuration/Configuration.tsx
Labels: filigran team

#9688 [frontend] Fix OpenBAS simulation for Cases (#8820)
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/Root.tsx
Labels: filigran team

#9662 [frontend] Remove "ACCESS_RESTRICTION_AT_CREATION" FF
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftCreation.tsx
Labels: filigran team

#9617 [backend/frontend] dissemination list - send file by email (#5551)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EEChip.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesDissemination.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useGranted.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/database/smtp.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/listener/UserActionListener.ts
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/migrations/1737537986865-capabilities-dissemination.js
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-converter.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-domain.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-graphql.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-resolver.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-types.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList.graphql
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList.ts
  opencti-platform/opencti-graphql/src/modules/index.ts
  opencti-platform/opencti-graphql/src/types/settings.d.ts
  opencti-platform/opencti-graphql/src/utils/emailTemplates/emailTemplate.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/data-initialization-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/role-test.js
Labels: filigran team

#9696 [backend] Fix param in query ai
  opencti-platform/opencti-graphql/src/modules/xtm/xtm-domain.js
Labels: filigran team

#9244 [backend/frontend] add configuration to have better chances to get RSS Feed contents (#8736)
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionRss.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvLine.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionRss/IngestionRssLine.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-rss.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-rss.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-types.ts
Labels: filigran team

#9681 [CI] Upload artifact should work if only back or front has worked (#9687)
  .drone.yml
Labels: filigran team

#9705 [frontend] - Fixes and standardization of some front parts (#8941)
  opencti-platform/opencti-front/src/components/AlertInfo.tsx
  opencti-platform/opencti-front/src/components/Breadcrumbs.tsx
  opencti-platform/opencti-front/src/components/PageContainer.tsx
  opencti-platform/opencti-front/src/components/ThemeDark.ts
  opencti-platform/opencti-front/src/components/ThemeLight.ts
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTableFilters.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableContext.tsx
  opencti-platform/opencti-front/src/private/components/common/danger_zone/DangerZoneBlock.tsx
  opencti-platform/opencti-front/src/private/components/data/Management.tsx
  opencti-platform/opencti-front/src/private/components/data/Playbooks.tsx
  opencti-platform/opencti-front/src/private/components/data/Sync.tsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookPopover.jsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListsStatus.tsx
  opencti-platform/opencti-front/src/private/components/settings/file_indexing/FileIndexingMonitoring.tsx
  opencti-platform/opencti-front/src/public/components/Login.tsx
Labels: filigran team

#9718 [backend/frontend] Remove some denormalized IDs for very large entities to improve performances (#9717)
  opencti-platform/opencti-front/src/components/list_lines/ListLines.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationships.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationForm.js
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsRelationshipsView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectVictimology.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectVictimologyRegions.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectVictimologySectors.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreationForm.js
  opencti-platform/opencti-front/src/private/components/locations/cities/CityKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/city.js
  opencti-platform/opencti-graphql/src/migrations/1737961892515-clean-deprecated-rels.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/city-test.js
Labels: filigran team

#9296 [backend] No default values on upsert mode (#8183)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#9708 [backend] only kill session in sseMiddleware for auth bearer sessions (#9216)
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
Labels: filigran team

#9726 [frontend] Fix error at infrastructure creation (#9698)
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureCreation.tsx
Labels: filigran team

#9725 [frontend] Confirmation message when deleting an infrastructure (#9721)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructurePopover.tsx
Labels: filigran team

#9720 [frontend] Fix for user deletion on cache + prevent loop on error on Private Root (#9719)
  opencti-platform/opencti-front/src/app.tsx
  opencti-platform/opencti-front/src/private/components/Error.jsx
  opencti-platform/opencti-graphql/src/manager/cacheManager.ts
Labels: filigran team

#9706 [frontend/backend] Export/import Fintel templates (#8906)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplatePopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplatesGrid.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/useFintelTemplateExport.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/useFintelTemplateImport.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/graphql-codegen.yml
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/fintelTemplate/fintel-template-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/fintelTemplate/fintelTemplate-domain.ts
  opencti-platform/opencti-graphql/src/modules/fintelTemplate/fintelTemplate.graphql
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-domain.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-utils.ts
Labels: filigran team

#9636 [frontend] Columns customisation for list entities widget (#7295)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dashboard/WidgetListCoreObjects.tsx
  opencti-platform/opencti-front/src/components/dashboard/WidgetListRelationships.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTableWithoutFragment.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsList.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsList.jsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetColumnsCustomizationInput.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationParameters.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetListsDefaultColumns.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsList.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_relationships/PublicStixRelationshipsList.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/hooks/useAttributes.ts
  opencti-platform/opencti-front/src/utils/tests/filtersUtils.test.tsx
Labels: filigran team

#9730 [frontend] align the card selector UI in export form
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectFileExportForm.tsx
Labels: filigran team

#9727 [backend] Fix usage of ElasticSearch ID
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/migrations/1611671597858-standard_id.js
  opencti-platform/opencti-graphql/src/migrations/1612381566895-clear_indicates_indexation.js
  opencti-platform/opencti-graphql/src/migrations/1612999232704-fix_attack_patterns.js
  opencti-platform/opencti-graphql/src/migrations/1613150325865-clear_aliases.js
  opencti-platform/opencti-graphql/src/migrations/1614942944848-fix_locations_identities.js
  opencti-platform/opencti-graphql/src/migrations/1616890781521-fix_aliases.js
  opencti-platform/opencti-graphql/src/migrations/1619270898754-migrate_incidents.js
  opencti-platform/opencti-graphql/src/migrations/1620980638439-fix_attack_patterns.js
  opencti-platform/opencti-graphql/src/migrations/1630337822820-report_status.js
  opencti-platform/opencti-graphql/src/migrations/1637328713848-system_standard_id.js
  opencti-platform/opencti-graphql/src/migrations/1716392968110-alias_migration.js
Labels: filigran team

#9729 [frontend] fix Fintel templates pdf export button (#8336)
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectFileExportForm.tsx
Labels: filigran team

#9391 [frontend] In Observable / Indicators composed with this observable view, fix the css(#9279)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.js
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableAddIndicators.jsx
Labels: filigran team

#9735 [frontend] COLUMNS_CUSTOMIZATION feature flag removed (#7295)
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationParameters.tsx
Labels: filigran team

#9653 [worker] Pool thread control
  opencti-worker/src/worker.py
Labels: filigran team

#9750 [frontend] Fix scrollbar on loggin page
  opencti-platform/opencti-front/src/public/components/Login.tsx
Labels: filigran team

#9736 [frontend] Improve color for readability on AI and fix loading on simulation
  opencti-platform/opencti-front/src/components/ThemeDark.ts
  opencti-platform/opencti-front/src/components/ThemeLight.ts
  opencti-platform/opencti-front/src/private/components/common/ai/AIInsights.tsx
  opencti-platform/opencti-front/src/private/components/common/ai/AISummaryActivity.tsx
  opencti-platform/opencti-front/src/private/components/common/ai/AISummaryContainers.tsx
  opencti-platform/opencti-front/src/private/components/common/ai/AISummaryForecast.tsx
  opencti-platform/opencti-front/src/private/components/common/ai/AISummaryHistory.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResultContainer.jsx
Labels: filigran team

#9753 [frontend] Some import fixes and Markdown field min height adapted
  opencti-platform/opencti-front/src/components/fields/MarkdownField.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/related_containers/RelatedContainers.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
  opencti-platform/opencti-front/vite.config.mts
Labels: filigran team

#9744 [backend] Prevent prepareElementForIndexing to block event loop
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/migrations/1672652100502-entity-settings-mapping.js
  opencti-platform/opencti-graphql/tests/01-unit/database/engine-test.js
Labels: filigran team

#9756 [frontend] Fix the high level error for OTP
  opencti-platform/opencti-front/src/app.tsx
  opencti-platform/opencti-front/src/private/components/AuthBoundary.jsx
Labels: filigran team

#9761 [frontend] widget config no select column on fintel context
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationParameters.tsx
Labels: filigran team

#9764 [ci] Fix environment variable for CI
  .circleci/config.yml
Labels: filigran team

#9747 [backend] save column selection when creating public dashboards
  opencti-platform/opencti-front/src/components/ItemCvssScore.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityDetails.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsList.jsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsList.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_relationships/PublicStixRelationshipsList.tsx
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-domain.ts
Labels: filigran team

#9623 [frontend] Add a new relationship views in entities having an Attack Pattern Knowledge view (#8835)
  opencti-platform/opencti-front/src/components/list_lines/index.ts
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationships.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatterns.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChain.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainMatrixInLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useQueryLoading.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#9742 [backend] Fix reindex error on deleting old objects (#9270)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
Labels: filigran team

#9765 [frontend/backend] Fintel template fixes (#8336)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dashboard/WidgetListRelationships.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_relationships/StixRelationshipsList.jsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplatePreview.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplateWidgetsSidebar.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetAttributesInput.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetConfig.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetConfigContext.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationParameters.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationPerspective.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetListsDefaultColumns.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WorkspaceWidgetConfig.jsx
  opencti-platform/opencti-front/src/utils/hooks/useBuildReadableAttribute.tsx
  opencti-platform/opencti-front/src/utils/outcome_template/engine/EngineFintelTemplateQuery.tsx
  opencti-platform/opencti-front/src/utils/outcome_template/engine/stix_core_objects/useBuildListOutcome.test.ts
  opencti-platform/opencti-front/src/utils/outcome_template/engine/stix_core_objects/useBuildListOutcome.tsx
  opencti-platform/opencti-front/src/utils/outcome_template/engine/useFileFromTemplate.ts
  opencti-platform/opencti-graphql/src/utils/fintelTemplate/__fintelTemplateWidgets.ts
Labels: filigran team

#9682 [backend/frontend] manage dissemination list and send PDFs (#5551)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/components/TextField.jsx
  opencti-platform/opencti-front/src/components/fields/DisseminationListField.tsx
  opencti-platform/opencti-front/src/private/components/common/menus/NavToolbarMenu.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesDissemination.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
  opencti-platform/opencti-front/src/private/components/settings/AccessesMenu.tsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationList.test.ts
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationListCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationListEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationListForm.tsx
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationListPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationListUtils.ts
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationLists.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/email.test.ts
  opencti-platform/opencti-front/src/utils/email.ts
  opencti-platform/opencti-front/src/utils/hooks/useApiMutation.ts
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-converter.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-domain.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-resolver.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-types.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList.graphql
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/disseminationList-test.ts
Labels: filigran team

#9773 [frontend] Fix QR code for OTP on dark mode that is not readable
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
  opencti-platform/opencti-front/src/public/components/OtpActivation.tsx
Labels: filigran team

#9770 [frontend] Delete confirmation message for workspaces (#9769)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
Labels: filigran team

#9749 [frontend] action on 'No label' click in 'Add entities' panel (#8985)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjects.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsInLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsLines.jsx
Labels: filigran team
