Repository OpenCTI-Platform/opencti, pull requests merged in 2025-04, with the labels that each got.

#10354 [frontend] remove NLQ Feature Flag (#9751)
  opencti-platform/opencti-front/src/components/SearchInput.jsx
Labels: filigran team

#10382 [frontend/backend] Import Workflow Chunk 4 - Add import mode to files dialog
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesContext.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesList.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesOptions.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesStepper.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesToggleMode.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesUploadProgress.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesUploader.tsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#10368 [e2e] some changes on background tasks test (#9147)
  opencti-platform/opencti-front/playwright.config.ts
  opencti-platform/opencti-front/tests_e2e/backgroundTask/backgroundTask.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/taskPopup.pageModel.ts
Labels: filigran team

#10363 [backend] Add authorize member in request access created RFI. (#9657)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/Message.tsx
  opencti-platform/opencti-front/src/components/RequestAccessDialog.tsx
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/modules/requestAccess/requestAccess-domain.ts
  opencti-platform/opencti-graphql/src/modules/requestAccess/requestAccessUtils.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/middleware-organization-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/requestAccess-domain-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/requestAccess-test.ts
Labels: filigran team

#10273 [frontend] Ability to Manipulate knowledge in playbooks (#8245)
  opencti-platform/opencti-front/src/private/components/common/form/KillChainPhasesField.jsx
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team, multi-repository

#10362 FAB_REPLACEMENT: add missing screens and realign styling
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/CreateEntityControlledDial.tsx
  opencti-platform/opencti-front/src/components/EditEntityControlledDial.tsx
  opencti-platform/opencti-front/src/components/UpdateEntityControlledDial.tsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EETooltip.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectEnrollPlaybook.tsx
  opencti-platform/opencti-front/src/private/components/data/CsvMappers.tsx
  opencti-platform/opencti-front/src/private/components/data/Feed.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionRss.jsx
  opencti-platform/opencti-front/src/private/components/data/IngestionTaxiiCollections.jsx
  opencti-platform/opencti-front/src/private/components/data/IngestionTaxiis.jsx
  opencti-platform/opencti-front/src/private/components/data/Stream.tsx
  opencti-platform/opencti-front/src/private/components/data/Sync.tsx
  opencti-platform/opencti-front/src/private/components/data/Taxii.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.jsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionRss/IngestionRssCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxiiCollection/IngestionTaxiiCollectionCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/stream/StreamCollectionCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/sync/SyncCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/Sectors.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationship.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/alerting/AlertCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplateCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayRuleCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationListCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/settings/kill_chain_phases/KillChainPhaseCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/labels/LabelCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/notifiers/NotifierCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganizationEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/retention/RetentionCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplateCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/SettingsOrganizationUserCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserEdition.tsx
Labels: filigran team

#10258 [frontend] Saved filter button and create mutation (#6044)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dataGrid/DataTableFilters.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterButton.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterCreateDialog.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterDeleteDialog.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterSelection.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilters.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFiltersAutocomplete.tsx
  opencti-platform/opencti-front/src/components/saved_filters/getSavedFilterScopeFilter.ts
  opencti-platform/opencti-front/src/private/components/common/lists/Filters.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/ListFilters.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter.graphql
Labels: filigran team

#10443 [frontend] UX fixes for NLQ (#9751)
  opencti-platform/opencti-front/src/components/SearchInput.jsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
Labels: filigran team

#10454 [backend] add query options log in Fail engine pagination error (#9751)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#10448 [frontend/backend] Small draft fixes (#9300)
  opencti-platform/opencti-front/src/private/components/drafts/DraftRoot.tsx
  opencti-platform/opencti-graphql/src/modules/draftWorkspace/draftWorkspace-domain.ts
Labels: filigran team

#10457 [backend] always save filters outside of draft (#9300)
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter-domain.ts
Labels: filigran team

#10288 [frontend] Save filters in the notifications datatable view
  opencti-platform/opencti-front/src/components/TextField.jsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeader.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterButton.tsx
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/profile/Notifications.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationLine.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationsLines.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/NotificationsToolBar.tsx
Labels: filigran team

#10456 [frontend] Some UI alignments
  opencti-platform/opencti-front/src/components/PageContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/form/AuthorizedMembersField.tsx
  opencti-platform/opencti-front/src/private/components/data/Management.tsx
  opencti-platform/opencti-front/src/private/components/data/ManagementMenu.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
Labels: filigran team

#10458 [frontend] Import Workflow - Fixes & import dialog in entities (#9760)
  opencti-platform/opencti-front/src/components/UploadImport.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceFileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesContext.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesList.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesOptions.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesStepper.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesUploader.tsx
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectsField.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
Labels: filigran team

#10444 [frontend] Request access - Update ui texts and labels (#9657)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/RequestAccessDialog.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/SubType.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/workflow/GlobalWorkflowSettings.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/workflow/RequestAccessConfigurationEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/workflow/RequestAccessSettings.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/workflow/StatusTemplateFieldScoped.tsx
Labels: filigran team

#10356 [backend/frontend] Authorized members organizations and groups intersection (#9952)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/Root.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/form/AuthorizedMembersField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/AuthorizedMembersFieldListItem.tsx
  opencti-platform/opencti-front/src/private/components/common/form/FormAuthorizedMembersDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/form/ObjectMembersField.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxiiCollection/IngestionTaxiiCollectionEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/stream/StreamCollectionEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiCollectionEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/notifiers/NotifierEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/entity_setting/EntitySettingAttributeEdition.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceManageAccessDialog.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/authorizedMembers.ts
  opencti-platform/opencti-front/src/utils/defaultValues.ts
  opencti-platform/opencti-front/src/utils/edition.js
  opencti-platform/opencti-front/src/utils/field.ts
  opencti-platform/opencti-front/src/utils/hooks/useDefaultValues.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting-domain.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/src/utils/authorizedMembers.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/authorizedMembers-test.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/access-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/container-authorized-members-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/requestAccess-test.ts
Labels: filigran team

#10426 [backend] add hashes to indicator observable values (#10277)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.graphql
Labels: filigran team, multi-repository

#10469 [frontend] fix an useless horizontal scrollbar when hovering over the 'Subscribe to Updates' button (#9463)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectQuickSubscription.tsx
Labels: filigran team

#10468 [frontend/backend] last draft improvements (#9300)
  opencti-platform/opencti-front/src/components/ExportButtons.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipSharing.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipSharing.tsx
  opencti-platform/opencti-graphql/src/database/draft-utils.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixSightingRelationship.js
Labels: filigran team

#10348 [frontend] list widgets sortable values according to runtime mapping enabled (#10338)
  opencti-platform/opencti-front/src/private/components/widgets/WidgetCreationParameters.tsx
Labels: filigran team

#10474 [frontend] In Mass Op to Indicator: Fix toggle display for detection field (#10466)
  opencti-platform/opencti-front/src/components/fields/SwitchField.jsx
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
Labels: filigran team

#10478 [frontend] In playbook, preserve field value when switching action type (#10467)
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookAddComponents.jsx
Labels: filigran team

#10447 [frontend] warning at public dashboard creation with @me filter value (#9128)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/public_dashboards/PublicDashboardCreationForm.tsx
Labels: filigran team

#10471 [frontend] remove IMPORT_WORKFLOW feature flag (#9760)
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceFileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
Labels: filigran team

#10464 [backend/frontend] Request access - fix workflow status and fix popup organization (#9657)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/RequestAccessDialog.tsx
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfi.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/ProcessingStatusOverview.tsx
  opencti-platform/opencti-front/src/private/components/common/form/MyOrganizationField.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/workflow/RequestAccessConfigurationEdition.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/tests_e2e/report/report.spec.ts
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/database/generate-message.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/status.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.graphql
  opencti-platform/opencti-graphql/src/modules/requestAccess/requestAccess-domain.ts
  opencti-platform/opencti-graphql/src/modules/requestAccess/requestAccessUtils.ts
  opencti-platform/opencti-graphql/src/resolvers/subType.js
  opencti-platform/opencti-graphql/src/types/store.d.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/requestAccess-test.ts
Labels: filigran team

#10472 [backend/frontend] Remove Request acces feature flag (#9657)
  opencti-platform/opencti-front/src/components/Message.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectOverview.jsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/SubType.tsx
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/modules/case/case-rfi/case-rfi.ts
  opencti-platform/opencti-graphql/src/modules/entitySetting/entitySetting.ts
  opencti-platform/opencti-graphql/src/modules/requestAccess/requestAccessUtils.ts
Labels: filigran team

#10491 [backend/frontend] Notification for request acces feature (#9657)
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfi.tsx
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-types.ts
  opencti-platform/opencti-graphql/src/modules/notifier/notifier-statics.ts
  opencti-platform/opencti-graphql/src/modules/requestAccess/requestAccess-domain.ts
  opencti-platform/opencti-graphql/src/types/event.d.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-stix/stix-testers.ts
  opencti-platform/opencti-graphql/src/utils/publisher-mock.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/00-Raw/sync-raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/sync-utils.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#10455 [frontend] playbook execution traces icon (#10425)
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookHeader.tsx
Labels: filigran team

#10492 [frontend/backend] fix within date checks (#4950)
  opencti-platform/opencti-front/src/components/filters/RelativeDateInput.tsx
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
Labels: filigran team

#10498 [backend] Better cache diff management for users
  opencti-platform/opencti-graphql/src/manager/cacheManager.ts
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
Labels: filigran team

#10496 [backend/frontend] align MIME type detection in import workflow with backend behavior
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesContext.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDropzone.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/file.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/file-test.ts
Labels: filigran team

#10494 [frontend] Some fixes on graphs (count, expand, selection UI) (#9298)
  opencti-platform/opencti-front/src/components/graph/GraphContext.tsx
  opencti-platform/opencti-front/src/components/graph/components/GraphToolbarExpandTools.tsx
  opencti-platform/opencti-front/src/components/graph/utils/useGraphInteractions.ts
  opencti-platform/opencti-front/src/components/graph/utils/useGraphPainter.ts
  opencti-platform/opencti-front/src/components/graph/utils/useGraphParser.ts
Labels: filigran team

#10499 [frontend] fix update note
  opencti-platform/opencti-front/src/components/TextField.jsx
  opencti-platform/opencti-front/src/utils/ai/ResponseDialog.tsx
Labels: filigran team

#10377 [frontend] filter entity types values in Relationship view (#10375)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationships.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsRelationshipsView.tsx
Labels: filigran team

#10164 [frontend] Missing observable name when creating sighting from knowledge graph (#9871)
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreationForm.js
Labels: filigran team

#10504 [backend/frontend] disable request access in draft (#9657)
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/ProcessingStatusOverview.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/workflow/RequestAccessConfigurationEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/workflow/RequestAccessConfigurationPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/workflow/RequestAccessSettings.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/workflow/RequestAccessStatus.tsx
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/modules/requestAccess/requestAccess-domain.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/requestAccess-domain-test.ts
Labels: filigran team

#10497 [backend] add user_id and account_login to searchable elastic fields (#10094)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#10522 [frontend] Observable types displayed with technical name in Decay rules (#9902)
  opencti-platform/opencti-front/src/private/components/common/form/ObservableTypesField.tsx
  opencti-platform/opencti-front/src/private/components/settings/decay/DecayRule.tsx
Labels: filigran team

#9119 [frontend] clamp confidence input values between 0 and 100 (#6715)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEditionOverview.jsx
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator.graphql
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixCyberObservable-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#10446 Dev environment: configure rabbitmq max message size
  opencti-platform/opencti-dev/docker-compose.yml
  opencti-platform/opencti-dev/rabbitmq.config
Labels: filigran team

#10287 [frontend] Upgrade to React 19 (#9960)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/components/ColorPickerField.jsx
  opencti-platform/opencti-front/src/components/ItemMarkings.jsx
  opencti-platform/opencti-front/src/components/dashboard/WidgetWordCloud.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTableFilters.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeader.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/components/fields/RichTextField.tsx
  opencti-platform/opencti-front/src/components/graph/GraphContext.tsx
  opencti-platform/opencti-front/src/components/graph/components/BasicRelationshipDetails.tsx
  opencti-platform/opencti-front/src/components/graph/components/EntityDetails.tsx
  opencti-platform/opencti-front/src/components/graph/components/RelationshipDetails.tsx
  opencti-platform/opencti-front/src/components/graph/components/StixMetaObjectDetails.tsx
  opencti-platform/opencti-front/src/components/range_slider/RangeSlider.jsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceDetails.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceFileImportViewer.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceHeader.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/StixCoreObjectOrStixCoreRelationshipNoteCard.tsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsList.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/CaseTaskOverview.tsx
  opencti-platform/opencti-front/src/private/components/common/bulk/dialog/BulkRelationDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsInLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsSuggestedMappingLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservables.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjects.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainerLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/related_containers/RelatedContainersDetails.tsx
  opencti-platform/opencti-front/src/private/components/common/danger_zone/DangerZoneBlock.tsx
  opencti-platform/opencti-front/src/private/components/common/drawer/Drawer.tsx
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EEField.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectQuickSubscription.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesViewLine.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainLines.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectOverview.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntityLine.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftEntities.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentDetails.tsx
  opencti-platform/opencti-front/src/private/components/observations/StixCyberObservables.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureDetails.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
  opencti-platform/opencti-front/src/private/components/search/SearchIndexedFiles.tsx
  opencti-platform/opencti-front/src/private/components/settings/case_templates/CaseTemplateEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/notifiers/NotifierEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserAnalytics.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/AddPersonasThreatActorIndividual.tsx
  opencti-platform/opencti-front/src/private/components/trash/all/DeleteOperationLine.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetAttributesInput.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareButton.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareList.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/DashboardEntitiesViz.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjectsLine.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/workspaceHeader/WorkspaceHeader.tsx
  opencti-platform/opencti-front/src/utils/hooks/useBulkCommit.tsx
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#10546 [frontend] display the number of “Indicators” in the malware knowledge view (#10529)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsEntitiesView.tsx
Labels: filigran team

#10547 [backend] fix the base time set in decayRule test
  opencti-platform/opencti-graphql/tests/01-unit/domain/decayRule-test.ts
Labels: filigran team

#10563 [backend] Enforce two-factor authentication option prevent connectors to communicate with the platform (#10557)
  opencti-platform/opencti-graphql/src/graphql/authDirective.js
Labels: filigran team

#10560 [backend] update @opensearch-project/opensearch to v3
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#10532 [frontend] Fix bulk search result panel (#10518)
  opencti-platform/opencti-front/src/private/components/SearchBulk.jsx
Labels: filigran team

#10549 [backend] fix clean up of denormalized rel if multiple rel of same type exists (#7208)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#9302 [frontend] Missing button to generate Observables in container (#9263)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#10501 [frontend] removing an indicator score from the UI should not be possible (#8021)
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEditionOverview.jsx
Labels: filigran team

#10575 [backend] fix draft search (#10554)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/draftWorkspace/draftWorkspace.graphql
Labels: filigran team

#10562 [frontend] fix Diamond tab in Observations > Infrastructure
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/getFilterFromEntityTypeAndNodeType.ts
Labels: filigran team

#10579 [frontend] Fix missing attribute in CaseRfi fragment (#10577)
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfi.tsx
  opencti-platform/opencti-front/tests_e2e/model/caseRfi.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/caseRfiDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboardDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/caseRfiForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/form/participantsForm.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/rfis/rfis.spec.ts
Labels: filigran team

#10595 [frontend] Fix init zoom on graphs (#10580)
  opencti-platform/opencti-front/src/components/graph/Graph.tsx
  opencti-platform/opencti-front/src/components/graph/utils/graphUtils.ts
  opencti-platform/opencti-front/src/components/graph/utils/useGraphInteractions.ts
Labels: filigran team

#10601 [backend] Improve notifications build performance (#10600)
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-types.ts
Labels: filigran team

#10428 [worker] fix starting pingAlive thread once
  opencti-worker/src/worker.py
Labels: filigran team

#10386 [backend] Fix container entities can't be shared with organization (#10108)
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/playbook-components-test.ts
Labels: filigran team

#10438 [worker] add a metric for number of running ingestion threads
  opencti-worker/src/worker.py
Labels: filigran team

#10648 [worker] Add capability to add custom headers in worker (#9992)
  opencti-worker/src/worker.py
Labels: filigran team

#9066 [frontend] Avoid URI filters repercussion in Knowledge screens (#8511)
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualKnowledge.tsx
Labels: filigran team

#10515 [backend] Fix activity manager indexing error (#7986)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
Labels: filigran team

#10660 [backend] Typo in STIX pattern creator (#10490)
  opencti-platform/opencti-graphql/src/python/runtime/stix2_create_pattern.py
Labels: filigran team

#10663 [frontend/backend] modify draft display behavior (#10615)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemOperations.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftContextBanner.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftEntities.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftProcessingStatus.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRelationships.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftSightings.tsx
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#10503 [frontend] every user should be able to manage its own notifications (#10290)
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/backgroundTask-common-test.ts
Labels: filigran team

#10670 [frontend] Fix layout for meta-objects in details popup (#10585)
  opencti-platform/opencti-front/src/components/graph/components/StixMetaObjectDetails.tsx
Labels: filigran team

#10666 [frontend] Expand on node double click in investigation (#10583)
  opencti-platform/opencti-front/src/components/graph/Graph.tsx
  opencti-platform/opencti-front/src/components/graph/GraphContext.tsx
  opencti-platform/opencti-front/src/components/graph/components/GraphToolbarExpandTools.tsx
  opencti-platform/opencti-front/src/components/graph/graph.types.ts
  opencti-platform/opencti-front/src/components/graph/utils/useGraphInteractions.ts
Labels: filigran team

#10667 [frontend] do not use particles for links (#10586)
  opencti-platform/opencti-front/src/components/graph/Graph.tsx
  opencti-platform/opencti-front/src/components/graph/SimpleGraph2D.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipInference.jsx
Labels: filigran team

#10655 [frontend] Fix init zoom on graphs (2) (#10580)
  opencti-platform/opencti-front/src/components/graph/GraphContainerCorrelation.tsx
  opencti-platform/opencti-front/src/components/graph/GraphContainerKnowledge.tsx
  opencti-platform/opencti-front/src/components/graph/utils/useGraphInteractions.ts
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.tsx
Labels: filigran team

#10677 [frontend] Graphs: display loading long enough to avoid blink effect (#10584)
  opencti-platform/opencti-front/src/components/graph/Graph.tsx
  opencti-platform/opencti-front/src/components/graph/components/GraphLoadingAlert.tsx
Labels: filigran team

#10678 [frontend] Dont display previous result while AskAI content is loading (#10665)
  opencti-platform/opencti-front/src/private/components/common/form/TextFieldAskAI.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectAskAI.tsx
  opencti-platform/opencti-front/src/utils/ai/ResponseDialog.tsx
Labels: filigran team

#10669 [frontend] When left menu opened, the active marker is not working in drafts section (#10614)
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
Labels: filigran team

#10683 [backend] fix password retrieval (#10681)
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.ts
Labels: filigran team

#10682 [frontend] Fix exporting image by skipping fonts (#10680)
  opencti-platform/opencti-front/src/utils/Image.js
Labels: filigran team

#10685 [CI] copy opencti-platform without nodes_modules for start services (#10684)
  .drone.yml
Labels: filigran team

#10122 [frontend] [Dashboard] White color in "Tree" visualization makes text illegible (#7458)
  opencti-platform/opencti-front/src/utils/Charts.jsx
  opencti-platform/opencti-front/src/utils/Colors.js
Labels: filigran team

#10596 [frontend/backend] enable adding relationships as representation entity targets (#9395)
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributeRefForm.tsx
  opencti-platform/opencti-front/src/utils/stixTypeUtils.ts
  opencti-platform/opencti-graphql/src/parser/csv-mapper.ts
  opencti-platform/opencti-graphql/src/schema/stixRefRelationship.ts
Labels: filigran team

#10704 [backend] refresh cache for Resolved filters at playbook/stream/trigger update (#10593)
  opencti-platform/opencti-graphql/src/manager/cacheManager.ts
Labels: filigran team

#10658 [backend] Error message when using NLQ with bad AI configuration (#10652)
  opencti-platform/opencti-front/src/components/SearchInput.jsx
  opencti-platform/opencti-graphql/src/database/ai-llm.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-domain.ts
Labels: filigran team

#10679 [backend] Add authorized members on notifications
  opencti-platform/opencti-graphql/src/modules/notification/notification-domain.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-types.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/user-delete-cleanup-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/notifications-test.ts
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#10717 [backend] refresh cache only if it has been initialized (#10593)
  opencti-platform/opencti-graphql/src/database/cache.ts
Labels: filigran team

#10556 [frontend] Some components moved to TypeScript (#10548)
  opencti-platform/opencti-front/src/components/ItemMarkings.jsx
  opencti-platform/opencti-front/src/components/ItemMarkings.tsx
  opencti-platform/opencti-front/src/components/TextField.jsx
  opencti-platform/opencti-front/src/components/TextField.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/components/fields/BulkTextField/BulkTextField.tsx
  opencti-platform/opencti-front/src/components/graph/components/BasicRelationshipDetails.tsx
  opencti-platform/opencti-front/src/components/graph/components/EntityDetails.tsx
  opencti-platform/opencti-front/src/components/graph/components/RelationshipDetails.tsx
  opencti-platform/opencti-front/src/components/graph/components/StixMetaObjectDetails.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/StixCoreObjectOrStixCoreRelationshipNoteCard.tsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsList.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/CaseTaskOverview.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectsSuggestedMappingLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainerLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/related_containers/RelatedContainersDetails.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx
  opencti-platform/opencti-front/src/private/components/common/form/TextFieldAskAI.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/EntityStixCoreRelationshipsEntitiesViewLine.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsContextualView.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainLines.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectDetectDuplicate.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectGlobalKillChain.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectOverview.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectVictimologyRegionsList.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectVictimologySectors.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntityLine.tsx
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorTargetedOrganizations.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipOverview.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableOverview.jsx
  opencti-platform/opencti-front/src/private/components/search/SearchIndexedFiles.tsx
  opencti-platform/opencti-front/src/private/components/trash/all/DeleteOperationLine.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceShareList.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjectsLine.tsx
Labels: filigran team

#10736 [backend] add disable_checksum_validation in minio config to disable default data protection (#10733)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/file-storage.js
Labels: filigran team

#10703 [backend/frontend] Add score to Organizations (#9811)
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationDetails.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationEditionOverview.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/database/stix-2-1-converter.ts
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/organization/organization-domain.ts
  opencti-platform/opencti-graphql/src/modules/organization/organization.graphql
  opencti-platform/opencti-graphql/src/modules/organization/organization.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
  opencti-platform/opencti-graphql/src/types/stix-2-1-sdo.d.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/organization-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team, multi-repository

#10657 [backend] remove status update if status is not in entity statuses configuration (#9071)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#10656 [frontend] Detect changes in CK Editor when in Source mode (#8694)
  opencti-platform/opencti-front/src/components/CKEditor.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContent.jsx
Labels: filigran team

#10731 [frontend] [Nested relation] Impossible to create nested relation with malware (#6959)
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
Labels: filigran team

#10783 [backend] fix lockResource default values initiation (#9582)
  opencti-platform/opencti-graphql/src/database/redis.ts
Labels: filigran team

#10780 [backend] fix entities without internal_id (#10172)
  opencti-platform/opencti-graphql/src/migrations/1742823297614-fix-missing-internal-ids.js
Labels: filigran team

#10802 [backend] Update cache after renew api key (10762)
  opencti-platform/opencti-graphql/src/domain/user.js
Labels: filigran team

#10809 [frontend] Make deletion calls in knowledge graphs sequential (#10784)
  opencti-platform/opencti-front/src/components/graph/components/GraphToolbarRemoveConfirm.tsx
Labels: filigran team

#10810 [backend] fix cron playbook node filter saving (#9646)
  opencti-platform/opencti-graphql/src/manager/playbookManager.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-domain.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
Labels: filigran team

#10805 [frontend] fix redirection to Entities created by a user (#10697)
  opencti-platform/opencti-front/src/private/components/Search.tsx
Labels: filigran team

#10806 [frontend] When only one export connector is available for the desired format, it should be directly selected (#10700)
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectFileExportForm.tsx
Labels: filigran team

#10820 [frontend] fix AI Insight content remove tags with props (#10506)
  opencti-platform/opencti-front/src/private/components/common/ai/AISummaryActivity.tsx
  opencti-platform/opencti-front/src/private/components/common/ai/AISummaryContainers.tsx
  opencti-platform/opencti-front/src/private/components/common/ai/AISummaryForecast.tsx
  opencti-platform/opencti-front/src/private/components/common/ai/AISummaryHistory.tsx
  opencti-platform/opencti-front/src/utils/utils.ts
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/utils/ai/cleanHtmlTags.ts
Labels: filigran team

#10840 [frontend] test fix e2e
  opencti-platform/opencti-front/tests_e2e/backgroundTask/backgroundTask.spec.ts
Labels: filigran team

#10825 [frontend/backend] handle update resulting in a standard_id change in draft (#10817)
  opencti-platform/opencti-front/src/private/components/drafts/DraftEntities.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRelationships.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftSightings.tsx
  opencti-platform/opencti-graphql/src/database/draft-utils.js
Labels: filigran team, multi-repository

#10811 [frontend] Display the all users in Creators trigger filter of Connector (#9023)
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.jsx
  opencti-platform/opencti-front/src/utils/Connector.ts
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-front/src/utils/hooks/useSchema.ts
Labels: filigran team

#10767 [frontend] Add support for dynamic configurable required fields to Entities
  opencti-platform/opencti-front/src/private/components/entities/events/EventCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemCreation.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemEditionOverview.jsx
Labels: community

#10776 [frontend] update attributes when configuring a csv feed sharing
  opencti-platform/opencti-front/src/utils/hooks/useAttributes.ts
Labels: filigran team

#10822 [backend] log user self-updates in activity stream (#10821)
  opencti-platform/opencti-graphql/src/domain/user.js
Labels: filigran team

#10845 [frontend] Columns not aligned in status template list (#10819)
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplateCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplateLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplateLineDummy.tsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplatePopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplates.tsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplatesLines.tsx
Labels: filigran team

#10864 [frontend] CTRL+click on left menu top level (#9787)
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
Labels: filigran team

#10859 [frontend] Provide all entity types for source/target type filters (#10852)
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
Labels: filigran team

#10836 [frontend] Fix the loaders in the distribution of opinions
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinions.tsx
Labels: filigran team

#10865 [frontend] DataTable: compute table width before calling loading lines (#10759)
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableComponent.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
Labels: filigran team

#10884 [backend] keep raw observable value format when converting observableValues in stix (#10883)
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-converter.ts
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
Labels: filigran team
