Repository OpenCTI-Platform/opencti, pull requests merged in 2025-08, with the labels that each got.

#11688 [frontend] External reference URLs ignore trailing slashes (#11164)
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/external_references/ExternalReferenceEditionOverview.tsx
Labels: community

#11796 [frontend/backend] Remove not allowed types in Nested Relation creation list (#11634)
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisDetails.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectNestedEntities.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntityContainer.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableNestedEntities.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/stixRefRelationship.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/stixRefRelationship.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixRefRelationships-test.js
Labels: filigran team

#11888 [frontend] fix makdown description on activity logs (#11887)
  opencti-platform/opencti-front/src/components/MarkdownDisplay.tsx
Labels: filigran team

#11845 [frontend] Delete popover fix
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationship.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceDeletion.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceKebabMenu.tsx
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboardRestriction.spec.ts
  opencti-platform/opencti-front/tests_e2e/investigations/createInvestigation.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboardDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/investigationDetails.pageModel.ts
Labels: filigran team

#11816 [frontend] - (CSVFeed) create new page to 1Click deploy (#11297)
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvImport.tsx
  opencti-platform/opencti-front/src/private/components/xtm-hub/Root.tsx
Labels: filigran team

#11854 [frontend] [ChatBot] Make platform message links clickable (#11747)
  opencti-platform/opencti-front/src/private/components/settings/settings_messages/SettingsMessagesBanner.tsx
  opencti-platform/opencti-front/src/utils/String.jsx
Labels: filigran team

#11846 [backend/frontend] feat(hub): add registration connectivity check
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/it.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/ru.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/ConfirmationDialog.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/ProcessInstructions.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/XtmHubSettings.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/XtmHubTab.tsx
  opencti-platform/opencti-front/src/utils/Time.js
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/manager/hubRegistrationManager.ts
  opencti-platform/opencti-graphql/src/manager/index.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/xtm/hub/xtm-hub-client.ts
  opencti-platform/opencti-graphql/src/types/settings.d.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/src/utils/settings.helper.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/settings-test.ts
Labels: filigran team

#11882 [frontend](feat) Be able to see at first sight if the connector is deployed by the manager (#7328)
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/SortConnectorsHeader.tsx
Labels: filigran team

#11917 [backend] modify updated_at attribute after ref relationship edition (#11915)
  opencti-platform/opencti-graphql/src/schema/fieldDataAdapter.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixRefRelationships-test.js
Labels: filigran team, datamodel

#11745 [backend] Add user agent and x-forwarded-for in activity raw and audit log (#7729)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#11909 [frontend] Missing translations in the rule configuration page (#11195)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/it.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/ru.json
  opencti-platform/opencti-front/lang/back/zh.json
Labels: filigran team

#11907 [frontend] Marking color missing in Task (#11024)
  opencti-platform/opencti-front/src/components/ItemMarkings.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/CaseTaskOverview.tsx
Labels: filigran team

#11941 [frontend] fix: use platform title during registration
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/XtmHubTab.tsx
Labels: filigran team

#11799 [backend](fix)Vulnerabilities: support "_" & "-" in CVSS values
  opencti-platform/opencti-graphql/src/utils/vulnerabilities.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/vulnerabilities-test.ts
Labels: filigran team

#11908 [backend/frontend] Enable OpenCTI registration in XTM Hub (#11295)
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/initialization.js
  opencti-platform/opencti-graphql/src/manager/hubRegistrationManager.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
Labels: filigran team

#11955 [backend/frontend] authorize several bulk actions on the same key if no replace action (#11932)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/domain/backgroundTask.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/backgroundTask-common-test.ts
Labels: filigran team

#12005 [frontend] Author chip redirection on click in Case RFI (#11989)
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncident.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfi.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRft.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectOverview.jsx
Labels: filigran team

#11789 [backend] replace the “Too many values” log error with a warn only (#11682)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#11988 [backend] optimize checkFilterKeys function (#11987)
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
Labels: critical

#12042 [frontend] user header layout (#12000)
  opencti-platform/opencti-front/src/private/components/settings/users/Root.jsx
Labels: filigran team

#12006 [backend] fix scheduling period in ingestion(#11599)
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/utils/format.js
Labels: filigran team

#12048 [frontend] refactor: rename query param for hub resource redirection
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceCreation.jsx
Labels: filigran team

#12029 [frontend] fix Observable creation validation (#11913)
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
Labels: filigran team

#11956 [backend/frontend] Take args into account at ref relationship creation (#10846)
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableNestedEntitiesLines.jsx
  opencti-platform/opencti-graphql/src/domain/stixRefRelationship.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixRefRelationships-test.js
Labels: filigran team

#12077 [frontend] Internal objects (playbooks, tasks) exposed in ingestion (#12065)
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
Labels: filigran team

#11974 [frontend/backend] improve catalog (#7328)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/form/ConfidenceField.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogCard.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogConnector.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogConnectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogConnectorHeader.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogConnectorOverview.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCreationUserHandling.tsx
  opencti-platform/opencti-front/src/private/components/data/Root.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/Catalogs.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ManagedConnectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ManagedConnectorEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/utils/hooks/useConfidenceLevel.ts
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/modules/catalog/catalog-domain.ts
  opencti-platform/opencti-graphql/src/modules/catalog/catalog-types.ts
  opencti-platform/opencti-graphql/src/modules/catalog/filigran/opencti-manifest.json
  opencti-platform/opencti-graphql/src/modules/notifier/notifier-domain.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/connector-composer-test.ts
  opencti-platform/opencti-graphql/tests/utils/catalogHelper.ts
Labels: filigran team

#11972 [frontend] fix chatbot UI (#11027)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/private/components/chatbox/AskArianeButton.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#12019 [backend] Enable audit log user agent info and add missing in knowledge history (#7729)
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/manager/historyManager.ts
Labels: filigran team

#12096 [frontend] rework connector update form (#7328)
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogConnectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ManagedConnectorEdition.tsx
Labels: filigran team

#12110 [frontend] Expand fields observables (#10480)
  opencti-platform/opencti-front/src/components/ItemCopy.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableDetails.jsx
Labels: filigran team

#12115 [backend] last version of the manifest (#7328)
  opencti-platform/opencti-graphql/src/modules/catalog/catalog-domain.ts
  opencti-platform/opencti-graphql/src/modules/catalog/filigran/opencti-manifest.json
Labels: filigran team

#12086 [frontend] fix delete stix ref relationship (#11631)
  opencti-platform/opencti-graphql/src/domain/stixRefRelationship.js
Labels: filigran team

#11981 [backend] fix provisioning numbers (#11668)
  opencti-platform/opencti-graphql/src/manager/taskManager.js
Labels: filigran team

#12132 [frontend/backend] relathionship technology from added (#11879)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectKnowledgeBar.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureKnowledge.tsx
  opencti-platform/opencti-front/src/utils/Colors.js
  opencti-platform/opencti-graphql/src/database/stix.ts
  opencti-platform/opencti-graphql/src/schema/stixCoreRelationship.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/filterKeysSchema-test.ts
Labels: filigran team

#12126 [backend/frontend] Be able to duplicate / import and export playbooks (#4523)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/CsvMappers.tsx
  opencti-platform/opencti-front/src/private/components/data/JsonMappers.tsx
  opencti-platform/opencti-front/src/private/components/data/Playbooks.tsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookPopover.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-domain.ts
  opencti-platform/opencti-graphql/src/modules/internal/jsonMapper/jsonMapper-domain.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-domain.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/playbook/playbook.graphql
Labels: filigran team

#12137 [frontend] replace names and icon (#7328)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/Connectors.jsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogConnector.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogConnectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogConnectorOverview.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionMenu.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/Root.jsx
Labels: filigran team

#12159 [frontend] truncate text in NavToolbarMenu when text exceeds width co…
  opencti-platform/opencti-front/src/private/components/common/menus/NavToolbarMenu.tsx
Labels: filigran team

#11898 [frontend] remove id from filters contained in dynamicRegardingOf (#11897)
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.test.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
Labels: technical improvement, filigran team

#12165 [frontend] Check XTM Hub connectivity with /health instead of the hom…
  opencti-platform/opencti-front/src/private/Root.tsx
Labels: filigran team

#12176 [frontend] new catalog card (#7328)
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog.tsx
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogCard.tsx
Labels: filigran team

#12195 [backend] [Playbook] Reduce knowledge component doesn't work (#12015)
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team
