Repository OpenCTI-Platform/opencti, pull requests merged in 2025-10, with the labels that each got.

#12543 [frontend] corrected margin in filter widget
  opencti-platform/opencti-front/src/private/components/widgets/WidgetFilters.tsx
Labels: filigran team

#12598 [frontend] Sighting header (#11920)
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationship.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipHeader.tsx
Labels: filigran team

#12513 [backend] Fix core relationship filtering to display correct country flags (#12438)
  opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/domain/stixRelationship.js
Labels: filigran team

#12608 [frontend] connector instance name (#12572)
  opencti-platform/opencti-front/src/private/components/data/IngestionCatalog/IngestionCatalogConnectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ManagedConnectorEdition.tsx
Labels: filigran team

#12519 [backend] remove unused dependencies (#12514)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#12610 Update Yarn version and configuration (#12609)
  .drone.yml
  .gitignore
  .yarnrc.yml
  opencti-platform/opencti-front/.gitignore
  opencti-platform/opencti-front/.yarn/releases/yarn-4.9.2.cjs
  opencti-platform/opencti-front/.yarnrc.yml
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/.gitattributes
  opencti-platform/opencti-graphql/.gitignore
  opencti-platform/opencti-graphql/.yarn/releases/yarn-4.9.2.cjs
  opencti-platform/opencti-graphql/.yarnrc.yml
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/yarn.lock
  renovate.json
Labels: technical improvement, filigran team

#12593 [backend] 'and' local mode for source/target entity filters (#12218)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
Labels: filigran team

#12603 [frontend] Location overview if relationships with restricted entities (#12601)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/SimpleStixObjectOrStixRelationshipStixCoreRelationshipLine.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/SimpleStixObjectOrStixRelationshipStixCoreRelationshipLine.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/SimpleStixObjectOrStixRelationshipStixCoreRelationships.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/SimpleStixObjectOrStixRelationshipStixCoreRelationships.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/SimpleStixObjectOrStixRelationshipStixCoreRelationshipsLines.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/SimpleStixObjectOrStixRelationshipStixCoreRelationshipsLines.tsx
Labels: filigran team

#12642 [backend] Fix flaky API test with error "Cannot find module './build/Release/nodecallspython.node'" (#12641)
  .drone.yml
Labels: bug, filigran team

#12590 [frontend] 'creators of related entity' filter values for Activity widgets (#11611)
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
Labels: filigran team

#12620 [backend] add stix filtering for "pattern" key (#10459)
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-stix/stix-testers.ts
  opencti-platform/opencti-graphql/tests/01-unit/database/stix-filtering-testers-test.ts
Labels: filigran team

#12626 [backend] GraphQL plugins generates errors (#12625)
  opencti-platform/opencti-graphql/src/config/errors.js
  opencti-platform/opencti-graphql/src/graphql/graphql.js
  opencti-platform/opencti-graphql/src/graphql/loggerPlugin.js
  opencti-platform/opencti-graphql/src/graphql/telemetryPlugin.js
Labels: bug

#12621 [backend] add initial score on vulnerabilities updates function (#12544)
  opencti-platform/opencti-graphql/src/utils/vulnerabilities.ts
Labels: filigran team

#12548 [backend] reintroduce some engine performance improvements
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#12665 [frontend] Page title is incorrect in activity (#10855)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/activity/alerting/Alerting.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/audit/Audit.tsx
  opencti-platform/opencti-front/src/private/components/settings/activity/configuration/Configuration.tsx
Labels: filigran team

#12661 [ci] Fix missing .yarnrc.yml in release 6.8.3 (#12660)
  .circleci/config.yml
  .github/workflows/test-feature-branch.yml
Labels: bug, filigran team
