Repository OpenCTI-Platform/opencti, pull requests merged in 2025-05, with the labels that each got.

#10807 [frontend] Removing popover should not show cascade delete in investigations (#10793)
  opencti-platform/opencti-front/src/components/graph/components/GraphToolbarRemoveConfirm.tsx
Labels: filigran team

#10887 [frontend] Fix Search in Add locations of Threat Actor Individuals (#10794)
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/AddLocationsThreatActorIndividual.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualLocation.jsx
Labels: filigran team

#10787 [frontend] Bug fix for the overflowing User Session area
  opencti-platform/opencti-front/src/private/components/settings/users/User.tsx
Labels: community

#10808 [frontend] Saved Filters Edition (#10383)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/DeleteDialog.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterButton.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterCreateDialog.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterDeleteDialog.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterSelection.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilters.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFiltersAutocomplete.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/Filters.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/ListFilters.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorageModel.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter-domain.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter-resolver.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter.graphql
Labels: filigran team

#10947 [backend] Http sharing (csv, taxii, stream) blocked data organization segregation sharing (#10945)
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
  opencti-platform/opencti-graphql/src/http/httpAuthenticatedContext.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/http/httpRollingFeed.ts
  opencti-platform/opencti-graphql/src/http/httpServer.js
  opencti-platform/opencti-graphql/src/http/httpTaxii.js
Labels: filigran team

#10814 [frontend] Add an highlight on the saved filters container
  opencti-platform/opencti-front/src/components/FilterIconButton.tsx
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTableFilters.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/Filters.tsx
Labels: filigran team

#10950 [backend/frontend] Fix convert workbench to draft (#10942)
  opencti-platform/opencti-front/src/private/components/common/files/FileManager.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#10728 [frontend] Fix validation errors on changes in creation forms
  opencti-platform/opencti-front/src/components/AutocompleteField.jsx
  opencti-platform/opencti-front/src/components/DateTimePickerField.jsx
  opencti-platform/opencti-front/src/components/SimpleTextField.jsx
  opencti-platform/opencti-front/src/components/TextField.jsx
  opencti-platform/opencti-front/src/components/fields/MarkdownField.jsx
  opencti-platform/opencti-front/src/components/fields/RichTextField.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/malware_analyses/MalwareAnalysisCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/notes/NoteCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/OpinionCreation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/opinions/StixCoreObjectOpinionsRadarDialog.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/form/AuthorizedMembersField.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreationForm.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionListEdition.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupCreation.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualCreation.tsx
Labels: filigran team

#10967 [backend] Improving code and test coverage on data sharing
  opencti-platform/opencti-graphql/src/domain/feed.ts
  opencti-platform/opencti-graphql/src/domain/stream.js
  opencti-platform/opencti-graphql/src/domain/taxii.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/csvFeed-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stream-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/taxiiCollection-test.ts
Labels: filigran team

#10904 Better handling of null value in organization score field (#9811)
  opencti-platform/opencti-front/src/components/ItemScore.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationEditionOverview.tsx
Labels: filigran team

#10974 [CI] add a log file for sync-raw test on jfrog output
  .drone.yml
  opencti-platform/opencti-graphql/tests/04-sync/00-Raw/sync-raw-test.js
Labels: filigran team

#10898 [frontend] Patch to correct duplicate persona chips
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualDetailsChips.tsx
Labels: community

#10889 [backend] Outcome template design [Chunk 1] (#10284)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/graphql-codegen.yml
  opencti-platform/opencti-graphql/src/config/conf.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign-converter.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign-domain.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign-graphql.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign-resolver.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign-types.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign.graphql
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign.ts
  opencti-platform/opencti-graphql/src/modules/index.ts
  opencti-platform/opencti-graphql/src/schema/internalObject.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/fintelDesign-test.ts
Labels: filigran team

#10959 [frontend] Add a description to countries (#10087)
  opencti-platform/opencti-front/src/private/components/locations/LocationDetails.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeArea.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/City.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/Country.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionDetails.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/Region.tsx
Labels: filigran team

#10986 [backend] One prefix missing on cyberark configuration
  opencti-platform/opencti-graphql/src/config/credentials.ts
Labels: filigran team

#10977 [frontend] Fix incorrect layout in Indicators composed with this observable
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableIndicators.jsx
Labels: filigran team

#10952 [frontend/backend] Edition mutation input updated (#10383)
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterButton.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter-domain.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter.graphql
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/savedFilterResolver-test.ts
Labels: filigran team

#10998 [frontend] Fix entity type filter in relationship creation list
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
Labels: filigran team

#10671 [frontend] Import View Rework - New tabs, move drafts to data / import, works drawer (#10482)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemOperations.tsx
  opencti-platform/opencti-front/src/components/UploadImport.tsx
  opencti-platform/opencti-front/src/private/Index.tsx
  opencti-platform/opencti-front/src/private/components/common/draft/DraftBlock.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileWork.jsx
  opencti-platform/opencti-front/src/private/components/common/files/ImportActionsPopover.tsx
  opencti-platform/opencti-front/src/private/components/common/files/ImportWorksDrawer.tsx
  opencti-platform/opencti-front/src/private/components/common/files/LaunchImportDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesOptions.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchCreation.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileCreator.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileLine.jsx
  opencti-platform/opencti-front/src/private/components/data/ImportMenu.tsx
  opencti-platform/opencti-front/src/private/components/data/import/Import.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportConnectors.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportFilesContent.tsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportWorkbenchesContent.tsx
  opencti-platform/opencti-front/src/private/components/data/import/Root.jsx
  opencti-platform/opencti-front/src/private/components/data/import/Root.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftContextBanner.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftCreation.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRoot.tsx
  opencti-platform/opencti-front/src/private/components/drafts/Drafts.tsx
  opencti-platform/opencti-front/src/private/components/drafts/Root.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/utils/Entity.ts
Labels: filigran team

#10999 [backend] Fix failed migration should stop the platform (#10988)
  opencti-platform/opencti-graphql/src/database/migration.js
Labels: filigran team

#11015 [backend] add more telemetry data for draft & workbenches (#11014)
  opencti-platform/opencti-graphql/src/domain/connector.ts
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/manager/telemetryManager.ts
  opencti-platform/opencti-graphql/src/modules/draftWorkspace/draftWorkspace-domain.ts
  opencti-platform/opencti-graphql/src/telemetry/TelemetryMeterManager.ts
Labels: filigran team

#10997 [frontend] Relationship start/stop time name uniformization (#8766)
  opencti-platform/opencti-front/src/components/graph/components/RelationshipDetails.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEntities.jsx
Labels: filigran team

#11037 [frontend] align filter popover on chip instead of label (#10723)
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
Labels: filigran team

#10867 [frontend] replace mutation and button by link to logout (#10863)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/public/components/OTPForm.tsx
Labels: filigran team

#10877 [frontend] [CSV Mapper] Two "Author" field on the Note representation (#10551)
  opencti-platform/opencti-front/src/private/components/data/csvMapper/representations/attributes/CsvMapperRepresentationAttributesForm.tsx
Labels: filigran team

#10561 [frontend] Fix MoreVert icon size in dataTable (#9783)
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookPopover.jsx
  opencti-platform/opencti-front/src/private/components/settings/activity/alerting/AlertingPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/kill_chain_phases/KillChainPhasePopover.jsx
  opencti-platform/opencti-front/src/private/components/settings/labels/LabelPopover.jsx
  opencti-platform/opencti-front/src/private/components/settings/marking_definitions/MarkingDefinitionPopover.jsx
  opencti-platform/opencti-front/src/private/components/settings/status_templates/StatusTemplatePopover.tsx
Labels: filigran team

#10653 [frontend / backend] forgot password (#9605)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/profile/ProfileOverview.jsx
  opencti-platform/opencti-front/src/public/components/Login.tsx
  opencti-platform/opencti-front/src/public/components/LoginForm.tsx
  opencti-platform/opencti-front/src/public/components/OTPForm.tsx
  opencti-platform/opencti-front/src/public/components/OtpActivation.tsx
  opencti-platform/opencti-front/src/public/components/ResetPassword.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/listener/UserActionListener.ts
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/modules/auth/auth-domain.ts
  opencti-platform/opencti-graphql/src/modules/auth/auth-graphql.ts
  opencti-platform/opencti-graphql/src/modules/auth/auth-resolver.ts
  opencti-platform/opencti-graphql/src/modules/auth/auth-types.ts
  opencti-platform/opencti-graphql/src/modules/auth/auth.graphql
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-domain.ts
  opencti-platform/opencti-graphql/src/modules/index.ts
  opencti-platform/opencti-graphql/src/types/smtp.d.ts
  opencti-platform/opencti-graphql/src/types/user.d.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/auth-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/redis-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/auth-test.ts
Labels: filigran team

#11053 [frontend] Timeline filters layout (#10791)
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectThreatKnowledge.tsx
Labels: filigran team

#11054 [backend] add correct user_inside_platform_organization in taskManager context (#11043)
  opencti-platform/opencti-graphql/src/http/httpAuthenticatedContext.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/utils/access.ts
Labels: filigran team

#11004 [backend] now also send stream message in digest notifications (#8685)
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
Labels: filigran team

#11042 [frontend] Stix core object history lines (#10965)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistoryLines.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistoryLines.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectLatestHistory.tsx
Labels: filigran team

#10837 [frontend] Stop Spam Notif Chunk 1 (#8685)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/profile/Notifications.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/DigestNotification.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/DigestNotificationDrawer.tsx
  opencti-platform/opencti-front/src/private/components/profile/notifications/notificationUtils.tsx
Labels: filigran team

#10984 [backend] validate date inputs format in validateInputAgainstSchema (#10881)
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-domain.ts
  opencti-platform/opencti-graphql/src/schema/schema-attributes.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-csv-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/report-test.js
Labels: filigran team

#11067 [frontend] Fix Hover Indicators/Knowledge view (#11050)
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEntityLine.jsx
Labels: filigran team

#11065 [frontend] In Live streams view and TAXII collections view, the hover overtakes on the line below. (#10696)
  opencti-platform/opencti-front/src/private/components/data/stream/StreamLine.jsx
  opencti-platform/opencti-front/src/private/components/data/taxii/TaxiiLine.jsx
Labels: filigran team

#11038 [frontend/backend] History message for new version of a file upload (#10598)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistoryLine.jsx
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/listener/UserActionListener.ts
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
Labels: filigran team

#11071 [frontend] Lines layout is broken in observable / knowledge section (#10797)
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipPopover.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEntitiesLines.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableNestedEntitiesLines.jsx
Labels: filigran team

#10960 [frontend] Vocabularies screen layout is broken (#10818)
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/Vocabularies.tsx
  opencti-platform/opencti-front/src/private/components/settings/attributes/VocabulariesLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/attributes/VocabularyCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/attributes/VocabularyLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/attributes/VocabularyPopover.tsx
Labels: filigran team

#11070 [frontend] remove ImportFilesDialog fix (#10761)
  opencti-platform/opencti-front/src/components/UploadImport.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx
Labels: filigran team

#11074 [frontend] Typo in the word WORKFLOW under customization/report (#11046)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/sub_types/SubType.tsx
Labels: filigran team

#11007 [frontend] [Outcome-Template] Add logo of a platform into template #10284
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ItemIcon.jsx
  opencti-platform/opencti-front/src/private/components/settings/CustomizationMenu.tsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesign.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesignCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesignPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesigns.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Entity.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign.graphql
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/fintelDesign-test.ts
Labels: filigran team

#10888 [backend/frontend] Create query csvFeedAddInputFromImport endpoint (#10350)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/IngestionCsv.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvFeedTestDialog.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvImport.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvPopover.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-types.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-domain.ts
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-types.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/csv-feed-test.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/csv-mapper-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/csvFeed-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-csv-test.ts
  opencti-platform/opencti-graphql/tests/data/csvFeed/test-csv-feed.json
Labels: filigran team

#11079 Correct bastion ip for prerelease aws
  .circleci/config.yml
Labels: filigran team

#11002 [frontend] Refacto AttackPatternsMatrixColumns & remove invert color (#10240)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChain.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainMatrix.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternsMatrix.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternsMatrixBar.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternsMatrixColumns.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternsMatrixColumns.tsx
  opencti-platform/opencti-front/src/utils/ListParameters.js
Labels: filigran team

#11083 Update fingerprint used to connect to bastion
  .circleci/config.yml
Labels: filigran team

#11107 [frontend] Improve close import file dialog (#10616)
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx
Labels: filigran team

#11108 [CI] Feature branch on staging
  .github/workflows/test-feature-branch.yml
Labels: filigran team, tiny

#11085 [Backend/Frontend] Add CSV Feed export functionality
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvPopover.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/csvFeed-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-csv-test.ts
Labels: filigran team

#11121 [backend/frontend] validate Indicator & Observable score value (#10975)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorCreation.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEditionOverview.jsx
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/utils/format.js
  opencti-platform/opencti-graphql/tests/01-unit/utils/format-utils-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/indicator-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/stixCyberObservable-test.js
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#10832 [backend] notif buffering implementation (#8685)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification-types.ts
  opencti-platform/opencti-graphql/src/modules/notification/notification.ts
  opencti-platform/opencti-graphql/src/modules/notifier/notifier-domain.ts
Labels: filigran team

#11106 [backend/frontend] Forgot password improvements (#9605)
  opencti-platform/opencti-front/src/public/components/Login.tsx
  opencti-platform/opencti-front/src/public/components/LoginForm.tsx
  opencti-platform/opencti-front/src/public/components/ResetPassword.tsx
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/modules/auth/auth-domain.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/auth-test.ts
Labels: filigran team

#11125 [backend] Apply case template with playbook: FF removed (#7231)
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-components.ts
Labels: filigran team

#11114 [frontend] fix headings options in ckeditor (#10661)
  opencti-platform/opencti-front/src/components/CKEditor.tsx
Labels: filigran team

#11000 [frontend] Add Italian language support (#10434)
  opencti-platform/opencti-front/lang/back/it.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/components/AppIntlProvider.tsx
  opencti-platform/opencti-front/src/components/DateTimePickerField.jsx
  opencti-platform/opencti-front/src/components/TimePickerField.jsx
  opencti-platform/opencti-front/src/utils/BrowserLanguage.js
Labels: community

#10708 First version under FF of the connector composer
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/components/Theme.d.ts
  opencti-platform/opencti-front/src/private/components/data/Connectors.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/Catalogs.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ManagedConnectorCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ManagedConnectorEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/WorkersStatus.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/Connector.tsx
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/graphql-codegen.yml
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/database/repository.js
  opencti-platform/opencti-graphql/src/domain/connector.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/modules/catalog/catalog-domain.ts
  opencti-platform/opencti-graphql/src/modules/catalog/catalog-graphql.ts
  opencti-platform/opencti-graphql/src/modules/catalog/catalog-resolver.ts
  opencti-platform/opencti-graphql/src/modules/catalog/catalog-types.ts
  opencti-platform/opencti-graphql/src/modules/catalog/catalog.graphql
  opencti-platform/opencti-graphql/src/modules/catalog/filigran/opencti-manifest.json
  opencti-platform/opencti-graphql/src/modules/index.ts
  opencti-platform/opencti-graphql/src/resolvers/connector.js
  opencti-platform/opencti-graphql/src/schema/identifier.js
  opencti-platform/opencti-graphql/src/schema/internalObject.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/src/utils/authorizedMembers.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/providers-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/user-delete-cleanup-test.ts
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team
