Repository OpenCTI-Platform/opencti, pull requests merged in 2025-03, with the labels that each got.

#10106 [frontend] Inconsistancy of empty fields in Threat Actor Individual overview (#9818)
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/AddLocations.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetDetails.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetLocations.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/AddLocationsThreatActorGroup.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupDetails.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualBiographics.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualDemographics.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualDetails.tsx
Labels: filigran team

#10012 [frontend] Fix spacing issues and buttons movement in Victimology view (#9724)
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectVictimology.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectVictimologySectors.jsx
Labels: filigran team

#10115 [frontend] Graphs refactoring - chunk3 investigation graph (#9298)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceManageAccessDialog.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/Investigation.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjects.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationExpandForm.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/useInvestigationGraphEdit.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/useInvestigationGraphUpdateEntities.tsx
  opencti-platform/opencti-front/src/utils/graph/Graph.tsx
  opencti-platform/opencti-front/src/utils/graph/GraphContext.tsx
  opencti-platform/opencti-front/src/utils/graph/GraphToolbar.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbar.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarContentTools.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarExpandTools.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarRemoveConfirm.tsx
  opencti-platform/opencti-front/src/utils/graph/graph.types.ts
  opencti-platform/opencti-front/src/utils/graph/utils/graphTimeRange.ts
  opencti-platform/opencti-front/src/utils/graph/utils/graphUtils.ts
  opencti-platform/opencti-front/src/utils/graph/utils/useGraphInteractions.ts
  opencti-platform/opencti-front/src/utils/graph/utils/useGraphParser.ts
  opencti-platform/opencti-front/src/utils/object.ts
Labels: filigran team

#10100 [backend/frontend] Add Import from XTM Hub button in Custom Dashboards
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/GradientButton.tsx
  opencti-platform/opencti-front/src/components/Theme.d.ts
  opencti-platform/opencti-front/src/components/ThemeDark.ts
  opencti-platform/opencti-front/src/components/ThemeLight.ts
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceCreation.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Workspaces.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/static/images/xtm/xtm_hub_dark.png
  opencti-platform/opencti-front/src/static/images/xtm/xtm_hub_light.png
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: feature, filigran team

#10024 [frontend/backend] Relative datetime range filter (#4950)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/FilterValuesContent.tsx
  opencti-platform/opencti-front/src/components/filters/BasicFilterInput.tsx
  opencti-platform/opencti-front/src/components/filters/DateRangeFilter.tsx
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/components/filters/FilterValues.tsx
  opencti-platform/opencti-front/src/components/filters/QuickRelativeDateFiltersButtons.tsx
  opencti-platform/opencti-front/src/components/filters/RelativeDateInput.tsx
  opencti-platform/opencti-front/src/components/i18n.jsx
  opencti-platform/opencti-front/src/private/components/common/lists/FilterDate.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/String.jsx
  opencti-platform/opencti-front/src/utils/filters/filtersHelpers-types.ts
  opencti-platform/opencti-front/src/utils/filters/filtersManageStateUtil.ts
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/filters/useFiltersState.tsx
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-front/src/utils/tests/String.test.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/schema/schemaUtils.js
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/filtering-utils-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/filterGroup-test.js
Labels: filigran team

#10139 [frontend] add Feature Flag XTM_HUB_INTEGRATION (#10027)
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceCreation.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Workspaces.tsx
Labels: filigran team

#10142 [frontend] Markings default values switching in Customization (#10107)
  opencti-platform/opencti-front/src/private/components/settings/sub_types/entity_setting/EntitySettingAttributes.tsx
  opencti-platform/opencti-front/src/utils/hooks/useDefaultValues.ts
Labels: filigran team

#10146 [backend] Update description for placeholders
  opencti-platform/opencti-graphql/src/modules/xtm/xtm-domain.js
Labels: filigran team

#10147 Revert "Update dependency slack to v5"
  .circleci/config.yml
Labels: filigran team

#10098 [backend] X509 Certificate pattern definition (#10091)
  opencti-platform/opencti-graphql/src/python/runtime/stix2_create_pattern.py
Labels: filigran team

#10162 [frontend] fix call to widget horizontal bar for relationships
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/DashboardEntitiesViz.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/DashboardRelationshipsViz.tsx
Labels: filigran team

#9961 [frontend/backend] Natural Language Capabilities in OpenCTI (#9751)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/Message.jsx
  opencti-platform/opencti-front/src/components/Message.tsx
  opencti-platform/opencti-front/src/components/SearchInput.jsx
  opencti-platform/opencti-front/src/private/components/RootSearch.tsx
  opencti-platform/opencti-front/src/private/components/Search.tsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-front/src/relay/environment.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/SearchUtils.ts
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/database/ai-llm.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-domain.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-nlq-utils.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai.graphql
  opencti-platform/opencti-graphql/src/utils/ai/dataResolutionHelpers.js
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
  opencti-platform/opencti-graphql/tests/01-unit/database/stix-filtering-engine-test.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/filtering-utils-test.ts
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#10179 [frontend] add e2e test to ensure all dashboards widgets are working correctly (#10178)
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboard_e2e.json
Labels: filigran team

#10158 [frontend] vulnerability detail grid updated (#10118)
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityDetails.tsx
Labels: filigran team

#10202 [backend] Live stream consuming can crash when inferences and specific filters are used (#10201)
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
Labels: filigran team

#10177 [frontend] Fix filters edition after NLQ search (#9751)
  opencti-platform/opencti-front/src/private/components/Search.tsx
Labels: filigran team

#10218 [frontend] fix URL generation for xtm hub (#10027)
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceCreation.jsx
Labels: filigran team

#10175 [frontend] fix filters modification in Indicator Knowledge view (#10173)
  opencti-platform/opencti-front/src/private/components/observations/indicators/IndicatorEntitiesLines.jsx
Labels: filigran team

#10221 [frontend] fix redirection link in draft overview when in read only mode (#9300)
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftEntities.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRelationships.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRoot.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftSightings.tsx
Labels: filigran team

#10222 [frontend] feat: Hide XTM Hub CTA button if platform_xtmhub_url variable is empty
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceCreation.jsx
Labels: filigran team

#10239 [frontend] fix the ability to edit a country after a first edition opening (#10204)
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryPopover.tsx
Labels: filigran team

#10256 [frontend] improve queries + refacto
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainers.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainersGraph.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainersGraph.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/StixCoreObjectOrStixCoreRelationshipContainersGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/Investigation.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/utils/fetchMetaObjectsCount.ts
  opencti-platform/opencti-front/src/utils/graph/Graph.tsx
  opencti-platform/opencti-front/src/utils/graph/GraphContainerCorrelation.tsx
  opencti-platform/opencti-front/src/utils/graph/GraphContainerKnowledge.tsx
  opencti-platform/opencti-front/src/utils/graph/GraphToolbar.tsx
  opencti-platform/opencti-front/src/utils/graph/components/EntitiesDetailsRightBar.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphLoadingAlert.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarContentTools.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarExpandTools.tsx
  opencti-platform/opencti-front/src/utils/graph/graph.types.ts
  opencti-platform/opencti-front/src/utils/graph/utils/useGraphInteractions.ts
  opencti-platform/opencti-front/src/utils/graph/utils/useGraphPainter.ts
Labels: filigran team

#10150 [backend] ”Saved filters” module implemented
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/graphql-codegen.yml
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/index.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter-converter.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter-domain.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter-graphql.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter-resolver.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter-types.ts
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter.graphql
  opencti-platform/opencti-graphql/src/modules/savedFilter/savedFilter.ts
  opencti-platform/opencti-graphql/src/schema/internalObject.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/savedFilterResolver-test.ts
Labels: filigran team

#10144 [frontend] add marking icon in definiton column (#10074)
  opencti-platform/opencti-front/src/components/dashboard/WidgetListRelationships.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTableWithoutFragment.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableComponent.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeader.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeaders.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/related_containers/RelatedContainersDetailsTable.tsx
  opencti-platform/opencti-front/src/private/components/settings/MarkingDefinitions.tsx
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationLists.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx
Labels: filigran team

#10272 [frontend/renovate] Upgrade react-markdown to v10
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/components/MarkdownDisplay.tsx
  opencti-platform/opencti-front/yarn.lock
Labels: dependencies, filigran team

#9201 [frontend] added configurable required fields to Arsenal
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareEditionDetails.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionOverview.jsx
Labels: community

#9113 [frontend] Add support for dynamic configurable required fields to Techniques
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/courses_of_action/CourseOfActionEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_components/DataComponentEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/data_sources/DataSourceEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeCreation.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeEditionOverview.jsx
Labels: community

#10163 [frontend/backend] Dynamic 'me' filter value (#9128)
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/domain/basicObject.ts
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/modules/playbook/playbook-domain.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-resolution.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/filtering-utils-test.ts
Labels: filigran team

#9179 [backend] update el core settings when updating indices mappings (#9157)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: do not merge, filigran team

#10167 [frontend] avoid duplicate relationship types in relationship creation form (#10151)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreation.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromRelation.jsx
Labels: filigran team

#10138 [frontend] regardingOf filter display in tasks details (#10099)
  opencti-platform/opencti-front/src/components/filters/DisplayFilterGroup.tsx
Labels: filigran team

#10282 [frontend] Align column content with title in Support package (#9731)
  opencti-platform/opencti-front/src/private/components/settings/support/SupportPackageLine.tsx
Labels: filigran team

#10254 [frontend] Also apply gradient on text for GradientButton (#10243)
  opencti-platform/opencti-front/src/components/GradientButton.tsx
  opencti-platform/opencti-front/src/components/Theme.d.ts
  opencti-platform/opencti-front/src/components/ThemeDark.ts
  opencti-platform/opencti-front/src/components/ThemeLight.ts
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceCreation.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/Workspaces.tsx
Labels: filigran team

#10303 [frontend/renovate] Update dependency cookie to v1
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#10302 [backend] Update decay score when expiration manager revoke an indicator. (#10174)
  opencti-platform/opencti-graphql/src/manager/expiredManager.js
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/decayRule-test.ts
Labels: filigran team

#10297 [e2e] Verifiy that background task popup is gone away before continue.
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/tests_e2e/backgroundTask/backgroundTask.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/taskPopup.pageModel.ts
  opencti-platform/opencti-graphql/tests/data/data-test-stix-e2e.json
Labels: filigran team

#10034 [frontend/backend] Import file dialog, with connectors - Chunk 2 (#9760)
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesList.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesOptions.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesUploader.tsx
  opencti-platform/opencti-front/src/private/components/common/form/EntitySelect.tsx
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectsField.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/connector.ts
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/file.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
Labels: filigran team

#10148 [frontend] Enhance massive operations on Indicators Chunk 1 (#8245)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#10275 [frontend] Content Mapping: Popup dialog is not opened for the main content (#10033)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectMappableContent.tsx
Labels: filigran team

#10279 [frontend] fix the loadQuery update after duplicating a CSV mapper
  opencti-platform/opencti-front/src/private/components/data/csvMapper/CsvMapperPopover.tsx
Labels: filigran team

#10181 [frontend/backend] Add reset connector under danger zone (#9387)
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useSensitiveModifications.ts
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#10260 [backend/frontend] bug fixing following draft testing
  opencti-platform/opencti-front/src/private/components/common/files/FileExportViewer.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileViewer.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFiles.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentHeader.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftEntities.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRelationships.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftSightings.tsx
  opencti-platform/opencti-graphql/src/connector/importCsv/importCsv-connector.ts
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
Labels: filigran team

#10285 [frontend/backend] Entities ids mapping by entity type for NLQ filters result (#9751)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/SearchInput.jsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-graphql/src/modules/ai/ai-domain.ts
Labels: filigran team

#10334 Add generated files from latest commit
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#10262 [frontend] large spacing on vulnerability details (#10118)
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityDetails.tsx
Labels: filigran team

#10301 [bakend] Filter extraction pipeline improvement (#9751)
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/database/ai-llm.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-domain.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-nlq-few-shot-examples.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-nlq-schema.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-nlq-utils.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-nlq-values.ts
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team

#10270 [backend] Relationship representative in email notifications (#10208)
  opencti-platform/opencti-graphql/src/database/stix-representative.ts
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/stix-representative-test.ts
Labels: filigran team

#10346 [frontend] fix missing userId props on UserPopover
  opencti-platform/opencti-front/src/private/components/settings/users/Root.jsx
Labels: filigran team

#10304 [backend] upsert indicator score if revoked (#10298)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#10337 [backend] now trim inputData to check if element should be upserted (#10325)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#10332 [frontend] Spacing of left submenu without icons is incorrect (#10296)
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
Labels: filigran team

#10309 [backend/frontend] feature flag removal & small fixes (#9300)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/Index.tsx
  opencti-platform/opencti-front/src/private/components/Search.tsx
  opencti-platform/opencti-front/src/private/components/common/files/FileWork.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFilesAndHistory.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftPopover.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRoot.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-graphql/src/connector/connector-domain.ts
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/http/httpServer.js
  opencti-platform/opencti-graphql/src/managers.js
  opencti-platform/opencti-graphql/src/modules/draftWorkspace/draftWorkspace-domain.ts
  opencti-platform/opencti-graphql/src/schema/attribute-definition.ts
Labels: filigran team

#10180 [backend] Initial support of Azure OpenAI
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/database/ai-llm.ts
Labels: filigran team, askai

#10295 [backend] New filter 'is inferred' (#8763)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/domain/filterKeysSchema.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
  opencti-platform/opencti-graphql/tests/05-rules/report-refs-observable-based-on-test.js
Labels: filigran team

#10376 [frontend] fix bulk search table text color
  opencti-platform/opencti-front/src/private/components/SearchBulk.jsx
Labels: bug, filigran team, regression

#10259 [backend] implement cluster safe gauges for telemetry (#10037)
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/manager/telemetryManager.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-domain.ts
  opencti-platform/opencti-graphql/src/telemetry/BatchExportingMetricReader.ts
  opencti-platform/opencti-graphql/src/telemetry/TelemetryMeterManager.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/redis-test.js
  opencti-platform/opencti-graphql/tests/02-integration/04-manager/telemetryManager-test.ts
  opencti-platform/opencti-graphql/tests/utils/globalSetup.ts
  opencti-platform/opencti-graphql/vitest.config.test.ts
Labels: filigran team

#10352 [frontend] Remove last usage of old graphs (#9298)
  opencti-platform/opencti-front/src/components/graph/Graph.tsx
  opencti-platform/opencti-front/src/components/graph/GraphContext.tsx
  opencti-platform/opencti-front/src/components/graph/SimpleGraph2D.tsx
  opencti-platform/opencti-front/src/components/graph/components/EntitiesDetailsRightBar.tsx
  opencti-platform/opencti-front/src/components/graph/components/LassoSelection.tsx
  opencti-platform/opencti-front/src/components/graph/components/RelationSelection.tsx
  opencti-platform/opencti-front/src/components/graph/graph.types.ts
  opencti-platform/opencti-front/src/components/graph/utils/useGraphInteractions.ts
  opencti-platform/opencti-front/src/components/graph/utils/useGraphPainter.ts
  opencti-platform/opencti-front/src/components/graph/utils/useGraphParser.ts
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerMappingContent.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCoreObjectPopover.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipInference.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipOverview.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipInference.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipOverview.jsx
  opencti-platform/opencti-front/src/utils/Graph.js
Labels: filigran team

#10384 [frontend] fix export of Indicators in Knowledge tab (#10381)
  opencti-platform/opencti-front/src/components/dataGrid/DataTable.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTableFilters.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableTypes.ts
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsEntitiesView.tsx
Labels: filigran team

#10372 [frontend] fix External reference search field
  opencti-platform/opencti-front/src/private/components/common/form/ExternalReferencesField.tsx
Labels: filigran team

#10361 [cd] prerelease use bastion
  .circleci/config.yml
Labels: filigran team

#10385 [CI] Add auto label on all PR creation
  .github/workflows/auto-set-labels.yml
Labels: filigran team

#10104 [frontend] Workspace Header updated (#9566)
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplateWidgetsSidebar.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetConfig.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceDuplicationDialog.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceHeader.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/DashboardTimeFilters.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WorkspaceWidgetConfig.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WorkspaceWidgetConfig.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/workspaceHeader/WorkspaceHeader.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/workspaceHeader/WorkspaceHeaderTagManager.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace.graphql
Labels: filigran team

#10355 [backend] add NLQ query telemetry count (#9751)
  opencti-platform/opencti-graphql/src/database/ai-llm.ts
  opencti-platform/opencti-graphql/src/manager/telemetryManager.ts
  opencti-platform/opencti-graphql/src/telemetry/TelemetryMeterManager.ts
Labels: filigran team
