Repository OpenCTI-Platform/opencti, pull requests merged in 2025-07, with the labels that each got.

#11555 [backend] Add check in identifier for potential deduplication
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/schema/identifier.js
Labels: filigran team

#11532 [frontend] Update dependency vite to v7 (#3395)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#11560 [frontend] No filters reset when changing between lines/cards view (#8428)
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
Labels: filigran team

#11416 [backend] launch container sharing task with system user instead of context user (#11570)
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/utils/access.ts
Labels: filigran team

#11506 [ci] Improve end to end test execution for settings validation (#11519)
  opencti-platform/opencti-front/tests_e2e/settings/parameters.spec.ts
  opencti-platform/opencti-front/tests_e2e/utils.ts
Labels: filigran team

#11576 [frontend] prevent empty event_types to crash event edition (#11538)
  opencti-platform/opencti-front/src/private/components/entities/events/EventEditionOverview.jsx
Labels: filigran team

#11537 [frontend] Verify did not work on Edit on switching to inline CSVMapper #11524
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvInlineMapperForm.tsx
Labels: filigran team

#11591 [frontend] Prevent .pif from direct download
  opencti-platform/opencti-front/src/private/components/common/files/FileLine.tsx
Labels: filigran team

#11584 [frontend/backend] fintel template variable name checker should allow - and _ (#11392)
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplateWidgetsSidebar.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetAttributesInput.tsx
  opencti-platform/opencti-front/src/private/components/widgets/useWidgetConfigValidateForm.tsx
  opencti-platform/opencti-graphql/src/modules/fintelTemplate/fintelTemplate-domain.ts
  opencti-platform/opencti-graphql/src/utils/syntax.js
Labels: filigran team

#11498 [frontend] refetch entity history every 5s (#11249)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistory.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectHistoryLines.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectLatestHistory.tsx
Labels: filigran team

#11587 [frontend] Enable merge for same entity types in Victimology section (#11412)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#11579 [backend] Add prometheus metric to monitor the number of sent emails (#11578)
  opencti-platform/opencti-graphql/src/config/tracing.ts
  opencti-platform/opencti-graphql/src/database/smtp.js
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/modules/auth/auth-domain.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-domain.ts
Labels: filigran team

#11588 [backend] Indicator should take created as valid_from as fallback (#9866)
  opencti-platform/opencti-graphql/tests/02-integration/01-database/indicator-domain-test.ts
  opencti-platform/opencti-graphql/tests/utils/syncCountHelper.ts
Labels: filigran team

#11449 [backend] Improve input resolve refs performance not fetching the denormalization #11447
  opencti-platform/opencti-front/tests_e2e/navigation/navigation.spec.ts
  opencti-platform/opencti-graphql/src/database/draft-utils.js
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/attackPattern.ts
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/http/httpAuthenticatedContext.js
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/draftWorkspace/draftWorkspace-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-json-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-rss-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-collection-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-resolver.ts
  opencti-platform/opencti-graphql/src/modules/organization/organization-resolver.ts
  opencti-platform/opencti-graphql/src/modules/pir/pir-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-resolver.ts
  opencti-platform/opencti-graphql/src/resolvers/attackPattern.js
  opencti-platform/opencti-graphql/src/resolvers/backgroundTask.js
  opencti-platform/opencti-graphql/src/resolvers/connector.js
  opencti-platform/opencti-graphql/src/resolvers/file.js
  opencti-platform/opencti-graphql/src/resolvers/group.js
  opencti-platform/opencti-graphql/src/resolvers/indexedFile.js
  opencti-platform/opencti-graphql/src/resolvers/internalRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/log.js
  opencti-platform/opencti-graphql/src/resolvers/stix.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixRefRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixSightingRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/subType.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/src/types/user.d.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#11586 [frontend] Fix html-to-image usage for Firefox (#11592)
  opencti-platform/opencti-front/src/utils/Image.js
Labels: filigran team

#11564 [frontend] View nested objects in the `Network Traffic` overview
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipPopover.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableDetails.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableNestedEntities.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableNestedEntities.tsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableNestedEntitiesLines.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableNestedEntitiesTable.tsx
Labels: filigran team

#11321 [backend] readMe improvements in modules directory
  opencti-platform/opencti-graphql/src/modules/README.md
Labels: filigran team

#11620 [backend] save session when opt login (#11619)
  opencti-platform/opencti-graphql/src/domain/user.js
Labels: filigran team

#11552 [Backend/frontend] Add generation licences file + verification that no "unsupported" licenses are installed
  .drone.yml
  .gitignore
  generatelicenseconfig.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/yarn.lock
  scripts/generate-licenses.sh
Labels: filigran team

#11562 [backend] Fix webhook duplicates
  opencti-platform/opencti-graphql/src/manager/notificationManager.ts
Labels: filigran team

#11612 [backend] fix relationship name duplicated in update and delete events (#10939)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#11598 [backend] Error when removing an entity from a Task (#11256)
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/task/task.graphql
  opencti-platform/opencti-graphql/src/modules/task/task.ts
Labels: filigran team

#11641 Link XTMHub and OCTI through tab #11295
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/ConfirmationDialog.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/EnrollmentInstructions.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/EnrollmentLoader.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/XtmHubSettings.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/XtmHubTab.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/useExternalTab.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/hooks/useGranted.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/data-initialization.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/initialization.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/data-initialization-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/elasticSearch-test.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/role-test.js
Labels: filigran team

#11575 [backend] Fix perf issue due to large sync operation (#11390)
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
  opencti-platform/opencti-graphql/src/utils/data-processing.ts
Labels: filigran team

#11687 [CI] Automate deployment on PIR test instance
  .circleci/config.yml
Labels: filigran team

#11621 [backend/frontend] Create service account (#8754)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/it.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/Policies.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/tests_e2e/model/form/userForm.pageModel.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/types/user.d.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/access-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/user-domain-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.ts
  opencti-platform/opencti-graphql/tests/utils/syncCountHelper.ts
Labels: filigran team

#11716 [backend] Fix error in generateUpdateMessage (#11713)
  opencti-platform/opencti-graphql/src/database/generate-message.js
Labels: filigran team

#11733 [frontend] Fix links color
  opencti-platform/opencti-front/src/components/ThemeDark.ts
  opencti-platform/opencti-front/src/components/ThemeLight.ts
Labels: filigran team

#11679 [frontend/backend] Enroll OCTI Instance with XTM Hub (#11295)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/it.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/Root.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/EnrollmentSuccess.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/XtmHubSettings.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/XtmHubTab.tsx
  opencti-platform/opencti-front/src/private/components/settings/xtm-hub/useExternalTab.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/src/utils/settings.helper.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/settings-test.ts
Labels: filigran team

#11605 [backend] feat(search): support defanged IOCs in global search (#3142)(#8799)(#11213)
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/utils/refang.js
  opencti-platform/opencti-graphql/tests/01-unit/utils/refang-test.ts
Labels: community

#11743 [frontend] PIR UI improvements (#11149)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/pir/PirFiltersDisplay.tsx
  opencti-platform/opencti-front/src/private/components/pir/pir_analyses/PirAnalyses.tsx
  opencti-platform/opencti-front/src/private/components/pir/pir_overview/PirOverviewCountFlagged.tsx
  opencti-platform/opencti-front/src/private/components/pir/pir_overview/PirOverviewDetails.tsx
  opencti-platform/opencti-front/src/private/components/pir/pir_overview/PirOverviewHistory.tsx
  opencti-platform/opencti-front/src/private/components/pir/pir_overview/PirOverviewTopSources.tsx
  opencti-platform/opencti-front/src/private/components/pir/pir_overview/PirThreatMap.tsx
Labels: filigran team

#11757 [backend] Improve input resolve refs performance not fetching the denormalization (#11726) (#11447)
  opencti-platform/opencti-front/tests_e2e/navigation/navigation.spec.ts
  opencti-platform/opencti-graphql/src/database/draft-utils.js
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/attackPattern.ts
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/http/httpAuthenticatedContext.js
  opencti-platform/opencti-graphql/src/modules/deleteOperation/deleteOperation-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/draftWorkspace/draftWorkspace-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-json-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-rss-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-collection-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-resolver.ts
  opencti-platform/opencti-graphql/src/modules/organization/organization-resolver.ts
  opencti-platform/opencti-graphql/src/modules/pir/pir-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/publicDashboard/publicDashboard-resolvers.ts
  opencti-platform/opencti-graphql/src/modules/workspace/workspace-resolver.ts
  opencti-platform/opencti-graphql/src/resolvers/attackPattern.js
  opencti-platform/opencti-graphql/src/resolvers/backgroundTask.js
  opencti-platform/opencti-graphql/src/resolvers/connector.js
  opencti-platform/opencti-graphql/src/resolvers/file.js
  opencti-platform/opencti-graphql/src/resolvers/group.js
  opencti-platform/opencti-graphql/src/resolvers/indexedFile.js
  opencti-platform/opencti-graphql/src/resolvers/internalRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/log.js
  opencti-platform/opencti-graphql/src/resolvers/stix.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreObject.js
  opencti-platform/opencti-graphql/src/resolvers/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixRefRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/stixSightingRelationship.js
  opencti-platform/opencti-graphql/src/resolvers/subType.js
  opencti-platform/opencti-graphql/src/resolvers/user.js
  opencti-platform/opencti-graphql/src/types/user.d.ts
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/file-storage-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#11766 [backend](test) add composer mock and test mutations
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/connector-composer-test.ts
  opencti-platform/opencti-graphql/tests/utils/XTMComposerMock.ts
Labels: filigran team

#11657 [frontend] fix missing name for target based-on relationships (#11600)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/SimpleStixObjectOrStixRelationshipStixCoreRelationshipLine.jsx
Labels: filigran team

#11738 [frontend] fix Note content default value field (#11702)
  opencti-platform/opencti-front/src/private/components/common/form/DefaultValueField.tsx
Labels: filigran team

#11777 [frontend] improve workspace Relay code
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceDuplicationDialog.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceKebabMenu.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopoverContainerQuery.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/Workspaces.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WorkspaceWidgetConfig.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WorkspaceWidgetPopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/workspaceHeader/WorkspaceHeader.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/workspaceHeader/WorkspaceHeaderTagManager.tsx
Labels: filigran team

#11461 [backend/frontend] Improve SSO error UI feedback when local strategy is disabled (#11353)
  opencti-platform/opencti-front/src/public/components/Login.tsx
  opencti-platform/opencti-front/src/public/components/LoginForm.tsx
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
Labels: community

#11601 [backend/frontend] add new action types for handling users in background tasks (#3343)
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableHeaders.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/profile/Notifications.tsx
  opencti-platform/opencti-front/src/private/components/settings/Users.jsx
  opencti-platform/opencti-front/src/private/components/settings/Users.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupEditionUsers.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/SettingsOrganizationUserCreation.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/SettingsOrganizationUserLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/SettingsOrganizationUsers.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/SettingsOrganizationUsersLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UsersLines.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-front/tests_e2e/model/form/userForm.pageModel.ts
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/domain/filterKeysSchema.ts
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-utils.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/backgroundTask-common-test.ts
Labels: filigran team, multi-repository

#11751 [frontend] "Shared" column in custom dashboard is misleading (#11663)
  opencti-platform/opencti-front/lang/back/ru.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
Labels: filigran team

#11651 [backend] add more tests on observables hashes (#11301)
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/observables-hashes-test.ts
  opencti-platform/opencti-graphql/tests/utils/syncCountHelper.ts
Labels: filigran team

#11793 [frontend] fix users effective_confidence_level render (#3343)
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
Labels: filigran team

#11776 [frontend] create entity button in Sighting creation from entity (#11754)
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreationFromEntityStixDomainObjectsLines.jsx
Labels: filigran team

#11735 [backend] Fix update feed crashes on recent platforms
  opencti-platform/opencti-graphql/src/domain/feed.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/csvFeed-test.ts
Labels: filigran team

#11791 [frontend] fix JSON Mapper 'Representations for relationship'
  opencti-platform/opencti-front/src/private/components/data/jsonMapper/JsonMapperForm.tsx
Labels: filigran team

#11742 [frontend] fix popover menu for enrichment (#11708)
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectHeader.jsx
Labels: filigran team

#11636 [frontend] Remove credential fetching in feeds (#10886)
  opencti-platform/opencti-front/src/components/PasswordTextField.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEditionContainer.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiEdition.jsx
  opencti-platform/opencti-front/src/private/components/data/ingestionTaxii/IngestionTaxiiPopover.tsx
  opencti-platform/opencti-front/src/private/components/data/sync/SyncEdition.jsx
  opencti-platform/opencti-front/src/utils/ingestionAuthentificationUtils.ts
  opencti-platform/opencti-graphql/src/domain/connector.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-common.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-taxii-resolver.ts
  opencti-platform/opencti-graphql/src/resolvers/connector.js
  opencti-platform/opencti-graphql/src/types/connector.d.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-taxii-test.ts
Labels: filigran team

#11769 [frontend] improve investigation rollbacks (#11565)
  opencti-platform/opencti-front/src/components/graph/components/GraphToolbarExpandTools.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjectsLines.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/dialog/InvestigationRollBackExpandDialog.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/utils/investigationStorage.ts
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/utils/setStackDataInSessionStorage/setStackDataInSessionStorage.test.ts
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/utils/setStackDataInSessionStorage/setStackDataInSessionStorage.ts
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/utils/useInvestigationState.ts
  opencti-platform/opencti-front/src/utils/sessionStorage.test.ts
  opencti-platform/opencti-front/src/utils/sessionStorage.ts
Labels: filigran team

#11775 [backend] Display all internal connectors (#11666)
  opencti-platform/opencti-graphql/src/connector/connector-domain.ts
  opencti-platform/opencti-graphql/src/database/rabbitmq.js
  opencti-platform/opencti-graphql/src/database/repository.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/connector-test.ts
Labels: filigran team

#11806 [frontend/backend] Prevent making several actions on the same key in the same task (#11798)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/tests/01-unit/domain/backgroundTask-common-test.ts
Labels: filigran team

#11736 [frontend] possibility to submit on enter keydown (#8648)
  opencti-platform/opencti-front/src/components/TextField.tsx
Labels: filigran team

#11819 [frontend] allow italian language and add missing translation (#11817)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-graphql/src/domain/user.js
Labels: filigran team

#11767 [backend/frontend] Update CSV feed creation with service_account (#8754)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/ru.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreationUserHandling.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEditionUserHandling.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupSetDefaultGroupForIngestionUsers.tsx
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/ingestion-csv-domain-test.ts
  opencti-platform/opencti-graphql/tests/utils/syncCountHelper.ts
Labels: filigran team

#11815 [frontend] [Dashboard] “Bookmark” visualization broken (#10949)
  opencti-platform/opencti-front/src/private/components/widgets/WidgetFilters.tsx
Labels: filigran team

#11844 [frontend](chore) migrate connectors page from jsx to tsx (#7328)
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.tsx
  opencti-platform/opencti-front/src/utils/Connector.tsx
Labels: filigran team

#11758 [frontend] add attributes in widget column selection for Vulnerabilities and Organizations (#11546)
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectsList.jsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetListsDefaultColumns.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsList.tsx
Labels: filigran team

#11656 [frontend] feat(markdown): add breakWords prop for long string handling (#10430)
  opencti-platform/opencti-front/src/components/MarkdownDisplay.tsx
Labels: filigran team
