Repository OpenCTI-Platform/opencti, pull requests merged in 2025-02, with the labels that each got.

#9798 [backend/frontend] sending dissemination email synchronously (#5551)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesDissemination.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFileExportButton.tsx
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationLists.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/backgroundTask-common.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/listener/UserActionListener.ts
  opencti-platform/opencti-graphql/src/manager/activityListener.ts
  opencti-platform/opencti-graphql/src/manager/taskManager.js
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-domain.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-resolver.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList.graphql
Labels: filigran team

#9789 [frontend/backend] Fintel templates improvements for 6.5 (#8336)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/FilterValuesContent.tsx
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableContext.tsx
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectFileExportForm.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/SubType.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplateHeader.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplateTabs.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplateWidgetsList.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplateWidgetsSidebar.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetAttributesInput.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetConfig.tsx
  opencti-platform/opencti-front/src/private/components/widgets/WidgetConfigContext.tsx
  opencti-platform/opencti-front/src/utils/widget/widgetUtils.tsx
  opencti-platform/opencti-graphql/src/modules/fintelTemplate/fintelTemplate-domain.ts
  opencti-platform/opencti-graphql/src/utils/fintelTemplate/__executiveSummary.template.ts
  opencti-platform/opencti-graphql/src/utils/fintelTemplate/__fintelTemplateWidgets.ts
  opencti-platform/opencti-graphql/src/utils/fintelTemplate/__incidentCase.template.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/fintelTemplate-test.ts
Labels: filigran team

#9801 [frontend] Detect datatable parent height changes to auto adapt
  opencti-platform/opencti-front/src/components/dataGrid/components/DataTableBody.tsx
Labels: filigran team

#9782 [backend/frontend] remove FF dissemination list (#5551)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
  opencti-platform/opencti-front/src/private/components/settings/AccessesMenu.tsx
  opencti-platform/opencti-front/src/private/components/settings/roles/RoleEditionCapabilities.tsx
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-domain.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList.ts
Labels: filigran team

#9755 [backend] Fix null for objectParticipant in Task (#9752)
  opencti-platform/opencti-graphql/src/modules/task/task-resolvers.ts
Labels: filigran team

#9808 Fix page container usage for DataTable filters
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/PageContainer.tsx
Labels: filigran team

#9807 [frontend] fix file name in fintel template export form (#8336)
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectFileExportForm.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplatePopover.tsx
  opencti-platform/opencti-graphql/src/utils/fintelTemplate/__executiveSummary.template.ts
Labels: filigran team

#9737 [frontend/backend] remove Fintel Templates Feature Flag (#8336)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFiles.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/SubType.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplate.tsx
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/initialization.js
  opencti-platform/opencti-graphql/src/modules/fintelTemplate/fintelTemplate-domain.ts
Labels: filigran team

#9810 [backend] Improve template notification verifications (#9795)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/src/modules/notifier/notifier-domain.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/notifier-ejs-test.ts
Labels: filigran team

#9804 [frontend] translate types in CSV feeds list (#9771)
  opencti-platform/opencti-front/src/private/components/data/feeds/FeedLine.jsx
Labels: filigran team

#9791 [backend] now also send event_id for events sent to worker coming from stream (#9824)
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/redis.ts
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
  opencti-platform/opencti-graphql/src/manager/playbookManager.ts
  opencti-platform/opencti-graphql/src/manager/syncManager.js
  opencti-platform/opencti-graphql/src/types/user.d.ts
  opencti-platform/opencti-graphql/src/utils/format.js
Labels: filigran team

#9827 [backend] Adding some allowed function in webhook (#9795)
  opencti-platform/opencti-graphql/config/default.json
  opencti-platform/opencti-graphql/tests/01-unit/domain/notifier-ejs-test.ts
Labels: filigran team

#9802 [frontend] add 'search' filter operator translation (#9772)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
Labels: filigran team

#9826 [frontend] Truncate the value of observables in Graph (#9588)
  opencti-platform/opencti-front/src/utils/Graph.js
Labels: filigran team

#9844 [frontend] fix the background in the 'create multiple entities' dialog box
  opencti-platform/opencti-front/src/components/fields/BulkTextField/BulkTextModal.tsx
Labels: filigran team

#9020 [frontend] Add support for dynamic configurable required fields to Cases
  opencti-platform/opencti-front/src/components/SimpleMarkdownField.jsx
  opencti-platform/opencti-front/src/components/fields/MarkdownField.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/CaseIncidentEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/FeedbackCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/feedbacks/FeedbackEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/CaseTaskCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TaskCreation.tsx
  opencti-platform/opencti-front/src/private/components/cases/tasks/TasksEditionOverview.tsx
  opencti-platform/opencti-graphql/src/modules/case/feedback/feedback.ts
  opencti-platform/opencti-graphql/src/modules/task/task.ts
Labels: community

#9843 [backend] Improve markings edition control
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/domain/stixObjectOrStixRelationship.ts
  opencti-platform/opencti-graphql/tests/02-integration/01-database/disseminationList-test.ts
Labels: filigran team

#9870 [frontend] fix malware variants missing from relationships (#9531)
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/EntityStixCoreRelationshipLineAll.jsx
Labels: filigran team

#9876 [backend] fix minimal version compatibility for fintel template import (#8336)
  opencti-platform/opencti-graphql/src/modules/fintelTemplate/fintelTemplate-domain.ts
Labels: filigran team

#9715 [backend] Improve application stopping time (#9740)
  opencti-platform/opencti-graphql/.eslintrc.js
  opencti-platform/opencti-graphql/src/back.js
  opencti-platform/opencti-graphql/src/config/providers.js
  opencti-platform/opencti-graphql/src/database/engine.js
  opencti-platform/opencti-graphql/src/database/migration.js
  opencti-platform/opencti-graphql/src/database/session.js
  opencti-platform/opencti-graphql/src/database/sessionStore-redis.js
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/src/domain/settings.js
  opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
  opencti-platform/opencti-graphql/src/domain/stixSightingRelationship.js
  opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/http/httpServer.js
  opencti-platform/opencti-graphql/src/instrumentation.js
  opencti-platform/opencti-graphql/src/lock/child-lock.manager.ts
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
  opencti-platform/opencti-graphql/src/manager/publisherManager.ts
  opencti-platform/opencti-graphql/src/manager/syncManager.js
Labels: filigran team

#9853 [frontend] translate entity type in Fintel template Breadcrumbs header path (#9840)
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplateHeader.tsx
Labels: filigran team

#9911 [frontend] Spacing is not correct in dissemination list table between search and headers (#9880)
  opencti-platform/opencti-front/src/components/PageContainer.tsx
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationLists.tsx
Labels: filigran team

#9926 [frontend] merge icon available in global search for entities with same type (#9894)
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
Labels: filigran team

#9809 [backend] Check authorized members for element access (#4538)
  opencti-platform/opencti-graphql/src/utils/access.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/access-test.ts
Labels: filigran team

#9901 [frontend] correctly display observable types in filters list (#9857)
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
Labels: filigran team

#9918 [frontend] Align column headings in the connectors view (#9556)
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorsStatus.tsx
Labels: filigran team

#9873 [frontend] draft UX improvements
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/Index.tsx
  opencti-platform/opencti-front/src/private/components/common/draft/DraftBlock.tsx
  opencti-platform/opencti-front/src/private/components/common/draft/DraftChip.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationships.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectCreation.jsx
  opencti-platform/opencti-front/src/private/components/data/DataTableToolBar.jsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftContextBanner.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftEntities.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRelationships.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftRoot.tsx
  opencti-platform/opencti-front/src/private/components/drafts/DraftSightings.tsx
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/nav/TopBar.tsx
  opencti-platform/opencti-graphql/src/modules/draftWorkspace/draftWorkspace-domain.ts
Labels: filigran team

#9941 [frontend] fix usage of geologica (#9940)
  opencti-platform/opencti-front/src/components/ThemeDark.ts
  opencti-platform/opencti-front/src/components/ThemeLight.ts
  opencti-platform/opencti-front/src/private/components/common/danger_zone/DangerZoneBlock.tsx
  opencti-platform/opencti-front/src/private/components/common/draft/DraftBlock.tsx
Labels: filigran team

#9924 [backend] Improve deletion of element with hundreds of thousands relationships (#9923)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#9883 [client] Add markings support for workbench
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileContent.jsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileCreator.tsx
  opencti-platform/opencti-front/src/private/components/common/files/workbench/WorkbenchFileLine.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportContent.jsx
  opencti-platform/opencti-front/src/private/components/data/import/ImportWorkbenchesContent.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/database/file-storage.js
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/domain/file.js
  opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
  opencti-platform/opencti-graphql/src/domain/stixObjectOrStixRelationship.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/resolvers/file.js
  opencti-platform/opencti-graphql/src/utils/access.ts
Labels: filigran team

#9963 [backend] Improve notification template verifications (#9795)
  opencti-platform/opencti-graphql/src/modules/notifier/notifier-domain.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/notifier-ejs-test.ts
Labels: filigran team

#9964 [backend] Fix CSV mapper creation if name exists (#9962)
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper.ts
Labels: filigran team

#9973 [frontend] fix UI in exclusion lists (#9971)
  opencti-platform/opencti-front/src/components/PageContainer.tsx
  opencti-platform/opencti-front/src/private/components/settings/exclusion_lists/ExclusionLists.tsx
Labels: filigran team

#9975 [frontend] fix tool edition (#9970)
  opencti-platform/opencti-front/src/components/AutocompleteField.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolDetails.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/common/form/KillChainPhasesField.jsx
  opencti-platform/opencti-front/src/private/components/common/form/ObjectMarkingField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/StatusField.jsx
Labels: filigran team

#9797 [frontend] Modified left padding for submenus to align with parent text
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
Labels: community

#9969 [backend] Prevent event loop CPU blocking when processing applyUpdate in container rules (#9936)
  opencti-platform/opencti-graphql/src/rules/containerWithRefsBuilder.ts
  opencti-platform/opencti-graphql/src/utils/data-processing.ts
  opencti-platform/opencti-graphql/tests/01-unit/utils/data-processing-test.ts
Labels: filigran team

#9968 [backend] Side deletions of ref relationships can lead to updated_at upgrade (#9944)
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#9879 [backend] make exclusion list check case insensitive (#9877)
  opencti-platform/opencti-graphql/src/utils/exclusionLists.ts
Labels: filigran team

#9274 [frontend/backend] Possibility to prevent default group assignation at user creation (#9234)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/form/GroupField.tsx
  opencti-platform/opencti-front/src/private/components/settings/Users.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserCreation.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/user-test.ts
Labels: filigran team

#9946 [frontend] Enable label click actions in the Knowledge view indicator list (#9292)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicators.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/views/indicators/EntityStixCoreRelationshipsIndicatorsEntitiesView.tsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/StixDomainObjectIndicatorLine.jsx
  opencti-platform/opencti-front/src/private/components/observations/indicators/StixDomainObjectIndicatorsLines.jsx
Labels: filigran team

#9868 [frontend] Add 'All entities' view in Knowledge section, which lists all entities & relationships linked to the entity
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/channels/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/tools/ToolKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/Root.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectKnowledgeBar.tsx
  opencti-platform/opencti-front/src/private/components/entities/events/EventKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/IndividualKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/OrganizationKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/organizations/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/sectors/SectorKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/entities/systems/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/systems/SystemKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/locations/administrative_areas/AdministrativeAreaKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/locations/cities/CityKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/locations/countries/CountryKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/locations/positions/PositionKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/locations/positions/Root.tsx
  opencti-platform/opencti-front/src/private/components/locations/regions/RegionKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/observations/infrastructures/InfrastructureKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/AttackPatternKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/Root.tsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/NarrativeKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/techniques/narratives/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/Root.tsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualKnowledge.tsx
  opencti-platform/opencti-front/src/utils/Relation.ts
Labels: filigran team

#9991 [backend/frontend] Fix generation scenario from threat and victime entities (#9987)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSimulationResult.jsx
Labels: filigran team

#9988 [backend] add Contains filter for Relationships (#9985)
  opencti-platform/opencti-graphql/src/domain/filterKeysSchema.ts
Labels: filigran team

#10005 [frontend] small UI fixes
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/Management.tsx
  opencti-platform/opencti-front/src/private/components/settings/dissemination_lists/DisseminationLists.tsx
Labels: filigran team

#9515 [backend] Change marking values order: TLP:AMBER+STRICT to be hierarchically greater than TLP:AMBER (#9450)
  opencti-platform/opencti-graphql/src/database/data-initialization.js
Labels: filigran team

#9998 [frontend] Align the height between EnterpriseEdition and Danger zone labels
  opencti-platform/opencti-front/src/private/components/common/entreprise_edition/EEChip.tsx
Labels: filigran team

#8960 [frontend] Add support for dynamic configurable required fields to Events
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentEditionDetails.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataCreation.tsx
  opencti-platform/opencti-front/src/private/components/events/observed_data/ObservedDataEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreationForm.js
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipEditionOverview.tsx
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
Labels: community

#10014 [frontend] Fix spacing before search bar of 'Rules engine' (#9972)
  opencti-platform/opencti-front/src/private/components/settings/Rules.jsx
Labels: filigran team

#9874 [backend] change how we check if need to fetch rss feed (#9836)
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
Labels: filigran team

#9942 [backend/frontend] Improve readability of works in the connector interface
  opencti-platform/opencti-front/src/private/components/data/connectors/Connector.jsx
  opencti-platform/opencti-front/src/private/components/data/connectors/ConnectorWorks.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
Labels: filigran team

#10010 [frontend] Only accessible markings visible in filters (#10006)
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
Labels: filigran team

#9999 [frontend] chip and menu buttons aligned (#9616)
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectHeader.jsx
Labels: filigran team

#9855 [frontend] improve entity type filter detection to display tool bar actions (#9828)
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/tests/filtersUtils.test.tsx
Labels: filigran team

#10054 [frontend] Clicking on the burger button in the playbook list view open the playbook (#10031)
  opencti-platform/opencti-front/src/private/components/data/playbooks/PlaybookPopover.jsx
Labels: filigran team

#10055 [frontend] Impossible to share Note with Organization (#10030)
  opencti-platform/opencti-front/src/private/components/analyses/notes/Root.jsx
Labels: filigran team

#10056 [frontend] replace APP_SCRIPT_SNIPPET in dev mode
  opencti-platform/opencti-front/builder/dev/dev.js
  opencti-platform/opencti-front/vite.config.mts
Labels: filigran team

#10001 [frontend] Redirect to the All view for each diamond model view with the needed filters
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/getFilterFromEntityTypeAndNodeType.ts
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/test/getFilterFromEntity.test.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeAdversary.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeCapabilities.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeInfrastructure.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/diamond/types/nodes/NodeVictimology.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetKnowledge.jsx
  opencti-platform/opencti-front/src/utils/Relation.ts
Labels: filigran team

#9875 [backend/frontend] Disseminate HTML files (#8949)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesDissemination.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectContentFilesList.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/manager/telemetryManager.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList-domain.ts
  opencti-platform/opencti-graphql/src/modules/disseminationList/disseminationList.graphql
  opencti-platform/opencti-graphql/src/telemetry/TelemetryMeterManager.ts
  opencti-platform/opencti-graphql/src/utils/emailTemplates/basicEmailTemplate.ts
  opencti-platform/opencti-graphql/src/utils/emailTemplates/octiEmailTemplate.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/disseminationListResolver-test.ts
Labels: filigran team

#10050 [frontend] Refacto graphs - chunk 2 : all knowledge graphs (#9298)
  opencti-platform/opencti-front/src/components/range_slider/RangeSlider.jsx
  opencti-platform/opencti-front/src/components/range_slider/components/Handle.jsx
  opencti-platform/opencti-front/src/components/range_slider/components/KeyboardHandle.jsx
  opencti-platform/opencti-front/src/components/range_slider/components/SliderRail.jsx
  opencti-platform/opencti-front/src/components/range_slider/components/Tick.jsx
  opencti-platform/opencti-front/src/components/range_slider/components/Track.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphQuery.js
  opencti-platform/opencti-front/src/private/components/analyses/groupings/Root.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/useGroupingKnowledgeGraphAddRelation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/useGroupingKnowledgeGraphDeleteRelation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/useGroupingKnowledgeGraphEdit.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/Root.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphQuery.js
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/useIncidentKnowledgeGraphAddRelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/useIncidentKnowledgeGraphDeleteRelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/useIncidentKnowledgeGraphEdit.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphQuery.js
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/useCaseRfiKnowledgeGraphAddRelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/useCaseRfiKnowledgeGraphDeleteRelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/useCaseRfiKnowledgeGraphEdit.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraph.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphQuery.js
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/useCaseRftKnowledgeGraphAddRelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/useCaseRftKnowledgeGraphDeleteRelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/useCaseRftKnowledgeGraphEdit.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreation.jsx
  opencti-platform/opencti-front/src/private/components/events/stix_sighting_relationships/StixSightingRelationshipCreation.jsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbar.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarContentTools.tsx
  opencti-platform/opencti-front/src/utils/graph/graph.types.ts
  opencti-platform/opencti-front/src/utils/graph/utils/graphUtils.ts
  opencti-platform/opencti-front/src/utils/graph/utils/useGraphInteractions.ts
Labels: filigran team

#10075 [frontend] Mandatory file for Artifact creation (#8794)
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
Labels: filigran team

#10003 [frontend] 'In regards of' filter tooltip for not detected relationships (#9909)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/FilterIconButtonContainer.tsx
  opencti-platform/opencti-front/src/components/filters/FilterValues.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/tests/filtersUtils.test.tsx
  opencti-platform/opencti-graphql/src/migrations/1733912620469-clean-deprecated-rels.js
Labels: do not merge, filigran team

#10103 [frontend/backend] add new filter capabilities to playbooks
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-constants.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-stix/stix-testers.ts
Labels: filigran team

#10093 [frontend] Refactoring of correlation graphs (#9298)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analyses/groupings/useGroupingKnowledgeCorrelationEdit.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/useReportKnowledgeCorrelationEdit.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/useIncidentKnowledgeCorrelationEdit.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/useCaseRfiKnowledgeCorrelationEdit.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeCorrelation.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeCorrelation.tsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledgeGraphBar.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/useCaseRftKnowledgeCorrelationEdit.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerAddStixCoreObjectsInLine.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/KnowledgeCorrelationQuery.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromKnowledgeGraph.tsx
  opencti-platform/opencti-front/src/utils/graph/Graph.tsx
  opencti-platform/opencti-front/src/utils/graph/GraphContext.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbar.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarContentTools.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarCorrelationTools.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarEditObject.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarFilterTools.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarRemoveConfirm.tsx
  opencti-platform/opencti-front/src/utils/graph/components/GraphToolbarSelectTools.tsx
  opencti-platform/opencti-front/src/utils/graph/graph.types.ts
  opencti-platform/opencti-front/src/utils/graph/utils/graphTimeRange.ts
  opencti-platform/opencti-front/src/utils/graph/utils/graphUtils.ts
  opencti-platform/opencti-front/src/utils/graph/utils/useGraphFilter.ts
  opencti-platform/opencti-front/src/utils/graph/utils/useGraphInteractions.ts
  opencti-platform/opencti-front/src/utils/graph/utils/useGraphPainter.ts
  opencti-platform/opencti-front/src/utils/graph/utils/useGraphParser.ts
Labels: filigran team

#10105 [frontend] "all" counter updated (#7879)
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectKnowledgeBar.tsx
Labels: filigran team
