Repository OpenCTI-Platform/opencti, pull requests merged in 2025-06, with the labels that each got.

#11139 [frontend] fix css for relationships paper div (#10985)
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipOverview.jsx
Labels: filigran team

#11141 [backend] Allow marking direct marking deletion (#11112)
  opencti-platform/opencti-graphql/src/domain/group.js
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/group-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/domainQueryHelper.ts
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#11176 [backend] fix current_state_date date format (#11132)
  opencti-platform/opencti-graphql/src/manager/ingestionManager.ts
Labels: filigran team

#11180 [backend] fix ResourceNotFoundError handling (#10734)
  opencti-platform/opencti-graphql/src/config/errors.js
  opencti-platform/opencti-graphql/src/database/xtm-obas.ts
  opencti-platform/opencti-graphql/src/domain/stixCoreObject.js
Labels: filigran team

#10973 [dependencies] prepare redis updates to major 8 (#6975)
  .drone.yml
  opencti-platform/opencti-dev/docker-compose.yml
  opencti-platform/opencti-graphql/tests/02-integration/01-database/redis-test.js
Labels: filigran team

#11009 [frontend] fix dashboard export to pdf fails when containing donuts (#10786)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/components/ExportButtons.jsx
  opencti-platform/opencti-front/src/utils/Image.js
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboardDetails.pageModel.ts
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#11190 [backend] Fix add creator stream message (#11177)
  opencti-platform/opencti-graphql/src/database/generate-message.js
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: filigran team

#11189 Improve automatic translations scripts
  opencti-platform/opencti-front/lang/back/it.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/script/auto-translate.js
Labels: filigran team

#11202 [frontend] Fix spacing in import files dialog free textarea and stepper (#10795)
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesDialog.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesFreeText.tsx
  opencti-platform/opencti-front/src/private/components/common/files/import_files/ImportFilesToggleMode.tsx
Labels: filigran team

#11192 [backend] new relationship added for channels (#8497)
  opencti-platform/opencti-front/src/private/components/arsenal/channels/ChannelKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectKnowledgeBar.tsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualKnowledge.tsx
  opencti-platform/opencti-graphql/src/database/stix.ts
  opencti-platform/opencti-graphql/src/modules/channel/channel.ts
Labels: filigran team

#11217 [frontend] SavedFilters (#10383)
  opencti-platform/opencti-front/src/components/dataGrid/DataTableFilters.tsx
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilterSelection.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/ListFilters.tsx
Labels: filigran team

#11218 [frontend] Possibility to update stop_time of a nested ref (#10778)
  opencti-platform/opencti-front/src/components/graph/components/GraphToolbarEditObject.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipEdition.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipEdition.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipPopover.jsx
Labels: filigran team

#11236 Align all docker images to node 22 for Drone
  .drone.yml
Labels: filigran team

#11211 [backend/frontend] - (ServiceAccount): Let the user choose a default group for on the fly user creation (#11047)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/it.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/settings/Policies.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupSetDefaultGroupForIngestionUsers.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/attributes/internalObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/group-test.ts
Labels: filigran team

#11254 [frontend] clear saved filters on changing view like filters (#10383)
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
Labels: filigran team

#11245 [frontend] Fix bulk search with hashes (#9158)
  opencti-platform/opencti-front/src/private/components/SearchBulk.jsx
  opencti-platform/opencti-front/src/private/components/common/bulk/utils/querySearchEntityByText.ts
  opencti-platform/opencti-front/src/utils/defaultRepresentatives.ts
Labels: filigran team

#11208 [frontend] Upgrade Relay to version 19 (#11207)
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/tests_e2e/model/MalwareAnalyses.pageModel.ts
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#10714 [backend] compute decay when revoked is changed(#10299)
  opencti-platform/opencti-graphql/src/modules/indicator/indicator-domain.ts
  opencti-platform/opencti-graphql/src/schema/identifier.js
  opencti-platform/opencti-graphql/tests/02-integration/01-database/indicator-domain-test.ts
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/utils/testQuery.ts
Labels: filigran team

#11266 [frontend] add a fix height to fintel templates datatable
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplatesGrid.tsx
Labels: filigran team

#11257 [backend/frontend] Fixes on Security Platforms (#10452)
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/components/graph/GraphContainerKnowledge.tsx
  opencti-platform/opencti-front/src/components/graph/utils/graphImages.ts
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.tsx
  opencti-platform/opencti-front/src/private/components/entities/SecurityPlatforms.tsx
  opencti-platform/opencti-front/src/private/components/entities/securityPlatforms/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/securityPlatforms/SecurityPlatform.tsx
  opencti-platform/opencti-front/src/private/components/entities/securityPlatforms/SecurityPlatformAnalysis.tsx
  opencti-platform/opencti-front/src/private/components/entities/securityPlatforms/SecurityPlatformDetails.tsx
  opencti-platform/opencti-front/src/private/components/entities/securityPlatforms/SecurityPlatformEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/entities/securityPlatforms/SecurityPlatformUtils.ts
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.jsx
  opencti-platform/opencti-front/src/private/components/settings/hidden_types/HiddenTypesField.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationAddStixCoreObjectsLine.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/static/images/entities/security-platform.svg
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/securityPlatform/securityPlatform.ts
Labels: filigran team

#11275 [backend] add missing group_ids in user origin (#11273)
  opencti-platform/opencti-graphql/src/domain/user.js
  opencti-platform/opencti-graphql/src/http/httpServer.js
  opencti-platform/opencti-graphql/src/migrations/1742823297618-fix-activity-group_ids.js
Labels: filigran team

#11198 [backend/frontend] background tasks to worker fixes (#10274)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/TaskScope.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectActiveBackgroundTasks.tsx
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/src/domain/rules.ts
  opencti-platform/opencti-graphql/src/domain/stix.js
  opencti-platform/opencti-graphql/src/manager/taskManager.js
Labels: filigran team

#11282 [frontend] improve sharing UX for containers (#10274)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSharing.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectSharingList.tsx
Labels: filigran team

#11197 [backend/frontend] [Outcome-Template - Chunk 4] Add logo of a platform into template (#10284)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/ColorPickerField.jsx
  opencti-platform/opencti-front/src/private/components/common/files/CustomFileUploader.tsx
  opencti-platform/opencti-front/src/private/components/common/form/FintelDesignField.tsx
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectFileExportForm.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_objects/StixCoreObjectFileExport.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesign.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesignCreation.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesignDeletion.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesignEdition.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesignEditionOverview.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesignForm.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesignPopover.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesigns.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplatePreview.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplatePreviewForm.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/src/utils/htmlToPdf/htmlToPdf.ts
  opencti-platform/opencti-front/src/utils/htmlToPdf/utils/constants.ts
  opencti-platform/opencti-front/src/utils/htmlToPdf/utils/pdfBackground.ts
  opencti-platform/opencti-front/src/utils/htmlToPdf/utils/pdfHeader.ts
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign-converter.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign-domain.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign-resolver.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign-types.ts
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign.graphql
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/fintelDesign-test.ts
Labels: filigran team

#11305 [frontend] fix missing feature flag on csv_mapper
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
Labels: filigran team

#11271 [frontend] fix attack pattern matrix (#4948)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/malwares/MalwareKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatterns.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChain.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainMatrix.tsx
  opencti-platform/opencti-front/src/private/components/entities/securityPlatforms/SecurityPlatformKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrix.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrixAccordion.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrixBadge.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrixColumns.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrixColumsElement.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrixShouldCoverIcon.tsx
Labels: filigran team

#11238 [frontend] update workspace header UI (#10985)
  opencti-platform/opencti-front/src/components/ExportButtons.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceKebabMenu.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopover.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopoverContainerQuery.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspacePopoverDeletionMutation.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/Dashboard.jsx
  opencti-platform/opencti-front/src/private/components/workspaces/dashboards/WorkspaceWidgetConfig.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/investigations/InvestigationGraph.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/workspaceHeader/WorkspaceHeader.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/workspaceHeader/WorkspaceHeaderTagManager.tsx
  opencti-platform/opencti-front/tests_e2e/dashboard/dashboard.spec.ts
  opencti-platform/opencti-front/tests_e2e/investigations/createInvestigation.spec.ts
  opencti-platform/opencti-front/tests_e2e/investigations/updateInvestigation.spec.ts
  opencti-platform/opencti-front/tests_e2e/model/AccessRestriction.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/dashboardDetails.pageModel.ts
  opencti-platform/opencti-front/tests_e2e/model/investigationDetails.pageModel.ts
Labels: filigran team

#11315 [frontend] remove Manage Access button from Notes entities (#11312)
  opencti-platform/opencti-front/src/private/components/analyses/notes/Root.jsx
Labels: filigran team

#11314 [frontend] Fintel Design fixes (#10284-fix)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectFileExportForm.tsx
  opencti-platform/opencti-front/src/private/components/settings/CustomizationMenu.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesign.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesignForm.tsx
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesigns.tsx
  opencti-platform/opencti-front/src/private/components/settings/sub_types/fintel_templates/FintelTemplatePreview.tsx
  opencti-platform/opencti-graphql/src/modules/fintelDesign/fintelDesign-domain.ts
Labels: filigran team

#11319 [frontend] Some fixes on headers (#10985)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
  opencti-platform/opencti-front/src/private/components/entities/events/Root.tsx
  opencti-platform/opencti-front/src/private/components/entities/individuals/Root.tsx
Labels: filigran team

#11316 [frontend] Remove entity type right bar in containers (#7574)
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixCyberObservables.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjects.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerStixDomainObjectsLines.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectsRightBar.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservablesRightBar.jsx
  opencti-platform/opencti-front/src/utils/utils.ts
  opencti-platform/opencti-front/tests_e2e/navigation/navigation.spec.ts
Labels: filigran team

#11355 [frontend] Update NestedMenuButton color and move additional settings into it (#9915)
  opencti-platform/opencti-front/src/components/dataGrid/DataTableFilters.tsx
  opencti-platform/opencti-front/src/components/dataGrid/DataTablePagination.tsx
Labels: filigran team

#11356 [frontend] fintel design available for built in html to pdf connector (#10284)
  opencti-platform/opencti-front/src/private/components/common/form/StixCoreObjectFileExportForm.tsx
Labels: filigran team

#11360 [frontend] Add SecurityPlatform on some queries
  opencti-platform/opencti-front/src/private/components/data/entities/EntitiesStixDomainObjectLine.jsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_core_objects/PublicStixCoreObjectsList.tsx
  opencti-platform/opencti-front/src/public/components/dashboard/stix_relationships/PublicStixRelationshipsList.tsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-front/src/utils/outcome_template/engine/stix_core_objects/StixCoreObjectsAttributesQuery.tsx
Labels: filigran team

#11361 [frontend] fix double reload cause by SavedFilters query
  opencti-platform/opencti-front/src/components/saved_filters/SavedFilters.tsx
Labels: filigran team

#11370 [backend/frontend]-(AutoIngestionUser) call existing user only on auto_user (#11047)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/tests/02-integration/01-database/ingestion-csv-domain-test.ts
Labels: filigran team

#11368 [frontend] validate fintel design form (#10284)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/private/components/settings/fintel_design/FintelDesignForm.tsx
  opencti-platform/opencti-front/src/utils/Image.js
  opencti-platform/opencti-front/src/utils/htmlToPdf/htmlToPdf.ts
  opencti-platform/opencti-front/yarn.lock
Labels: filigran team

#11365 [backend] handle new split_bundle_with_expectations signature (#11359)
  opencti-worker/src/worker.py
Labels: filigran team, multi-repository

#11397 [ci] fix prerelease deployment on AWS
  .circleci/config.yml
Labels: filigran team

#11406 [frontend] fix delete a task doesn't refresh (#11405)
  opencti-platform/opencti-front/src/private/components/data/tasks/TasksList.jsx
Labels: filigran team

#11393 [frontend] fix mode only with subtechniques (#4948)
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrixColumns.tsx
Labels: filigran team

#11372 [backend/frontend] Implement new vulnerability data model (#11366)
  opencti-platform/opencti-front/lang/back/de.json
  opencti-platform/opencti-front/lang/back/en.json
  opencti-platform/opencti-front/lang/back/es.json
  opencti-platform/opencti-front/lang/back/fr.json
  opencti-platform/opencti-front/lang/back/it.json
  opencti-platform/opencti-front/lang/back/ja.json
  opencti-platform/opencti-front/lang/back/ko.json
  opencti-platform/opencti-front/lang/back/zh.json
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/package.json
  opencti-platform/opencti-front/src/components/ItemBoolean.jsx
  opencti-platform/opencti-front/src/components/ItemCvssScore.tsx
  opencti-platform/opencti-front/src/components/ItemSeverity.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/AddSoftwares.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/AddSoftwaresLines.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityCreation.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityDetails.tsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionContainer.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionCvss2.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionCvss3.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionCvss4.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityEditionOverview.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilityKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilitySoftwaresHas.jsx
  opencti-platform/opencti-front/src/private/components/arsenal/vulnerabilities/VulnerabilitySoftwaresRemediates.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntityList.jsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/config/schema/opencti.graphql
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/database/middleware.js
  opencti-platform/opencti-graphql/src/database/stix-2-1-converter.ts
  opencti-platform/opencti-graphql/src/database/stix.ts
  opencti-platform/opencti-graphql/src/domain/attribute-utils.ts
  opencti-platform/opencti-graphql/src/domain/vulnerability.js
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/ai/ai-nlq-values.ts
  opencti-platform/opencti-graphql/src/modules/attributes/stixDomainObject-registrationAttributes.ts
  opencti-platform/opencti-graphql/src/types/stix-2-1-sdo.d.ts
  opencti-platform/opencti-graphql/src/types/store.d.ts
  opencti-platform/opencti-graphql/src/utils/filtering/filtering-stix/stix-testers.ts
  opencti-platform/opencti-graphql/src/utils/vulnerabilities.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/attribute-test.js
  opencti-platform/opencti-graphql/yarn.lock
Labels: filigran team, multi-repository

#11410 [frontend/backend] Limit number of results for dynamic regardingOf filter prequery (#11357)
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/components/filters/FilterFiltersInput.tsx
  opencti-platform/opencti-front/src/components/filters/FilterValues.tsx
  opencti-platform/opencti-front/src/components/filters/FilterValuesForDynamicSubKey.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/FilterAutocomplete.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/Filters.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/FiltersElement.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/ListFilters.tsx
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-graphql/src/database/engine.js
Labels: filigran team

#11414 [frontend] fix double loading caused by NestedMenuButton
  opencti-platform/opencti-front/src/components/dataGrid/DataTablePagination.tsx
Labels: filigran team

#11419 [backend] added missing resolving for default values (#11363)
  opencti-platform/opencti-graphql/src/database/middleware.js
Labels: do not merge, filigran team

#11417 [frontend] Relationship icon direction updated in Observable Knowledge tab (#11227)
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableEntitiesLines.jsx
Labels: filigran team

#10990 [frontend] Scrollable User Activity History Tab (#11427)
  opencti-platform/opencti-front/src/components/ItemHistory.tsx
  opencti-platform/opencti-front/src/components/dataGrid/dataTableUtils.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/Root.jsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistoryLine.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistoryLines.tsx
  opencti-platform/opencti-front/src/private/components/settings/users/UserHistoryTab.tsx
Labels: community

#11462 [frontend] fix japanese translations (#11185)
  opencti-platform/opencti-front/lang/front/ja.json
Labels: filigran team

#11444 [frontend/backend] force container summary to output HTML and handle empty entity (#10902)
  opencti-platform/opencti-front/src/private/components/common/ai/AISummaryContainers.tsx
  opencti-platform/opencti-graphql/src/database/ai-llm.ts
  opencti-platform/opencti-graphql/src/domain/container.js
  opencti-platform/opencti-graphql/src/utils/ai/cleanHtmlTags.ts
Labels: filigran team

#11161 [backend] Compute totals to have less counter updates on changes (#11251)
  opencti-platform/opencti-graphql/tests/03-streams/00-Raw/raw-test.js
  opencti-platform/opencti-graphql/tests/04-sync/00-Raw/sync-raw-test.js
  opencti-platform/opencti-graphql/tests/utils/syncCountHelper.ts
Labels: technical improvement, filigran team

#11400 [frontend] No label filter should be displayed as 'label is empty' (#11378)
  opencti-platform/opencti-front/src/components/fields/EntitySelectWithTypes.tsx
  opencti-platform/opencti-front/src/components/filters/FilterChipPopover.tsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainertKnowledgeTimeLineBar.tsx
  opencti-platform/opencti-front/src/private/components/common/lists/FilterAutocomplete.tsx
  opencti-platform/opencti-front/src/private/components/workspaces/WorkspaceTurnToContainerDialog.tsx
  opencti-platform/opencti-front/src/utils/filters/SearchEntitiesUtil.ts
  opencti-platform/opencti-front/src/utils/filters/filtersHelpers-types.ts
  opencti-platform/opencti-front/src/utils/filters/filtersUtils.tsx
  opencti-platform/opencti-front/src/utils/filters/useFiltersState.tsx
  opencti-platform/opencti-front/src/utils/filters/useSearchEntities.tsx
  opencti-platform/opencti-front/src/utils/hooks/useLocalStorage.ts
Labels: filigran team

#11367 [frontend/backend] rework CSV Mapper in CSV Feed format
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCSVFeedUtils.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreationDeprecated.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvFeedTestDialog.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvInlineMapperForm.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-converter.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/src/modules/internal/csvMapper/csvMapper-domain.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/csv-feed-test.ts
  opencti-platform/opencti-graphql/tests/01-unit/domain/csv-mapper-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-csv-test.ts
Labels: filigran team

#11465 [frontend] filter nested entities to add/create for network traffic type (#11247)
  opencti-platform/opencti-front/src/private/components/common/stix_nested_ref_relationships/StixNestedRefRelationshipCreationFromEntity.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableCreation.jsx
  opencti-platform/opencti-front/src/private/components/observations/stix_cyber_observables/StixCyberObservableNestedEntities.jsx
Labels: filigran team

#11467 [frontend] fix playbooks canva overflow (#11166)
  opencti-platform/opencti-front/src/private/components/data/playbooks/Playbook.jsx
Labels: filigran team

#11415 [backend/frontend] - (UpdatingCSVFeed): allow user to create on the fly user #11047
  opencti-platform/opencti-front/lang/front/de.json
  opencti-platform/opencti-front/lang/front/en.json
  opencti-platform/opencti-front/lang/front/es.json
  opencti-platform/opencti-front/lang/front/fr.json
  opencti-platform/opencti-front/lang/front/it.json
  opencti-platform/opencti-front/lang/front/ja.json
  opencti-platform/opencti-front/lang/front/ko.json
  opencti-platform/opencti-front/lang/front/zh.json
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreation.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvCreationUserHandling.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEdition.tsx
  opencti-platform/opencti-front/src/private/components/data/ingestionCsv/IngestionCsvEditionUserHandling.tsx
  opencti-platform/opencti-front/src/private/components/settings/Policies.tsx
  opencti-platform/opencti-front/src/private/components/settings/groups/GroupSetDefaultGroupForIngestionUsers.tsx
  opencti-platform/opencti-front/src/schema/relay.schema.graphql
  opencti-platform/opencti-graphql/src/generated/graphql.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-domain.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv-resolver.ts
  opencti-platform/opencti-graphql/src/modules/ingestion/ingestion-csv.graphql
  opencti-platform/opencti-graphql/tests/02-integration/01-database/ingestion-csv-domain-test.ts
  opencti-platform/opencti-graphql/tests/02-integration/02-resolvers/ingestion-csv-test.ts
  opencti-platform/opencti-graphql/tests/utils/syncCountHelper.ts
Labels: filigran team

#11523 [frontend] Buttons display in Attack patterns matrix view (#11517)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatterns.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChain.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainMatrix.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrix.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrixColumns.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualKnowledge.tsx
Labels: filigran team

#11525 [ci] Add sleep 10 for e2e start too (#11507)
  .drone.yml
Labels: filigran team

#11516 [frontend] Remove view icons from graph exported image (#10047)
  opencti-platform/opencti-front/src/components/ExportButtons.jsx
  opencti-platform/opencti-front/src/private/components/common/containers/ContainerHeader.jsx
Labels: filigran team

#11528 [frontend] Buttons display in Attack patterns matrix view (#11517)
  opencti-platform/opencti-front/src/private/components/analyses/groupings/GroupingKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/analyses/reports/ReportKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_incidents/IncidentKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfis/CaseRfiKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/cases/case_rfts/CaseRftKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatterns.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChain.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainContainer.tsx
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/StixDomainObjectAttackPatternsKillChainMatrix.tsx
  opencti-platform/opencti-front/src/private/components/events/incidents/IncidentKnowledge.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrix.tsx
  opencti-platform/opencti-front/src/private/components/techniques/attack_patterns/attack_patterns_matrix/AttackPatternsMatrixColumns.tsx
  opencti-platform/opencti-front/src/private/components/threats/campaigns/CampaignKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/intrusion_sets/IntrusionSetKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_group/ThreatActorGroupKnowledge.jsx
  opencti-platform/opencti-front/src/private/components/threats/threat_actors_individual/ThreatActorIndividualKnowledge.tsx
Labels: filigran team

#11508 [ci] Display drone runner name (#11507)
  .drone.yml
Labels: filigran team

#11547 [frontend] Wrong access warning when setting default dashboard for organization (#11240)
  opencti-platform/opencti-front/src/private/components/settings/organizations/SettingsOrganization.tsx
Labels: filigran team

#11542 [backend] Hostnames are case sensitive (#11253)
  opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js
Labels: filigran team
